// dino-spawn-weights.const.ts
export const DINO_SPAWN_WEIGHTS = [
  { nameFr: 'Ankylosaure', dinoNameTag: 'Anky', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Argentavis', dinoNameTag: 'Argent', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Chauve-Souris', dinoNameTag: 'Bat', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Brontosaure', dinoNameTag: 'Bronto', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Carnotaurus', dinoNameTag: 'Carno', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Coelacanthe', dinoNameTag: 'Coel', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Dilophosaure', dinoNameTag: 'Dilo', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Dodo', dinoNameTag: 'Dodo', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Mammouth', dinoNameTag: 'Mammoth', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Mégalodon', dinoNameTag: 'Mega', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Parasaur', dinoNameTag: 'Para', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Phiomia', dinoNameTag: 'Phiomia', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Piranha', dinoNameTag: 'Piranha', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Ptéranodon', dinoNameTag: 'Ptera', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Raptor', dinoNameTag: 'Raptor', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Rex', dinoNameTag: 'Rex', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Smilodon', dinoNameTag: 'Sabertooth', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Sarcosuchus', dinoNameTag: 'Sarco', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Scorpion', dinoNameTag: 'Scorpion', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Stegosaure', dinoNameTag: 'Stego', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Spinosaure', dinoNameTag: 'Spino', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Araignée', dinoNameTag: 'Spider', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Boa Titan', dinoNameTag: 'Titanboa', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Tricératops', dinoNameTag: 'Trike', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
  { nameFr: 'Tortue', dinoNameTag: 'Turtle', spawnWeightMultiplier: 1, overrideSpawnLimitPercentage: false, spawnLimitPercentage: 0.5 },
];
