export const ARMOR = [
  {
    nameFr: "Bottes Tek",
    key: "PrimalItemArmor_TekBoots_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Bottes en Tek, offrant une protection avancée contre les dégâts.",
    image: "assets/images/armures/PrimalItemArmor_TekBoots_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/TEK/PrimalItemArmor_TekBoots.PrimalItemArmor_TekBoots'",
    id: null
  },
  {
    nameFr: "Bottes anti-radiation",
    key: "PrimalItemArmor_HazardSuitBoots_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Bottes offrant une protection contre les radiations.",
    image: "assets/images/armures/PrimalItemArmor_HazardSuitBoots_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Armor/HazardSuit/PrimalItemArmor_HazardSuitBoots.PrimalItemArmor_HazardSuitBoots'",
    id: null
  },
  {
    nameFr: "Bottes de Camouflage",
    key: "PrimalItemArmor_GhillieBoots_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Bottes de camouflage en ghillie, idéales pour la discrétion.",
    image: "assets/images/armures/PrimalItemArmor_GhillieBoots_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Ghillie/PrimalItemArmor_GhillieBoots.PrimalItemArmor_GhillieBoots'",
    id: null
  },
  {
    nameFr: "Bottes du désert",
    key: "PrimalItemArmor_DesertClothBoots_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Bottes légères conçues pour les environnements désertiques.",
    image: "assets/images/armures/PrimalItemArmor_DesertClothBoots_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/Outfits/PrimalItemArmor_DesertClothBoots.PrimalItemArmor_DesertClothBoots'",
    id: null
  },
  {
    nameFr: "Bouclier Anti-Émeute",
    key: "PrimalItemArmor_TransparentRiotShield_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Bouclier transparent anti-émeute, utile pour se protéger des attaques.",
    image: "assets/images/armures/PrimalItemArmor_TransparentRiotShield_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_TransparentRiotShield.PrimalItemArmor_TransparentRiotShield'",
    id: null
  },
  {
    nameFr: "Bouclier Tek",
    key: "PrimalItemArmor_ShieldTek_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Bouclier Tek offrant une protection renforcée contre les attaques.",
    image: "assets/images/armures/PrimalItemArmor_ShieldTek_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_ShieldTek.PrimalItemArmor_ShieldTek'",
    id: null
  },
  {
    nameFr: "Bouclier en bois",
    key: "PrimalItemArmor_WoodShield_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Bouclier fabriqué en bois, offrant une protection basique.",
    image: "assets/images/armures/PrimalItemArmor_WoodShield_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_WoodShield.PrimalItemArmor_WoodShield'",
    id: null
  },
  {
    nameFr: "Bouclier en métal",
    key: "PrimalItemArmor_MetalShield_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Bouclier robuste en métal, offrant une protection accrue.",
    image: "assets/images/armures/PrimalItemArmor_MetalShield_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_MetalShield.PrimalItemArmor_MetalShield'",
    id: null
  },
  {
    nameFr: "Casque Tek",
    key: "PrimalItemArmor_TekHelmet_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Casque en Tek, offrant une protection avancée pour la tête.",
    image: "assets/images/armures/PrimalItemArmor_TekHelmet_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/TEK/PrimalItemArmor_TekHelmet.PrimalItemArmor_TekHelmet'",
    id: null
  },
  {
    nameFr: "Casque anti-radiation",
    key: "PrimalItemArmor_HazardSuitHelmet_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Casque conçu pour protéger contre les radiations.",
    image: "assets/images/armures/PrimalItemArmor_HazardSuitHelmet_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Armor/HazardSuit/PrimalItemArmor_HazardSuitHelmet.PrimalItemArmor_HazardSuitHelmet'",
    id: null
  },
  {
    nameFr: "Chapeau et lunettes du désert",
    key: "PrimalItemArmor_DesertClothGogglesHelmet_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Chapeau avec lunettes intégrées pour le désert.",
    image: "assets/images/armures/PrimalItemArmor_DesertClothGogglesHelmet_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/Outfits/PrimalItemArmor_DesertClothGogglesHelmet.PrimalItemArmor_DesertClothGogglesHelmet'",
    id: null
  },
  {
    nameFr: "Combinaison de Plongée",
    key: "PrimalItemArmor_ScubaPants_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Combinaison de plongée pour explorer les profondeurs sous-marines.",
    image: "assets/images/armures/PrimalItemArmor_ScubaPants_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/SCUBA/PrimalItemArmor_ScubaPants.PrimalItemArmor_ScubaPants'",
    id: null
  },
  {
    nameFr: "Gantelets Tek",
    key: "PrimalItemArmor_TekGloves_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Gantelets en Tek, offrant une protection avancée pour les mains.",
    image: "assets/images/armures/PrimalItemArmor_TekGloves_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/TEK/PrimalItemArmor_TekGloves.PrimalItemArmor_TekGloves'",
    id: null
  },
  {
    nameFr: "Gants anti-radiation",
    key: "PrimalItemArmor_HazardSuitGloves_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Gants offrant une protection contre les radiations.",
    image: "assets/images/armures/PrimalItemArmor_HazardSuitGloves_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Armor/HazardSuit/PrimalItemArmor_HazardSuitGloves.PrimalItemArmor_HazardSuitGloves'",
    id: null
  },
  {
    nameFr: "Gants de Camouflage",
    key: "PrimalItemArmor_GhillieGloves_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Gants de camouflage en ghillie pour la discrétion.",
    image: "assets/images/armures/PrimalItemArmor_GhillieGloves_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Ghillie/PrimalItemArmor_GhillieGloves.PrimalItemArmor_GhillieGloves'",
    id: null
  },
  {
    nameFr: "Gants du désert",
    key: "PrimalItemArmor_DesertClothGloves_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Gants légers conçus pour les environnements désertiques.",
    image: "assets/images/armures/PrimalItemArmor_DesertClothGloves_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/Outfits/PrimalItemArmor_DesertClothGloves.PrimalItemArmor_DesertClothGloves'",
    id: null
  },
  {
    nameFr: "Jambières Tek",
    key: "PrimalItemArmor_TekLeggings_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Jambières en Tek, offrant une protection avancée pour les jambes.",
    image: "assets/images/armures/PrimalItemArmor_TekLeggings_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/TEK/PrimalItemArmor_TekLeggings.PrimalItemArmor_TekLeggings'",
    id: null
  },
  {
    nameFr: "Jambières anti-radiation",
    key: "PrimalItemArmor_HazardSuitPants_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Jambières offrant une protection contre les radiations.",
    image: "assets/images/armures/PrimalItemArmor_HazardSuitPants_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Armor/HazardSuit/PrimalItemArmor_HazardSuitPants.PrimalItemArmor_HazardSuitPants'",
    id: null
  },
  {
    nameFr: "Jambières de Camouflage",
    key: "PrimalItemArmor_GhilliePants_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Jambières de camouflage en ghillie pour la discrétion.",
    image: "assets/images/armures/PrimalItemArmor_GhilliePants_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Ghillie/PrimalItemArmor_GhilliePants.PrimalItemArmor_GhilliePants'",
    id: null
  },
  {
    nameFr: "Jambières du désert",
    key: "PrimalItemArmor_DesertClothPants_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Jambières légères conçues pour les environnements désertiques.",
    image: "assets/images/armures/PrimalItemArmor_DesertClothPants_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/Outfits/PrimalItemArmor_DesertClothPants.PrimalItemArmor_DesertClothPants'",
    id: null
  },
  {
    nameFr: "Armure d'Elite",
    key: "PrimalItemArmor_RiotChestpiece_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Armure renforcée offrant une excellente protection contre les attaques.",
    image: "assets/images/armures/PrimalItemArmor_RiotChestpiece_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Riot/PrimalItemArmor_RiotChestpiece.PrimalItemArmor_RiotChestpiece'",
    id: null
  },
  {
    nameFr: "Armure Tek",
    key: "PrimalItemArmor_TekChestpiece_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Armure Tek offrant une protection avancée pour le torse.",
    image: "assets/images/armures/PrimalItemArmor_TekChestpiece_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/TEK/PrimalItemArmor_TekChestpiece.PrimalItemArmor_TekChestpiece'",
    id: null
  },
  {
    nameFr: "Armure anti-radiation",
    key: "PrimalItemArmor_HazardSuitShirt_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Armure offrant une protection contre les radiations.",
    image: "assets/images/armures/PrimalItemArmor_HazardSuitShirt_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Armor/HazardSuit/PrimalItemArmor_HazardSuitShirt.PrimalItemArmor_HazardSuitShirt'",
    id: null
  },
  {
    nameFr: "Armure de Camouflage",
    key: "PrimalItemArmor_GhillieShirt_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Armure de camouflage en ghillie pour la discrétion.",
    image: "assets/images/armures/PrimalItemArmor_GhillieShirt_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Ghillie/PrimalItemArmor_GhillieShirt.PrimalItemArmor_GhillieShirt'",
    id: null
  },
  {
    nameFr: "Armure du désert",
    key: "PrimalItemArmor_DesertClothShirt_C",
    defaultValue: 1,
    category: "ARMOR",
    description: "Armure légère conçue pour les environnements désertiques.",
    image: "assets/images/armures/PrimalItemArmor_DesertClothShirt_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/Outfits/PrimalItemArmor_DesertClothShirt.PrimalItemArmor_DesertClothShirt'",
    id: null
  }
]
