export const ARTIFACTS = [
  {
    nameFr: "Aileron de Mégalodon (Alpha)",
    key: "PrimalItemResource_ApexDrop_AlphaMegalodon_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un aileron de Mégalodon Alpha.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_AlphaMegalodon.PrimalItemResource_ApexDrop_AlphaMegalodon'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Alpha Reaper King Barb",
    key: "PrimalItemResource_ApexDrop_ReaperBarb_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un dard du Roi Reaper Alpha.",
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_ReaperBarb.PrimalItemResource_ApexDrop_ReaperBarb'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Artéfact de Puissance",
    key: "PrimalItemArtifact_09_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant la puissance.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_09.PrimalItemArtifact_09'",
    stackable: false,
    id: 154
  },
  {
    nameFr: "Artéfact de l'Immunité",
    key: "PrimalItemArtifact_08_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant l'immunité.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_08.PrimalItemArtifact_08'",
    stackable: false,
    id: 153
  },
  {
    nameFr: "Artéfact de la Bête",
    key: "PrimalItemArtifact_12_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant la bête.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_12.PrimalItemArtifact_12'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Artéfact de la Croissance",
    key: "PrimalItemArtifact_Extinction_ForestKaiju_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant la croissance.",
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_Extinction_ForestKaiju.PrimalItemArtifact_Extinction_ForestKaiju'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Artéfact de la Meute",
    key: "PrimalItemArtifact_02_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant la meute.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_02.PrimalItemArtifact_02'",
    stackable: false,
    id: 147
  },
  {
    nameFr: "Artéfact de la Ruse",
    key: "PrimalItemArtifact_11_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant la ruse.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_11.PrimalItemArtifact_11'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Artéfact de la Sagesse",
    key: "PrimalItemArtifact_05_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant la sagesse.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_05.PrimalItemArtifact_05'",
    stackable: false,
    id: 150
  },
  {
    nameFr: "Artéfact des Profondeurs",
    key: "PrimalItemArtifactAB_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant les profondeurs.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifactAB.PrimalItemArtifactAB'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Artéfact des Profondeurs",
    key: "PrimalItemArtifactSE_02_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant les profondeurs.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifactSE_02.PrimalItemArtifactSE_02'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Artéfact des Ténèbres",
    key: "PrimalItemArtifactAB_2_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant les ténèbres.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifactAB_2.PrimalItemArtifactAB_2'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Artéfact du Chaos",
    key: "PrimalItemArtifact_Extinction_DesertKaiju_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant le chaos.",
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_Extinction_DesertKaiju.PrimalItemArtifact_Extinction_DesertKaiju'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Artéfact du Chasseur",
    key: "PrimalItemArtifact_01_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant le chasseur.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_01.PrimalItemArtifact_01'",
    stackable: false,
    id: 146
  },
  {
    nameFr: "Artéfact du Colosse",
    key: "PrimalItemArtifact_03_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant le colosse.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_03.PrimalItemArtifact_03'",
    stackable: false,
    id: 148
  },
  {
    nameFr: "Artéfact du Destructeur",
    key: "PrimalItemArtifactSE_03_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant le destructeur.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifactSE_03.PrimalItemArtifactSE_03'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Artéfact du Dévoreur",
    key: "PrimalItemArtifact_07_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant le dévoreur.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_07.PrimalItemArtifact_07'",
    stackable: false,
    id: 152
  },
  {
    nameFr: "Artéfact du Gardien des Portes",
    key: "PrimalItemArtifactSE_01_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant le gardien des portes.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifactSE_01.PrimalItemArtifactSE_01'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Artéfact du Perdu",
    key: "PrimalItemArtifactAB_4_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant le perdu.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifactAB_4.PrimalItemArtifactAB_4'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Artéfact du Rôdeur",
    key: "PrimalItemArtifactAB_3_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant le rôdeur.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifactAB_3.PrimalItemArtifactAB_3'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Artéfact du Seigneur du Ciel",
    key: "PrimalItemArtifact_06_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant le seigneur du ciel.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_06.PrimalItemArtifact_06'",
    stackable: false,
    id: 151
  },
  {
    nameFr: "Artéfact du Sournois",
    key: "PrimalItemArtifact_04_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant le sournois.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_04.PrimalItemArtifact_04'",
    stackable: false,
    id: 149
  },
  {
    nameFr: "Artéfact du Vide",
    key: "PrimalItemArtifact_Extinction_IceKaiju_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un artéfact symbolisant le vide.",
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_Extinction_IceKaiju.PrimalItemArtifact_Extinction_IceKaiju'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Bras de Carnotaure (Alpha)",
    key: "PrimalItemResource_ApexDrop_AlphaCarno_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un bras de Carnotaure Alpha.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_AlphaCarno.PrimalItemResource_ApexDrop_AlphaCarno'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Bras de Tyrannosaure",
    key: "PrimalItemResource_ApexDrop_Rex_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un bras de Tyrannosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Rex.PrimalItemResource_ApexDrop_Rex'",
    stackable: true,
    id: 157
  },
  {
    nameFr: "Cerveau d'Allosaure",
    key: "PrimalItemResource_ApexDrop_Allo_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un cerveau d'Allosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Allo.PrimalItemResource_ApexDrop_Allo'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Coeur corrompu",
    key: "PrimalItemResource_RareDrop_CorruptHeart_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un coeur corrompu.",
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_RareDrop_CorruptHeart.PrimalItemResource_RareDrop_CorruptHeart'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Coeur de Giganotosaure",
    key: "PrimalItemResource_ApexDrop_Giga_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un coeur de Giganotosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Giga.PrimalItemResource_ApexDrop_Giga'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Croc de Basilic (Alpha)",
    key: "PrimalItemResource_ApexDrop_Basilisk_Alpha_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un croc de Basilic Alpha.",
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Basilisk_Alpha.PrimalItemResource_ApexDrop_Basilisk_Alpha'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Crâne de X-Tricératops (Alpha)",
    key: "PrimalItemSkin_TrikeSkullHelmet_Retrieve_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un crâne de X-Tricératops Alpha.",
    blueprint: "Blueprint'/Game/Genesis/Missions/Retrieve/RetrieveItems/TrikeSkull/PrimalItemSkin_TrikeSkullHelmet_Retrieve.PrimalItemSkin_TrikeSkullHelmet_Retrieve'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Crête de Spinosaure",
    key: "PrimalItemResource_ApexDrop_Spino_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une crête de Spinosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Spino.PrimalItemResource_ApexDrop_Spino'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Dent de Mosasaure (Alpha)",
    key: "PrimalItemResource_ApexDrop_AlphaMosasaur_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une dent de Mosasaure Alpha.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_AlphaMosasaur.PrimalItemResource_ApexDrop_AlphaMosasaur'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Dent de Mégalodon à rayures dorées",
    key: "PrimalItemResource_RetrieveMegTooth_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une dent de Mégalodon avec des rayures dorées.",
    blueprint: "Blueprint'/Game/Genesis/Missions/Retrieve/RetrieveItems/MegTeeth/PrimalItemResource_RetrieveMegTooth.PrimalItemResource_RetrieveMegTooth'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Dent de Mégalodon",
    key: "PrimalItemResource_ApexDrop_Megalodon_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une dent de Mégalodon.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Megalodon.PrimalItemResource_ApexDrop_Megalodon'",
    stackable: true,
    id: 156
  },
  {
    nameFr: "Dent de Tyrannosaure (Alpha)",
    key: "PrimalItemResource_ApexDrop_AlphaRex_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une dent de Tyrannosaure Alpha.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_AlphaRex.PrimalItemResource_ApexDrop_AlphaRex'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Glande de phéromone de Faucheur",
    key: "PrimalItemResource_XenomorphPheromoneGland_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une glande de phéromone de Faucheur.",
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_XenomorphPheromoneGland.PrimalItemResource_XenomorphPheromoneGland'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Glande de phéromone de Roi Faucheur",
    key: "PrimalItemResource_RetrieveReaperGland_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une glande de phéromone de Roi Faucheur.",
    blueprint: "Blueprint'/Game/Genesis/Missions/Retrieve/RetrieveItems/ReaperGland/PrimalItemResource_RetrieveReaperGland.PrimalItemResource_RetrieveReaperGland'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Graisse de Basilosaure",
    key: "PrimalItemResource_ApexDrop_Basilo_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "De la graisse de Basilosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Basilo.PrimalItemResource_ApexDrop_Basilo'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Graisse de Leedsichthys (Alpha)",
    key: "PrimalItemResource_ApexDrop_AlphaLeeds_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "De la graisse de Leedsichthys Alpha.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_AlphaLeeds.PrimalItemResource_ApexDrop_AlphaLeeds'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Griffe de Raptor (Alpha)",
    key: "PrimalItemResource_ApexDrop_AlphaRaptor_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une griffe de Raptor Alpha.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_AlphaRaptor.PrimalItemResource_ApexDrop_AlphaRaptor'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Griffe de Thylacoleo",
    key: "PrimalItemResource_ApexDrop_Thylaco_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une griffe de Thylacoleo.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Thylaco.PrimalItemResource_ApexDrop_Thylaco'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Griffes de Thérizinosaure",
    key: "PrimalItemResource_ApexDrop_Theriz_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Des griffes de Thérizinosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Theriz.PrimalItemResource_ApexDrop_Theriz'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Implant Humain",
    key: "PrimalItem_StartingNote_C",
    defaultValue: 1,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un implant humain.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Notes/PrimalItem_StartingNote.PrimalItem_StartingNote'",
    stackable: false,
    id: 133
  },
  {
    nameFr: "Oeil de Tusoteuthis (Alpha)",
    key: "PrimalItemResource_ApexDrop_AlphaTuso_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un oeil de Tusoteuthis Alpha.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_AlphaTuso.PrimalItemResource_ApexDrop_AlphaTuso'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Peau de Sarcosuchus",
    key: "PrimalItemResource_ApexDrop_Sarco_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une peau de Sarcosuchus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Sarco.PrimalItemResource_ApexDrop_Sarco'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Pince de Karkinos",
    key: "PrimalItemResource_ApexDrop_CrabClaw_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une pince de Karkinos.",
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_CrabClaw.PrimalItemResource_ApexDrop_CrabClaw'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Plume de Dragon Rocheux",
    key: "PrimalItemResource_ApexDrop_RockDrake_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une plume de Dragon Rocheux.",
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_RockDrake.PrimalItemResource_ApexDrop_RockDrake'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Poumons de Yutyrannus",
    key: "PrimalItemResource_ApexDrop_Yuty_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Des poumons de Yutyrannus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Yuty.PrimalItemResource_ApexDrop_Yuty'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Serre d'Argentavis",
    key: "PrimalItemResource_ApexDrop_Argentavis_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une serre d'Argentavis.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Argentavis.PrimalItemResource_ApexDrop_Argentavis'",
    stackable: true,
    id: 155
  },
  {
    nameFr: "Serre de Cristal",
    key: "PrimalItemResource_ApexDrop_CrystalWyvern_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une serre de Cristal.",
    blueprint: "Blueprint'/Game/PrimalEarth/Dinos/CrystalWyvern/PrimalItemResource_ApexDrop_CrystalWyvern.PrimalItemResource_ApexDrop_CrystalWyvern'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Serre de Cristal Alpha",
    key: "PrimalItemResource_ApexDrop_AlphaCrystalWyvern_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une serre de Cristal Alpha.",
    blueprint: "Blueprint'/Game/PrimalEarth/Dinos/CrystalWyvern/Mega/PrimalItemResource_ApexDrop_AlphaCrystalWyvern.PrimalItemResource_ApexDrop_AlphaCrystalWyvern'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Serre de feu",
    key: "PrimalItemResource_ApexDrop_FireWyvern_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une serre de feu.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_FireWyvern.PrimalItemResource_ApexDrop_FireWyvern'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Serre du poison",
    key: "PrimalItemResource_ApexDrop_PoisonWyvern_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une serre de poison.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_PoisonWyvern.PrimalItemResource_ApexDrop_PoisonWyvern'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Serre du tonnerre",
    key: "PrimalItemResource_ApexDrop_LightningWyvern_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une serre du tonnerre.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_LightningWyvern.PrimalItemResource_ApexDrop_LightningWyvern'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Tentacule de Tusoteuthis",
    key: "PrimalItemResource_ApexDrop_Tuso_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Un tentacule de Tusoteuthis.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Tuso.PrimalItemResource_ApexDrop_Tuso'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Toxine de Megalania",
    key: "PrimalItemResource_ApexDrop_Megalania_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une toxine de Megalania.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Megalania.PrimalItemResource_ApexDrop_Megalania'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Venin de Titanoboa",
    key: "PrimalItemResource_ApexDrop_Boa_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Du venin de Titanoboa.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Boa.PrimalItemResource_ApexDrop_Boa'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Vertèbre de Sauropode",
    key: "PrimalItemResource_ApexDrop_Sauro_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une vertèbre de Sauropode.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Sauro.PrimalItemResource_ApexDrop_Sauro'",
    stackable: true,
    id: 158
  },
  {
    nameFr: "Vessie de Sacagaz",
    key: "PrimalItemResource_ApexDrop_GasBag_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Une vessie de Sacagaz.",
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_GasBag.PrimalItemResource_ApexDrop_GasBag'",
    stackable: true,
    id: null
  },
  {
    nameFr: "Écailles de Basilic",
    key: "PrimalItemResource_ApexDrop_Basilisk_C",
    defaultValue: 100,
    category: "Artéfacts",
    image: "assets/images/artifact/PrimalItemResource_",
    description: "Des écailles de Basilic.",
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_ApexDrop_Basilisk.PrimalItemResource_ApexDrop_Basilisk'",
    stackable: true,
    id: null
  }
];
