export const CHIBIS = [
  {
    nameFr: "Chibi-Achatina",
    key: "PrimalItemSkin_ChibiDino_Achatina_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Achatina_C.png",
    description: "Un familier Chibi Achatina.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Achatina.PrimalItemSkin_ChibiDino_Achatina'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Allosaure",
    key: "PrimalItemSkin_ChibiDino_Allosaurus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Allosaurus_C.png",
    description: "Un familier Chibi Allosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Allosaurus.PrimalItemSkin_ChibiDino_Allosaurus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Amargasaure",
    key: "PrimalItemSkin_ChibiDino_Amarga_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Amarga_C.png",
    description: "Un familier Chibi Amargasaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Amarga.PrimalItemSkin_ChibiDino_Amarga'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Ammonite",
    key: "PrimalItemSkin_ChibiDino_Ammonite_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Ammonite_C.png",
    description: "Un familier Chibi Ammonite.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Ammonite.PrimalItemSkin_ChibiDino_Ammonite'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Andrewsarchus",
    key: "PrimalItemSkin_ChibiDino_Andrewsarchus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Andrewsarchus_C.png",
    description: "Un familier Chibi Andrewsarchus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Andrewsarchus.PrimalItemSkin_ChibiDino_Andrewsarchus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Ankylosaure",
    key: "PrimalItemSkin_ChibiDino_Ankylosaurus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Ankylosaurus_C.png",
    description: "Un familier Chibi Ankylosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Ankylosaurus.PrimalItemSkin_ChibiDino_Ankylosaurus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Aranéo",
    key: "PrimalItemSkin_ChibiDino_Araneo_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Araneo_C.png",
    description: "Un familier Chibi Aranéo.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Araneo.PrimalItemSkin_ChibiDino_Araneo'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Archaeopteryx",
    key: "PrimalItemSkin_ChibiDino_Archaeopteryx_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Archaeopteryx_C.png",
    description: "Un familier Chibi Archaeopteryx.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Archaeopteryx.PrimalItemSkin_ChibiDino_Archaeopteryx'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Argentavis",
    key: "PrimalItemSkin_ChibiDino_Argent_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Argent_C.png",
    description: "Un familier Chibi Argentavis.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Argent.PrimalItemSkin_ChibiDino_Argent'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Astrocetus",
    key: "PrimalItemSkin_ChibiDino_Astrocetus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Astrocetus_C.png",
    description: "Un familier Chibi Astrocetus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Astrocetus.PrimalItemSkin_ChibiDino_Astrocetus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Astrodelphis",
    key: "PrimalItemSkin_ChibiDino_Astrodelphis_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Astrodelphis_C.png",
    description: "Un familier Chibi Astrodelphis.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Astrodelphis.PrimalItemSkin_ChibiDino_Astrodelphis'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Baryonyx",
    key: "PrimalItemSkin_ChibiDino_Baryonyx_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Baryonyx_C.png",
    description: "Un familier Chibi Baryonyx.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Baryonyx.PrimalItemSkin_ChibiDino_Baryonyx'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Basilic",
    key: "PrimalItemSkin_ChibiDino_Basilisk_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Basilisk_C.png",
    description: "Un familier Chibi Basilic.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Basilisk.PrimalItemSkin_ChibiDino_Basilisk'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Basilic fantôme",
    key: "PrimalItemSkin_ChibiDino_BasiliskGhost_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_BasiliskGhost_C.png",
    description: "Un familier Chibi Basilic fantôme.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_BasiliskGhost.PrimalItemSkin_ChibiDino_BasiliskGhost'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Baudroie abyssale",
    key: "PrimalItemSkin_ChibiDino_Anglerfish_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Anglerfish_C.png",
    description: "Un familier Chibi Baudroie abyssale.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Anglerfish.PrimalItemSkin_ChibiDino_Anglerfish'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Beelzebufo",
    key: "PrimalItemSkin_ChibiDino_Beelzebufo_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Beelzebufo_C.png",
    description: "Un familier Chibi Beelzebufo.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Beelzebufo.PrimalItemSkin_ChibiDino_Beelzebufo'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Bloodstalker",
    key: "PrimalItemSkin_ChibiDino_BogSpider_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_BogSpider_C.png",
    description: "Un familier Chibi Bloodstalker.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_BogSpider.PrimalItemSkin_ChibiDino_BogSpider'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Brontosaure",
    key: "PrimalItemSkin_ChibiDino_Bronto_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Bronto_C.png",
    description: "Un familier Chibi Brontosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Bronto.PrimalItemSkin_ChibiDino_Bronto'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Brontosaure squelettique",
    key: "PrimalItemSkin_ChibiDino_Bronto_Bone_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Bronto_Bone_C.png",
    description: "Un familier Chibi Brontosaure squelettique.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Bronto_Bone.PrimalItemSkin_ChibiDino_Bronto_Bone'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Broodmother",
    key: "PrimalItemSkin_ChibiDino_BroodMother_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_BroodMother_C.png",
    description: "Un familier Chibi Broodmother.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_BroodMother.PrimalItemSkin_ChibiDino_BroodMother'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Bulbdog",
    key: "PrimalItemSkin_ChibiDino_Bulbdog_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Bulbdog_C.png",
    description: "Un familier Chibi Bulbdog.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Bulbdog.PrimalItemSkin_ChibiDino_Bulbdog'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Bulbdog festif (Rouge)",
    key: "PrimalItemSkin_ChibiDino_Bulbdog_FestiveR_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Bulbdog_FestiveR_C.png",
    description: "Un familier Chibi Bulbdog festif rouge.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Bulbdog_FestiveR.PrimalItemSkin_ChibiDino_Bulbdog_FestiveR'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Bulbdog festif (Vert)",
    key: "PrimalItemSkin_ChibiDino_Bulbdog_FestiveG_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Bulbdog_FestiveG_C.png",
    description: "Un familier Chibi Bulbdog festif vert.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Bulbdog_FestiveG.PrimalItemSkin_ChibiDino_Bulbdog_FestiveG'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Bulbdog terrifiant",
    key: "PrimalItemSkin_ChibiDino_Bulbdog_Pumpkin_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Bulbdog_Pumpkin_C.png",
    description: "Un familier Chibi Bulbdog terrifiant.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Bulbdog_Pumpkin.PrimalItemSkin_ChibiDino_Bulbdog_Pumpkin'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Carbonemys",
    key: "PrimalItemSkin_ChibiDino_Carbonemys_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Carbonemys_C.png",
    description: "Un familier Chibi Carbonemys.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Carbonemys.PrimalItemSkin_ChibiDino_Carbonemys'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Carcharodontosaure",
    key: "PrimalItemSkin_ChibiDino_Carcha_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Carcha_C.png",
    description: "Un familier Chibi Carcharodontosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Carcha.PrimalItemSkin_ChibiDino_Carcha'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Carnotaure",
    key: "PrimalItemSkin_ChibiDino_Carnotaurus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Carnotaurus_C.png",
    description: "Un familier Chibi Carnotaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Carnotaurus.PrimalItemSkin_ChibiDino_Carnotaurus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Carnotaure squelettique",
    key: "PrimalItemSkin_ChibiDino_Carnotaurus_Bone_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Carnotaurus_Bone_C.png",
    description: "Un familier Chibi Carnotaure squelettique.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Carnotaurus_Bone.PrimalItemSkin_ChibiDino_Carnotaurus_Bone'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Castoroides",
    key: "PrimalItemSkin_ChibiDino_Castroides_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Castroides_C.png",
    description: "Un familier Chibi Castoroides.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Castroides.PrimalItemSkin_ChibiDino_Castroides'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Sorcière Harfang",
    key: "PrimalItemSkin_ChibiDino_WitchingOwl_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_WitchingOwl_C.png",
    description: "Un familier Chibi Sorcière Harfang.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_WitchingOwl.PrimalItemSkin_ChibiDino_WitchingOwl'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Cnidaria",
    key: "PrimalItemSkin_ChibiDino_Cnidaria_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Cnidaria_C.png",
    description: "Un familier Chibi Cnidaria.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Cnidaria.PrimalItemSkin_ChibiDino_Cnidaria'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Daeodon",
    key: "PrimalItemSkin_ChibiDino_Daeodon_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Daeodon_C.png",
    description: "Un familier Chibi Daeodon.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Daeodon.PrimalItemSkin_ChibiDino_Daeodon'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Deinonychus",
    key: "PrimalItemSkin_ChibiDino_Deinonychus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Deinonychus_C.png",
    description: "Un familier Chibi Deinonychus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Deinonychus.PrimalItemSkin_ChibiDino_Deinonychus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Desmodus",
    key: "PrimalItemSkin_ChibiDino_Desmodus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Desmodus_C.png",
    description: "Un familier Chibi Desmodus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Desmodus.PrimalItemSkin_ChibiDino_Desmodus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Dilophosaure",
    key: "PrimalItemSkin_ChibiDino_Dilophosaur_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Dilophosaur_C.png",
    description: "Un familier Chibi Dilophosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Dilophosaur.PrimalItemSkin_ChibiDino_Dilophosaur'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Dinopithèque",
    key: "PrimalItemSkin_ChibiDino_Dinopithecus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Dinopithecus_C.png",
    description: "Un familier Chibi Dinopithèque.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Dinopithecus.PrimalItemSkin_ChibiDino_Dinopithecus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Diplodocus",
    key: "PrimalItemSkin_ChibiDino_Diplodocus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Diplodocus_C.png",
    description: "Un familier Chibi Diplodocus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Diplodocus.PrimalItemSkin_ChibiDino_Diplodocus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Dévoreur",
    key: "PrimalItemSkin_ChibiDino_Seeker_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Seeker_C.png",
    description: "Un familier Chibi Dévoreur.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Seeker.PrimalItemSkin_ChibiDino_Seeker'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Dodo",
    key: "PrimalItemSkin_ChibiDino_Dodo_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Dodo_C.png",
    description: "Un familier Chibi Dodo.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Dodo.PrimalItemSkin_ChibiDino_Dodo'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Dodo Deal with it",
    key: "PrimalItemSkin_ChibiDino_DodoDealWithIt_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_DodoDealWithIt_C.png",
    description: "Un familier Chibi Dodo Deal with it.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_DodoDealWithIt.PrimalItemSkin_ChibiDino_DodoDealWithIt'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Doedicurus",
    key: "PrimalItemSkin_ChibiDino_Doedicurus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Doedicurus_C.png",
    description: "Un familier Chibi Doedicurus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Doedicurus.PrimalItemSkin_ChibiDino_Doedicurus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Dragon Rocheux",
    key: "PrimalItemSkin_ChibiDino_RockDrake_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_RockDrake_C.png",
    description: "Un familier Chibi Dragon Rocheux.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_RockDrake.PrimalItemSkin_ChibiDino_RockDrake'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Dunkleosteus",
    key: "PrimalItemSkin_ChibiDino_Dunkleo_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Dunkleo_C.png",
    description: "Un familier Chibi Dunkleosteus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Dunkleo.PrimalItemSkin_ChibiDino_Dunkleo'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Exécuteur",
    key: "PrimalItemSkin_ChibiDino_Enforcer_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Enforcer_C.png",
    description: "Un familier Chibi Exécuteur.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Enforcer.PrimalItemSkin_ChibiDino_Enforcer'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Equus",
    key: "PrimalItemSkin_ChibiDino_Equus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Equus_C.png",
    description: "Un familier Chibi Equus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Equus.PrimalItemSkin_ChibiDino_Equus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Faucheur",
    key: "PrimalItemSkin_ChibiDino_Reaper_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Reaper_C.png",
    description: "Un familier Chibi Faucheur.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Reaper.PrimalItemSkin_ChibiDino_Reaper'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Fenrir",
    key: "PrimalItemSkin_ChibiDino_Fenrir_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Fenrir_C.png",
    description: "Un familier Chibi Fenrir.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Fenrir.PrimalItemSkin_ChibiDino_Fenrir'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Ferox (Grand)",
    key: "PrimalItemSkin_ChibiDino_Shapeshifter_Large_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Shapeshifter_Large_C.png",
    description: "Un familier Chibi Ferox (Grand).",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Shapeshifter_Large.PrimalItemSkin_ChibiDino_Shapeshifter_Large'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Ferox (Petit)",
    key: "PrimalItemSkin_ChibiDino_Shapeshifter_Small_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Shapeshifter_Small_C.png",
    description: "Un familier Chibi Ferox (Petit).",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Shapeshifter_Small.PrimalItemSkin_ChibiDino_Shapeshifter_Small'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Fjordhawk",
    key: "PrimalItemSkin_ChibiDino_Fjordhawk_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Fjordhawk_C.png",
    description: "Un familier Chibi Fjordhawk.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Fjordhawk.PrimalItemSkin_ChibiDino_Fjordhawk'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-GachaClaus",
    key: "PrimalItemSkin_ChibiDino_GachaClaus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_GachaClaus_C.png",
    description: "Un familier Chibi GachaClaus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_GachaClaus.PrimalItemSkin_ChibiDino_GachaClaus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Gallimimus",
    key: "PrimalItemSkin_ChibiDino_Gallimimus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Gallimimus_C.png",
    description: "Un familier Chibi Gallimimus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Gallimimus.PrimalItemSkin_ChibiDino_Gallimimus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Gecko luisant",
    key: "PrimalItemSkin_ChibiDino_Glowtail_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Glowtail_C.png",
    description: "Un familier Chibi Gecko luisant.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Glowtail.PrimalItemSkin_ChibiDino_Glowtail'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Gecko festif (Rouge)",
    key: "PrimalItemSkin_ChibiDino_Glowtail_FestiveR_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Glowtail_FestiveR_C.png",
    description: "Un familier Chibi Gecko festif rouge.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Glowtail_FestiveR.PrimalItemSkin_ChibiDino_Glowtail_FestiveR'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Gecko festif (Vert)",
    key: "PrimalItemSkin_ChibiDino_Glowtail_FestiveG_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Glowtail_FestiveG_C.png",
    description: "Un familier Chibi Gecko festif vert.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Glowtail_FestiveG.PrimalItemSkin_ChibiDino_Glowtail_FestiveG'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Gecko peluche",
    key: "PrimalItemSkin_ChibiDino_GlowtailStuffed_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_GlowtailStuffed_C.png",
    description: "Un familier Chibi Gecko peluche.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_GlowtailStuffed.PrimalItemSkin_ChibiDino_GlowtailStuffed'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Giganotosaure",
    key: "PrimalItemSkin_ChibiDino_Gigant_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Gigant_C.png",
    description: "Un familier Chibi Giganotosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Gigant.PrimalItemSkin_ChibiDino_Gigant'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Giganotosaure squelettique",
    key: "PrimalItemSkin_ChibiDino_Gigant_Bone_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Gigant_Bone_C.png",
    description: "Un familier Chibi Giganotosaure squelettique.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Gigant_Bone.PrimalItemSkin_ChibiDino_Gigant_Bone'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Gigantopithèque",
    key: "PrimalItemSkin_ChibiDino_Gigantopithecus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Gigantopithecus_C.png",
    description: "Un familier Chibi Gigantopithèque.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Gigantopithecus.PrimalItemSkin_ChibiDino_Gigantopithecus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Golem de pierre",
    key: "PrimalItemSkin_ChibiDino_RockGolem_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_RockGolem_C.png",
    description: "Un familier Chibi Golem de pierre.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_RockGolem.PrimalItemSkin_ChibiDino_RockGolem'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Griffon",
    key: "PrimalItemSkin_ChibiDino_Griffin_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Griffin_C.png",
    description: "Un familier Chibi Griffon.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Griffin.PrimalItemSkin_ChibiDino_Griffin'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Harfang des neiges",
    key: "PrimalItemSkin_ChibiDino_SnowOwl_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_SnowOwl_C.png",
    description: "Un familier Chibi Harfang des neiges.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_SnowOwl.PrimalItemSkin_ChibiDino_SnowOwl'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Iguanodon",
    key: "PrimalItemSkin_ChibiDino_Iguanodon_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Iguanodon_C.png",
    description: "Un familier Chibi Iguanodon.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Iguanodon.PrimalItemSkin_ChibiDino_Iguanodon'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Jerboa squelettique",
    key: "PrimalItemSkin_ChibiDino_Jerboa_Bone_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Jerboa_Bone_C.png",
    description: "Un familier Chibi Jerboa squelettique.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Jerboa_Bone.PrimalItemSkin_ChibiDino_Jerboa_Bone'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Jerbunny",
    key: "PrimalItemSkin_ChibiDino_JerboaBunny_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_JerboaBunny_C.png",
    description: "Un familier Chibi Jerbunny.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_JerboaBunny.PrimalItemSkin_ChibiDino_JerboaBunny'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Kairuku à col blanc",
    key: "PrimalItemSkin_ChibiDino_TophatKairuku_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_TophatKairuku_C.png",
    description: "Un familier Chibi Kairuku à col blanc.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_TophatKairuku.PrimalItemSkin_ChibiDino_TophatKairuku'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Kairuku",
    key: "PrimalItemSkin_ChibiDino_Kairuku_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Kairuku_C.png",
    description: "Un familier Chibi Kairuku.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Kairuku.PrimalItemSkin_ChibiDino_Kairuku'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Kaprosuchus",
    key: "PrimalItemSkin_ChibiDino_Kaprosuchus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Kaprosuchus_C.png",
    description: "Un familier Chibi Kaprosuchus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Kaprosuchus.PrimalItemSkin_ChibiDino_Kaprosuchus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Karkinos",
    key: "PrimalItemSkin_ChibiDino_Karkinos_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Karkinos_C.png",
    description: "Un familier Chibi Karkinos.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Karkinos.PrimalItemSkin_ChibiDino_Karkinos'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Kentrosaure",
    key: "PrimalItemSkin_ChibiDino_Kentrosaurus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Kentrosaurus_C.png",
    description: "Un familier Chibi Kentrosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Kentrosaurus.PrimalItemSkin_ChibiDino_Kentrosaurus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Lapin",
    key: "PrimalItemSkin_ChibiDino_Bunny_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Bunny_C.png",
    description: "Un familier Chibi Lapin.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Bunny.PrimalItemSkin_ChibiDino_Bunny'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Lézard épineux",
    key: "PrimalItemSkin_ChibiDino_SpineyLizard_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_SpineyLizard_C.png",
    description: "Un familier Chibi Lézard épineux.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_SpineyLizard.PrimalItemSkin_ChibiDino_SpineyLizard'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Licorne",
    key: "PrimalItemSkin_ChibiDino_Unicorn_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Unicorn_C.png",
    description: "Un familier Chibi Licorne.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Unicorn.PrimalItemSkin_ChibiDino_Unicorn'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Loup Sinistre",
    key: "PrimalItemSkin_ChibiDino_Direwolf_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Direwolf_C.png",
    description: "Un familier Chibi Loup Sinistre.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Direwolf.PrimalItemSkin_ChibiDino_Direwolf'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Loup Sinistre fantôme",
    key: "PrimalItemSkin_ChibiDino_DirewolfGhost_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_DirewolfGhost_C.png",
    description: "Un familier Chibi Loup Sinistre fantôme.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_DirewolfGhost.PrimalItemSkin_ChibiDino_DirewolfGhost'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Loutre",
    key: "PrimalItemSkin_ChibiDino_Otter_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Otter_C.png",
    description: "Un familier Chibi Loutre.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Otter.PrimalItemSkin_ChibiDino_Otter'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Loutre bonnet",
    key: "PrimalItemSkin_ChibiDino_OtterBonnet_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_OtterBonnet_C.png",
    description: "Un familier Chibi Loutre bonnet.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_OtterBonnet.PrimalItemSkin_ChibiDino_OtterBonnet'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Loutre chapeau de paille",
    key: "PrimalItemSkin_ChibiDino_OtterStrawHat_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_OtterStrawHat_C.png",
    description: "Un familier Chibi Loutre chapeau de paille.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_OtterStrawHat.PrimalItemSkin_ChibiDino_OtterStrawHat'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Lumicorne",
    key: "PrimalItemSkin_ChibiDino_Shinehorn_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Shinehorn_C.png",
    description: "Un familier Chibi Lumicorne.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Shinehorn.PrimalItemSkin_ChibiDino_Shinehorn'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Lumicorne festif (Rouge)",
    key: "PrimalItemSkin_ChibiDino_Shinehorn_FestiveR_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Shinehorn_FestiveR_C.png",
    description: "Un familier Chibi Lumicorne festif rouge.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Shinehorn_FestiveR.PrimalItemSkin_ChibiDino_Shinehorn_FestiveR'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Lumicorne festif (Vert)",
    key: "PrimalItemSkin_ChibiDino_Shinehorn_FestiveG_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Shinehorn_FestiveG_C.png",
    description: "Un familier Chibi Lumicorne festif vert.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Shinehorn_FestiveG.PrimalItemSkin_ChibiDino_Shinehorn_FestiveG'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Lumicorne printanier",
    key: "PrimalItemSkin_ChibiDino_SpringShinehorn_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_SpringShinehorn_C.png",
    description: "Un familier Chibi Lumicorne printanier.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_SpringShinehorn.PrimalItemSkin_ChibiDino_SpringShinehorn'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Lymantria",
    key: "PrimalItemSkin_ChibiDino_Lymantria_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Lymantria_C.png",
    description: "Un familier Chibi Lymantria.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Lymantria.PrimalItemSkin_ChibiDino_Lymantria'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Maewing",
    key: "PrimalItemSkin_ChibiDino_Maewing_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Maewing_C.png",
    description: "Un familier Chibi Maewing.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Maewing.PrimalItemSkin_ChibiDino_Maewing'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Magmasaure",
    key: "PrimalItemSkin_ChibiDino_Cherufe_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Cherufe_C.png",
    description: "Un familier Chibi Magmasaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Cherufe.PrimalItemSkin_ChibiDino_Cherufe'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Mammouth",
    key: "PrimalItemSkin_ChibiDino_Mammoth_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Mammoth_C.png",
    description: "Un familier Chibi Mammouth.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Mammoth.PrimalItemSkin_ChibiDino_Mammoth'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Managarm",
    key: "PrimalItemSkin_ChibiDino_Managarmr_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Managarmr_C.png",
    description: "Un familier Chibi Managarm.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Managarmr.PrimalItemSkin_ChibiDino_Managarmr'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Manta",
    key: "PrimalItemSkin_ChibiDino_Manta_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Manta_C.png",
    description: "Un familier Chibi Manta.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Manta.PrimalItemSkin_ChibiDino_Manta'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Mantis",
    key: "PrimalItemSkin_ChibiDino_Mantis_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Mantis_C.png",
    description: "Un familier Chibi Mantis.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Mantis.PrimalItemSkin_ChibiDino_Mantis'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Mantis fantomatique",
    key: "PrimalItemSkin_ChibiDino_MantisGhost_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_MantisGhost_C.png",
    description: "Un familier Chibi Mantis fantomatique.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_MantisGhost.PrimalItemSkin_ChibiDino_MantisGhost'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Megalania",
    key: "PrimalItemSkin_ChibiDino_Megalania_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Megalania_C.png",
    description: "Un familier Chibi Megalania.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Megalania.PrimalItemSkin_ChibiDino_Megalania'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Mégalocéros",
    key: "PrimalItemSkin_ChibiDino_Megaloceros_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Megaloceros_C.png",
    description: "Un familier Chibi Mégalocéros.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Megaloceros.PrimalItemSkin_ChibiDino_Megaloceros'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Mégalodon",
    key: "PrimalItemSkin_ChibiDino_Megalodon_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Megalodon_C.png",
    description: "Un familier Chibi Mégalodon.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Megalodon.PrimalItemSkin_ChibiDino_Megalodon'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Mégathérium",
    key: "PrimalItemSkin_ChibiDino_Megatherium_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Megatherium_C.png",
    description: "Un familier Chibi Mégathérium.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Megatherium.PrimalItemSkin_ChibiDino_Megatherium'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Mésopithèque",
    key: "PrimalItemSkin_ChibiDino_Mesopithecus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Mesopithecus_C.png",
    description: "Un familier Chibi Mésopithèque.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Mesopithecus.PrimalItemSkin_ChibiDino_Mesopithecus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Microraptor",
    key: "PrimalItemSkin_ChibiDino_Microraptor_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Microraptor_C.png",
    description: "Un familier Chibi Microraptor.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Microraptor.PrimalItemSkin_ChibiDino_Microraptor'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Mosasaure",
    key: "PrimalItemSkin_ChibiDino_Mosa_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Mosa_C.png",
    description: "Un familier Chibi Mosasaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Mosa.PrimalItemSkin_ChibiDino_Mosa'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Moschops",
    key: "PrimalItemSkin_ChibiDino_Moschops_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Moschops_C.png",
    description: "Un familier Chibi Moschops.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Moschops.PrimalItemSkin_ChibiDino_Moschops'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Noglin",
    key: "PrimalItemSkin_ChibiDino_BrainSlug_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_BrainSlug_C.png",
    description: "Un familier Chibi Noglin.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_BrainSlug.PrimalItemSkin_ChibiDino_BrainSlug'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Noglin festif",
    key: "PrimalItemSkin_ChibiDino_BrainSlugXmas_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_BrainSlugXmas_C.png",
    description: "Un familier Chibi Noglin festif.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_BrainSlugXmas.PrimalItemSkin_ChibiDino_BrainSlugXmas'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Oiseau-Terreur",
    key: "PrimalItemSkin_ChibiDino_TerrorBird_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_TerrorBird_C.png",
    description: "Un familier Chibi Oiseau-Terreur.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_TerrorBird.PrimalItemSkin_ChibiDino_TerrorBird'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Onyc",
    key: "PrimalItemSkin_ChibiDino_Onyc_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Onyc_C.png",
    description: "Un familier Chibi Onyc.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Onyc.PrimalItemSkin_ChibiDino_Onyc'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Ours Sinistre",
    key: "PrimalItemSkin_ChibiDino_Direbear_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Direbear_C.png",
    description: "Un familier Chibi Ours Sinistre.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Direbear.PrimalItemSkin_ChibiDino_Direbear'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Oviraptor",
    key: "PrimalItemSkin_ChibiDino_Oviraptor_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Oviraptor_C.png",
    description: "Un familier Chibi Oviraptor.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Oviraptor.PrimalItemSkin_ChibiDino_Oviraptor'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Ovis",
    key: "PrimalItemSkin_ChibiDino_Sheep_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Sheep_C.png",
    description: "Un familier Chibi Ovis.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Sheep.PrimalItemSkin_ChibiDino_Sheep'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Pachycéphalosaure",
    key: "PrimalItemSkin_ChibiDino_Pachy_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Pachy_C.png",
    description: "Un familier Chibi Pachycéphalosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Pachy.PrimalItemSkin_ChibiDino_Pachy'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Paraceratherium",
    key: "PrimalItemSkin_ChibiDino_Paraceratherium_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Paraceratherium_C.png",
    description: "Un familier Chibi Paraceratherium.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Paraceratherium.PrimalItemSkin_ChibiDino_Paraceratherium'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Parasaure",
    key: "PrimalItemSkin_ChibiDino_Parasaur_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Parasaur_C.png",
    description: "Un familier Chibi Parasaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Parasaur.PrimalItemSkin_ChibiDino_Parasaur'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Paire-o-Saures",
    key: "PrimalItemSkin_ChibiDino_Pairosaurs_VDay_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Pairosaurs_VDay_C.png",
    description: "Un familier Chibi Paire-o-Saures.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Pairosaurs_VDay.PrimalItemSkin_ChibiDino_Pairosaurs_VDay'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Pelagornis",
    key: "PrimalItemSkin_ChibiDino_Pelagornis_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Pelagornis_C.png",
    description: "Un familier Chibi Pelagornis.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Pelagornis.PrimalItemSkin_ChibiDino_Pelagornis'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Phiomia",
    key: "PrimalItemSkin_ChibiDino_Phiomia_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Phiomia_C.png",
    description: "Un familier Chibi Phiomia.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Phiomia.PrimalItemSkin_ChibiDino_Phiomia'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Phénix",
    key: "PrimalItemSkin_ChibiDino_Phoenix_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Phoenix_C.png",
    description: "Un familier Chibi Phénix.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Phoenix.PrimalItemSkin_ChibiDino_Phoenix'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Plésiosaure",
    key: "PrimalItemSkin_ChibiDino_Plesiosaur_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Plesiosaur_C.png",
    description: "Un familier Chibi Plésiosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Plesiosaur.PrimalItemSkin_ChibiDino_Plesiosaur'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Plumineux",
    key: "PrimalItemSkin_ChibiDino_Featherlight_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Featherlight_C.png",
    description: "Un familier Chibi Plumineux.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Featherlight.PrimalItemSkin_ChibiDino_Featherlight'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Plumineux festif (Rouge)",
    key: "PrimalItemSkin_ChibiDino_Featherlight_FestiveR_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Featherlight_FestiveR_C.png",
    description: "Un familier Chibi Plumineux festif rouge.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Featherlight_FestiveR.PrimalItemSkin_ChibiDino_Featherlight_FestiveR'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Plumineux festif (Vert)",
    key: "PrimalItemSkin_ChibiDino_Featherlight_FestiveG_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Featherlight_FestiveG_C.png",
    description: "Un familier Chibi Plumineux festif vert.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Featherlight_FestiveG.PrimalItemSkin_ChibiDino_Featherlight_FestiveG'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Poussin de Pâques",
    key: "PrimalItemSkin_ChibiDino_EasterChick_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_EasterChick_C.png",
    description: "Un familier Chibi Poussin de Pâques.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_EasterChick.PrimalItemSkin_ChibiDino_EasterChick'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Procoptodon",
    key: "PrimalItemSkin_ChibiDino_Procoptodon_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Procoptodon_C.png",
    description: "Un familier Chibi Procoptodon.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Procoptodon.PrimalItemSkin_ChibiDino_Procoptodon'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Ptérodactyle",
    key: "PrimalItemSkin_ChibiDino_Ptero_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Ptero_C.png",
    description: "Un familier Chibi Ptérodactyle.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Ptero.PrimalItemSkin_ChibiDino_Ptero'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Purlovia",
    key: "PrimalItemSkin_ChibiDino_Purlovia_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Purlovia_C.png",
    description: "Un familier Chibi Purlovia.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Purlovia.PrimalItemSkin_ChibiDino_Purlovia'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Quetzalcoatlus",
    key: "PrimalItemSkin_ChibiDino_Quetzalcoatlus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Quetzalcoatlus_C.png",
    description: "Un familier Chibi Quetzalcoatlus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Quetzalcoatlus.PrimalItemSkin_ChibiDino_Quetzalcoatlus'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Raptor",
    key: "PrimalItemSkin_ChibiDino_Raptor_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Raptor_C.png",
    description: "Un familier Chibi Raptor.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Raptor.PrimalItemSkin_ChibiDino_Raptor'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Raptor Dodo",
    key: "PrimalItemSkin_ChibiDino_DodoRaptor_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_DodoRaptor_C.png",
    description: "Un familier Chibi Raptor Dodo.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_DodoRaptor.PrimalItemSkin_ChibiDino_DodoRaptor'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Raptor squelettique",
    key: "PrimalItemSkin_ChibiDino_RaptorBone_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_RaptorBone_C.png",
    description: "Un familier Chibi Raptor squelettique.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_RaptorBone.PrimalItemSkin_ChibiDino_RaptorBone'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Reine Méganeura",
    key: "PrimalItemSkin_ChibiDino_MegaDragonfly_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_MegaDragonfly_C.png",
    description: "Un familier Chibi Reine Méganeura.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_MegaDragonfly.PrimalItemSkin_ChibiDino_MegaDragonfly'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Rhyniognatha",
    key: "PrimalItemSkin_ChibiDino_Rhynio_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Rhynio_C.png",
    description: "Un familier Chibi Rhyniognatha.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Rhynio.PrimalItemSkin_ChibiDino_Rhynio'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Sac à Fumier",
    key: "PrimalItemSkin_ChibiDino_FertileRaptor_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_FertileRaptor_C.png",
    description: "Un familier Chibi Sac à Fumier.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_FertileRaptor.PrimalItemSkin_ChibiDino_FertileRaptor'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Sabre de feu",
    key: "PrimalItemSkin_ChibiDino_FireSabertooth_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_FireSabertooth_C.png",
    description: "Un familier Chibi Sabre de feu.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_FireSabertooth.PrimalItemSkin_ChibiDino_FireSabertooth'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Sabertooth",
    key: "PrimalItemSkin_ChibiDino_Sabertooth_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Sabertooth_C.png",
    description: "Un familier Chibi Sabertooth.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Sabertooth.PrimalItemSkin_ChibiDino_Sabertooth'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Sabre-de-feu",
    key: "PrimalItemSkin_ChibiDino_FireSabertooth_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_FireSabertooth_C.png",
    description: "Un familier Chibi Sabre-de-feu.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_FireSabertooth.PrimalItemSkin_ChibiDino_FireSabertooth'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Sanglier effrayant",
    key: "PrimalItemSkin_ChibiDino_BoarPig_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_BoarPig_C.png",
    description: "Un familier Chibi Sanglier effrayant.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_BoarPig.PrimalItemSkin_ChibiDino_BoarPig'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Scorpion",
    key: "PrimalItemSkin_ChibiDino_Scorpion_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Scorpion_C.png",
    description: "Un familier Chibi Scorpion.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Scorpion.PrimalItemSkin_ChibiDino_Scorpion'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Sinomegasaurus",
    key: "PrimalItemSkin_ChibiDino_Sinomacrops_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Sinomacrops_C.png",
    description: "Un familier Chibi Sinomegasaurus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Sinomacrops.PrimalItemSkin_ChibiDino_Sinomacrops'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Sinomacrops",
    key: "PrimalItemSkin_ChibiDino_Sinomacrops_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Sinomacrops_C.png",
    description: "Un familier Chibi Sinomacrops.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Sinomacrops.PrimalItemSkin_ChibiDino_Sinomacrops'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Sinomegasaurus",
    key: "PrimalItemSkin_ChibiDino_Sinomacrops_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Sinomacrops_C.png",
    description: "Un familier Chibi Sinomegasaurus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Sinomacrops.PrimalItemSkin_ChibiDino_Sinomacrops'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Spino",
    key: "PrimalItemSkin_ChibiDino_Spino_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Spino_C.png",
    description: "Un familier Chibi Spino.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Spino.PrimalItemSkin_ChibiDino_Spino'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Squelette",
    key: "PrimalItemSkin_ChibiDino_Skeleton_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Skeleton_C.png",
    description: "Un familier Chibi Squelette.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Skeleton.PrimalItemSkin_ChibiDino_Skeleton'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Spinosaure",
    key: "PrimalItemSkin_ChibiDino_Spino_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Spino_C.png",
    description: "Un familier Chibi Spinosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Spino.PrimalItemSkin_ChibiDino_Spino'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Stégosaure",
    key: "PrimalItemSkin_ChibiDino_Stego_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Stego_C.png",
    description: "Un familier Chibi Stégosaure.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Stego.PrimalItemSkin_ChibiDino_Stego'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Stégosaure squelettique",
    key: "PrimalItemSkin_ChibiDino_StegoBone_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_StegoBone_C.png",
    description: "Un familier Chibi Stégosaure squelettique.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_StegoBone.PrimalItemSkin_ChibiDino_StegoBone'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Tapejara",
    key: "PrimalItemSkin_ChibiDino_Tapejara_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Tapejara_C.png",
    description: "Un familier Chibi Tapejara.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Tapejara.PrimalItemSkin_ChibiDino_Tapejara'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Terradon",
    key: "PrimalItemSkin_ChibiDino_Terradon_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Terradon_C.png",
    description: "Un familier Chibi Terradon.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Terradon.PrimalItemSkin_ChibiDino_Terradon'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Terrorbird",
    key: "PrimalItemSkin_ChibiDino_Terrorbird_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Terrorbird_C.png",
    description: "Un familier Chibi Terrorbird.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Terrorbird.PrimalItemSkin_ChibiDino_Terrorbird'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Thylacoleo",
    key: "PrimalItemSkin_ChibiDino_Thylacoleo_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Thylacoleo_C.png",
    description: "Un familier Chibi Thylacoleo.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Thylacoleo.PrimalItemSkin_ChibiDino_Thylacoleo'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Tricératops",
    key: "PrimalItemSkin_ChibiDino_Trike_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Trike_C.png",
    description: "Un familier Chibi Tricératops.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Trike.PrimalItemSkin_ChibiDino_Trike'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Troodon",
    key: "PrimalItemSkin_ChibiDino_Troodon_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Troodon_C.png",
    description: "Un familier Chibi Troodon.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Troodon.PrimalItemSkin_ChibiDino_Troodon'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Tyrolien",
    key: "PrimalItemSkin_ChibiDino_Yuty_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Yuty_C.png",
    description: "Un familier Chibi Tyrolien.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Yuty.PrimalItemSkin_ChibiDino_Yuty'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Voile rouge",
    key: "PrimalItemSkin_ChibiDino_SailFin_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_SailFin_C.png",
    description: "Un familier Chibi Voile rouge.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_SailFin.PrimalItemSkin_ChibiDino_SailFin'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Velonasaur",
    key: "PrimalItemSkin_ChibiDino_Velonasaur_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Velonasaur_C.png",
    description: "Un familier Chibi Velonasaur.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Velonasaur.PrimalItemSkin_ChibiDino_Velonasaur'",
    stackable: false,
    id: null
  },
  {
    nameFr: "Chibi-Yutyrannus",
    key: "PrimalItemSkin_ChibiDino_Yutyrannus_C",
    defaultValue: 1,
    category: "CHIBIS",
    image: "assets/images/CHIBIS/PrimalItemSkin_ChibiDino_Yutyrannus_C.png",
    description: "Un familier Chibi Yutyrannus.",
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/ChibiDinos/PrimalItemSkin_ChibiDino_Yutyrannus.PrimalItemSkin_ChibiDino_Yutyrannus'",
    stackable: false,
    id: null
  }
];
