export const COLORANTS = [
  {
    nameFr: "Colorant Ardoise",
    key: "PrimalItemDye_Slate_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Ardoise pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Slate_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Slate.PrimalItemDye_Slate'",
    id: 408
  },
  {
    nameFr: "Colorant Argent",
    key: "PrimalItemDye_Silver_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Argent pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Silver_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Silver.PrimalItemDye_Silver'",
    id: 363
  },
  {
    nameFr: "Colorant Blanc",
    key: "PrimalItemDye_White_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Blanc pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_White_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_White.PrimalItemDye_White'",
    id: 65
  },
  {
    nameFr: "Colorant Bleu Marine",
    key: "PrimalItemDye_Navy_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Bleu Marine pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Navy_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Navy.PrimalItemDye_Navy'",
    id: 406
  },
  {
    nameFr: "Colorant Bleu",
    key: "PrimalItemDye_Blue_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Bleu pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Blue_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Blue.PrimalItemDye_Blue'",
    id: 60
  },
  {
    nameFr: "Colorant Boue",
    key: "PrimalItemDye_Mud_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Boue pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Mud_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Mud.PrimalItemDye_Mud'",
    id: 405
  },
  {
    nameFr: "Colorant Brique",
    key: "PrimalItemDye_Brick_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Brique pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Brick_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Brick.PrimalItemDye_Brick'",
    id: 403
  },
  {
    nameFr: "Colorant Bronze",
    key: "PrimalItemDye_Tan_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Bronze pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Tan_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Tan.PrimalItemDye_Tan'",
    id: 365
  },
  {
    nameFr: "Colorant Brun",
    key: "PrimalItemDye_Brown_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Brun pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Brown_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Brown.PrimalItemDye_Brown'",
    id: 66
  },
  {
    nameFr: "Colorant Ciel",
    key: "PrimalItemDye_Sky_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Ciel pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Sky_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Sky.PrimalItemDye_Sky'",
    id: 364
  },
  {
    nameFr: "Colorant Cyan",
    key: "PrimalItemDye_Cyan_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Cyan pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Cyan_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Cyan.PrimalItemDye_Cyan'",
    id: 67
  },
  {
    nameFr: "Colorant Forêt",
    key: "PrimalItemDye_Forest_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Forêt pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Forest_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Forest.PrimalItemDye_Forest'",
    id: 359
  },
  {
    nameFr: "Colorant Jaune",
    key: "PrimalItemDye_Yellow_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Jaune pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Yellow_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Yellow.PrimalItemDye_Yellow'",
    id: 61
  },
  {
    nameFr: "Colorant Magenta",
    key: "PrimalItemDye_ActuallyMagenta_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Magenta pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_ActuallyMagenta_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_ActuallyMagenta.PrimalItemDye_ActuallyMagenta'",
    id: 402
  },
  {
    nameFr: "Colorant Magenta",
    key: "PrimalItemDye_Magenta_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Magenta pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Magenta_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Magenta.PrimalItemDye_Magenta'",
    id: 68
  },
  {
    nameFr: "Colorant Mandarine",
    key: "PrimalItemDye_Tangerine_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Mandarine pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Tangerine_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Tangerine.PrimalItemDye_Tangerine'",
    id: 366
  },
  {
    nameFr: "Colorant Melon Cantaloup",
    key: "PrimalItemDye_Cantaloupe_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Melon Cantaloup pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Cantaloupe_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Cantaloupe.PrimalItemDye_Cantaloupe'",
    id: 404
  },
  {
    nameFr: "Colorant Noir",
    key: "PrimalItemDye_Black_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Noir pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Black_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Black.PrimalItemDye_Black'",
    id: 64
  },
  {
    nameFr: "Colorant Olive",
    key: "PrimalItemDye_Olive_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Olive pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Olive_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Olive.PrimalItemDye_Olive'",
    id: 407
  },
  {
    nameFr: "Colorant Orange",
    key: "PrimalItemDye_Orange_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Orange pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Orange_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Orange.PrimalItemDye_Orange'",
    id: 63
  },
  {
    nameFr: "Colorant Parchemin",
    key: "PrimalItemDye_Parchment_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Parchemin pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Parchment_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Parchment.PrimalItemDye_Parchment'",
    id: 364
  },
  {
    nameFr: "Colorant Rose",
    key: "PrimalItemDye_Pink_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Rose pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Pink_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Pink.PrimalItemDye_Pink'",
    id: 361
  },
  {
    nameFr: "Colorant Rouge",
    key: "PrimalItemDye_Red_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Rouge pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Red_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Red.PrimalItemDye_Red'",
    id: 58
  },
  {
    nameFr: "Colorant Royauté",
    key: "PrimalItemDye_Royalty_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Royauté pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Royalty_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Royalty.PrimalItemDye_Royalty'",
    id: 362
  },
  {
    nameFr: "Colorant Vert",
    key: "PrimalItemDye_Green_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Vert pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Green_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Green.PrimalItemDye_Green'",
    id: 59
  },
  {
    nameFr: "Colorant Violet",
    key: "PrimalItemDye_Purple_C",
    defaultValue: 100,
    category: "Colorants",
    description: "Colorant Violet pour teindre vos objets.",
    image: "assets/images/colorants/PrimalItemDye_Purple_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Purple.PrimalItemDye_Purple'",
    id: 62
  }
]
