export const CONSUMABLES = [
  {
    nameFr: "Amarberry",
    key: "PrimalItemConsumable_Berry_Amarberry_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Baie d'Amarberry, utilisée pour la cuisine et comme nourriture pour les créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Berry_Amarberry_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Amarberry.PrimalItemConsumable_Berry_Amarberry'",
    id: 116
  },
  {
    nameFr: "Antidote",
    key: "PrimalItemConsumable_CureLow_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Antidote pour soigner les maladies.",
    image: "assets/images/consommables/PrimalItemConsumable_CureLow_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/BaseBPs/PrimalItemConsumable_CureLow.PrimalItemConsumable_CureLow'",
    id: null
  },
  {
    nameFr: "Azulberry",
    key: "PrimalItemConsumable_Berry_Azulberry_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Baie d'Azulberry, utilisée pour la cuisine et comme nourriture pour les créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Berry_Azulberry_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Azulberry.PrimalItemConsumable_Berry_Azulberry'",
    id: 117
  },
  {
    nameFr: "Biotoxine",
    key: "PrimalItemConsumable_JellyVenom_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Biotoxine, utilisée pour créer des fléchettes tranquillisantes.",
    image: "assets/images/consommables/PrimalItemConsumable_JellyVenom_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_JellyVenom.PrimalItemConsumable_JellyVenom'",
    id: null
  },
  {
    nameFr: "Bière",
    key: "PrimalItemResource_Beer_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Bière artisanale, consommable pour divers effets.",
    image: "assets/images/consommables/PrimalItemResource_Beer_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Beer.PrimalItemResource_Beer'",
    id: null
  },
  {
    nameFr: "Bocal d'eau (Plein)",
    key: "PrimalItemConsumable_WaterJarRefill_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Bocal d'eau plein, utilisé pour étancher la soif.",
    image: "assets/images/consommables/PrimalItemConsumable_WaterJarRefill_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_WaterJarRefill.PrimalItemConsumable_WaterJarRefill'",
    id: 16
  },
  {
    nameFr: "Bocal d'eau (Vide)",
    key: "PrimalItemConsumable_WaterJarCraftable_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Bocal d'eau vide, doit être rempli.",
    image: "assets/images/consommables/PrimalItemConsumable_WaterJarCraftable_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_WaterJarCraftable.PrimalItemConsumable_WaterJarCraftable'",
    id: 15
  },
  {
    nameFr: "Bouillon de cactus",
    key: "PrimalItemConsumable_CactusBuffSoup_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Bouillon de cactus, donne divers buffs.",
    image: "assets/images/consommables/PrimalItemConsumable_CactusBuffSoup_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CactusBuffSoup.PrimalItemConsumable_CactusBuffSoup'",
    id: null
  },
  {
    nameFr: "Bouillon de connaissance",
    key: "PrimalItemConsumable_TheHorn_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Bouillon de connaissance, augmente temporairement l'XP gagné.",
    image: "assets/images/consommables/PrimalItemConsumable_TheHorn_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_TheHorn.PrimalItemConsumable_TheHorn'",
    id: 448
  },
  {
    nameFr: "Breuvage médicinal",
    key: "PrimalItemConsumable_HealSoup_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Breuvage médicinal, régénère la santé.",
    image: "assets/images/consommables/PrimalItemConsumable_HealSoup_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_HealSoup.PrimalItemConsumable_HealSoup'",
    id: 52
  },
  {
    nameFr: "Breuvage énergétique",
    key: "PrimalItemConsumable_StaminaSoup_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Breuvage énergétique, régénère l'endurance.",
    image: "assets/images/consommables/PrimalItemConsumable_StaminaSoup_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_StaminaSoup.PrimalItemConsumable_StaminaSoup'",
    id: 53
  },
  {
    nameFr: "Carotte",
    key: "PrimalItemConsumable_Veggie_Rockarrot_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Carotte utilisée pour cuisiner ou nourrir les créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Veggie_Rockarrot_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Veggie_Rockarrot.PrimalItemConsumable_Veggie_Rockarrot'",
    id: 230
  },
  {
    nameFr: "Chair cuite de poisson supérieure",
    key: "PrimalItemConsumable_CookedPrimeMeat_Fish_C",
    defaultValue: 30,
    category: "CONSUMABLE",
    description: "Chair de poisson supérieure cuite, prête à être consommée.",
    image: "assets/images/consommables/PrimalItemConsumable_CookedPrimeMeat_Fish_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedPrimeMeat_Fish.PrimalItemConsumable_CookedPrimeMeat_Fish'",
    id: null
  },
  {
    nameFr: "Chair cuite de poisson",
    key: "PrimalItemConsumable_CookedMeat_Fish_C",
    defaultValue: 30,
    category: "CONSUMABLE",
    description: "Chair de poisson cuite, prête à être consommée.",
    image: "assets/images/consommables/PrimalItemConsumable_CookedMeat_Fish_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedMeat_Fish.PrimalItemConsumable_CookedMeat_Fish'",
    id: null
  },
  {
    nameFr: "Chair de poisson supérieure crue",
    key: "PrimalItemConsumable_RawPrimeMeat_Fish_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Chair de poisson supérieure crue, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_RawPrimeMeat_Fish_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_RawPrimeMeat_Fish.PrimalItemConsumable_RawPrimeMeat_Fish'",
    id: null
  },
  {
    nameFr: "Chair de poisson",
    key: "PrimalItemConsumable_RawMeat_Fish_C",
    defaultValue: 20,
    category: "CONSUMABLE",
    description: "Chair de poisson crue, utilisée pour nourrir les carnivores.",
    image: "assets/images/consommables/PrimalItemConsumable_RawMeat_Fish_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_RawMeat_Fish.PrimalItemConsumable_RawMeat_Fish'",
    id: null
  },
  {
    nameFr: "Champignon aquatique",
    key: "PrimalItemConsumable_Mushroom_Aquatic_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Champignon aquatique, utilisé pour divers effets.",
    image: "assets/images/consommables/PrimalItemConsumable_Mushroom_Aquatic_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Mushroom_Aquatic.PrimalItemConsumable_Mushroom_Aquatic'",
    id: null
  },
  {
    nameFr: "Champignon ascorbique",
    key: "PrimalItemConsumable_Mushroom_Ascerbic_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Champignon ascorbique, utilisé pour divers effets.",
    image: "assets/images/consommables/PrimalItemConsumable_Mushroom_Ascerbic_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Mushroom_Ascerbic.PrimalItemConsumable_Mushroom_Ascerbic'",
    id: null
  },
  {
    nameFr: "Champignon doré",
    key: "PrimalItemConsumable_Mushroom_Auric_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Champignon doré, utilisé pour divers effets.",
    image: "assets/images/consommables/PrimalItemConsumable_Mushroom_Auric_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Mushroom_Auric.PrimalItemConsumable_Mushroom_Auric'",
    id: null
  },
  {
    nameFr: "Champignon terreux",
    key: "PrimalItemResource_CommonMushroom_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Champignon terreux, utilisé pour divers effets.",
    image: "assets/images/consommables/PrimalItemResource_CommonMushroom_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemResource_CommonMushroom.PrimalItemResource_CommonMushroom'",
    id: null
  },
  {
    nameFr: "Chaudrée de Lazarus",
    key: "PrimalItemConsumable_Soup_LazarusChowder_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Chaudrée de Lazarus, augmente l'endurance sous l'eau.",
    image: "assets/images/consommables/PrimalItemConsumable_Soup_LazarusChowder_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Soup_LazarusChowder.PrimalItemConsumable_Soup_LazarusChowder'",
    id: 224
  },
  {
    nameFr: "Chili de concentration",
    key: "PrimalItemConsumable_Soup_FocalChili_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Chili de concentration, augmente la vitesse de fabrication.",
    image: "assets/images/consommables/PrimalItemConsumable_Soup_FocalChili_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Soup_FocalChili.PrimalItemConsumable_Soup_FocalChili'",
    id: 227
  },
  {
    nameFr: "Citron",
    key: "PrimalItemConsumable_Veggie_Citronal_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Citron, utilisé pour cuisiner ou nourrir les créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Veggie_Citronal_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Veggie_Citronal.PrimalItemConsumable_Veggie_Citronal'",
    id: 98
  },
  {
    nameFr: "Croquette (Oeuf d'Allosaure)",
    key: "PrimalItemConsumable_Kibble_Allo_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf d'Allosaure, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Allo_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Allo.PrimalItemConsumable_Kibble_Allo'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf d'Ankylosaure)",
    key: "PrimalItemConsumable_Kibble_AnkyloEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf d'Ankylosaure, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_AnkyloEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_AnkyloEgg.PrimalItemConsumable_Kibble_AnkyloEgg'",
    id: 323
  },
  {
    nameFr: "Croquette (Oeuf d'Aranéo)",
    key: "PrimalItemConsumable_Kibble_SpiderEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf d'Aranéo, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_SpiderEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_SpiderEgg.PrimalItemConsumable_Kibble_SpiderEgg'",
    id: 336
  },
  {
    nameFr: "Croquette (Oeuf d'Archaeopteryx)",
    key: "PrimalItemConsumable_Kibble_ArchaEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf d'Archaeopteryx, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_ArchaEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_ArchaEgg.PrimalItemConsumable_Kibble_ArchaEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf d'Argentavis)",
    key: "PrimalItemConsumable_Kibble_ArgentEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf d'Argentavis, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_ArgentEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_ArgentEgg.PrimalItemConsumable_Kibble_ArgentEgg'",
    id: 324
  },
  {
    nameFr: "Croquette (Oeuf d'Ichthyornis)",
    key: "PrimalItemConsumable_Kibble_IchthyornisEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf d'Ichthyornis, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_IchthyornisEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_IchthyornisEgg.PrimalItemConsumable_Kibble_IchthyornisEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf d'Iguanodon)",
    key: "PrimalItemConsumable_Kibble_IguanodonEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf d'Iguanodon, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_IguanodonEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_IguanodonEgg.PrimalItemConsumable_Kibble_IguanodonEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf d'Oiseau-Terreur)",
    key: "PrimalItemConsumable_Kibble_TerrorbirdEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf d'Oiseau-Terreur, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_TerrorbirdEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_TerrorbirdEgg.PrimalItemConsumable_Kibble_TerrorbirdEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf d'Oviraptor)",
    key: "PrimalItemConsumable_Kibble_OviraptorEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf d'Oviraptor, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_OviraptorEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_OviraptorEgg.PrimalItemConsumable_Kibble_OviraptorEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Baryonyx)",
    key: "PrimalItemConsumable_Kibble_BaryonyxEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Baryonyx, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_BaryonyxEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_BaryonyxEgg.PrimalItemConsumable_Kibble_BaryonyxEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Brontosaure)",
    key: "PrimalItemConsumable_Kibble_SauroEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Brontosaure, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_SauroEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_SauroEgg.PrimalItemConsumable_Kibble_SauroEgg'",
    id: 334
  },
  {
    nameFr: "Croquette (Oeuf de Carbonemys)",
    key: "PrimalItemConsumable_Kibble_TurtleEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Carbonemys, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_TurtleEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_TurtleEgg.PrimalItemConsumable_Kibble_TurtleEgg'",
    id: 340
  },
  {
    nameFr: "Croquette (Oeuf de Carnotaure)",
    key: "PrimalItemConsumable_Kibble_CarnoEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Carnotaure, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_CarnoEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_CarnoEgg.PrimalItemConsumable_Kibble_CarnoEgg'",
    id: 326
  },
  {
    nameFr: "Croquette (Oeuf de Compy)",
    key: "PrimalItemConsumable_Kibble_Compy_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Compy, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Compy_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Compy.PrimalItemConsumable_Kibble_Compy'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Dilophosaure)",
    key: "PrimalItemConsumable_Kibble_DiloEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Dilophosaure, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_DiloEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_DiloEgg.PrimalItemConsumable_Kibble_DiloEgg'",
    id: 327
  },
  {
    nameFr: "Croquette (Oeuf de Dimorphodon)",
    key: "PrimalItemConsumable_Kibble_DimorphEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Dimorphodon, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_DimorphEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_DimorphEgg.PrimalItemConsumable_Kibble_DimorphEgg'",
    id: 421
  },
  {
    nameFr: "Croquette (Oeuf de Dimétrodon)",
    key: "PrimalItemConsumable_Kibble_DimetroEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Dimétrodon, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_DimetroEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_DimetroEgg.PrimalItemConsumable_Kibble_DimetroEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Diplodocus)",
    key: "PrimalItemConsumable_Kibble_DiploEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Diplodocus, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_DiploEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_DiploEgg.PrimalItemConsumable_Kibble_DiploEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Dodo)",
    key: "PrimalItemConsumable_Kibble_DodoEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Dodo, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_DodoEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_DodoEgg.PrimalItemConsumable_Kibble_DodoEgg'",
    id: 328
  },
  {
    nameFr: "Croquette (Oeuf de Dragon Rocheux)",
    key: "PrimalItemConsumable_Kibble_RockDrakeEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Dragon Rocheux, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_RockDrakeEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_RockDrakeEgg.PrimalItemConsumable_Kibble_RockDrakeEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Gallimimus)",
    key: "PrimalItemConsumable_Kibble_GalliEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Gallimimus, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_GalliEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_GalliEgg.PrimalItemConsumable_Kibble_GalliEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Gecko luisant)",
    key: "PrimalItemConsumable_Kibble_LanternLizardEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Gecko luisant, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_LanternLizardEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_LanternLizardEgg.PrimalItemConsumable_Kibble_LanternLizardEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Kairuku)",
    key: "PrimalItemConsumable_Kibble_KairukuEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Kairuku, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_KairukuEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_KairukuEgg.PrimalItemConsumable_Kibble_KairukuEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Kaprosuchus)",
    key: "PrimalItemConsumable_Kibble_KaproEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Kaprosuchus, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_KaproEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_KaproEgg.PrimalItemConsumable_Kibble_KaproEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Kentrosaure)",
    key: "PrimalItemConsumable_Kibble_KentroEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Kentrosaure, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_KentroEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_KentroEgg.PrimalItemConsumable_Kibble_KentroEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Lystrosaure)",
    key: "PrimalItemConsumable_Kibble_LystroEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Lystrosaure, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_LystroEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_LystroEgg.PrimalItemConsumable_Kibble_LystroEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Lézard épineux)",
    key: "PrimalItemConsumable_Kibble_SpineyLizard_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Lézard épineux, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_SpineyLizard_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/SpineyLizard/PrimalItemConsumable_Kibble_SpineyLizard.PrimalItemConsumable_Kibble_SpineyLizard'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Mantis)",
    key: "PrimalItemConsumable_Kibble_Mantis_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Mantis, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Mantis_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/Mantis/PrimalItemConsumable_Kibble_Mantis.PrimalItemConsumable_Kibble_Mantis'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Megalania)",
    key: "PrimalItemConsumable_Kibble_Megalania_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Megalania, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Megalania_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Megalania.PrimalItemConsumable_Kibble_Megalania'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Microraptor)",
    key: "PrimalItemConsumable_Kibble_MicroraptorEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Microraptor, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_MicroraptorEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_MicroraptorEgg.PrimalItemConsumable_Kibble_MicroraptorEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Morellatops)",
    key: "PrimalItemConsumable_Kibble_Camelsaurus_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Morellatops, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Camelsaurus_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/Camelsaurus/PrimalItemConsumable_Kibble_Camelsaurus.PrimalItemConsumable_Kibble_Camelsaurus'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Moschops)",
    key: "PrimalItemConsumable_Kibble_MoschopsEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Moschops, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_MoschopsEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_MoschopsEgg.PrimalItemConsumable_Kibble_MoschopsEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Mégalosaure)",
    key: "PrimalItemConsumable_Kibble_MegalosaurusEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Mégalosaure, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_MegalosaurusEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_MegalosaurusEgg.PrimalItemConsumable_Kibble_MegalosaurusEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Pachycéphalosaure)",
    key: "PrimalItemConsumable_Kibble_PachyEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Pachycéphalosaure, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_PachyEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_PachyEgg.PrimalItemConsumable_Kibble_PachyEgg'",
    id: 414
  },
  {
    nameFr: "Croquette (Oeuf de Pachyrhinosaure)",
    key: "PrimalItemConsumable_Kibble_PachyRhinoEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Pachyrhinosaure, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_PachyRhinoEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_PachyRhinoEgg.PrimalItemConsumable_Kibble_PachyRhinoEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Papillon géant)",
    key: "PrimalItemConsumable_Kibble_Moth_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Papillon géant, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Moth_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/Moth/PrimalItemConsumable_Kibble_Moth.PrimalItemConsumable_Kibble_Moth'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Parasaure)",
    key: "PrimalItemConsumable_Kibble_ParaEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Parasaure, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_ParaEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_ParaEgg.PrimalItemConsumable_Kibble_ParaEgg'",
    id: 329
  },
  {
    nameFr: "Croquette (Oeuf de Pegomastax)",
    key: "PrimalItemConsumable_Kibble_PegomastaxEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Pegomastax, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_PegomastaxEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_PegomastaxEgg.PrimalItemConsumable_Kibble_PegomastaxEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Pelagornis)",
    key: "PrimalItemConsumable_Kibble_Pela_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Pelagornis, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Pela_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Pela.PrimalItemConsumable_Kibble_Pela'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Plumineux)",
    key: "PrimalItemConsumable_Kibble_LanternBirdEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Plumineux, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_LanternBirdEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_LanternBirdEgg.PrimalItemConsumable_Kibble_LanternBirdEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Ptéranodon)",
    key: "PrimalItemConsumable_Kibble_PteroEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Ptéranodon, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_PteroEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_PteroEgg.PrimalItemConsumable_Kibble_PteroEgg'",
    id: 330
  },
  {
    nameFr: "Croquette (Oeuf de Pulmonoscorpius)",
    key: "PrimalItemConsumable_Kibble_ScorpionEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Pulmonoscorpius, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_ScorpionEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_ScorpionEgg.PrimalItemConsumable_Kibble_ScorpionEgg'",
    id: 335
  },
  {
    nameFr: "Croquette (Oeuf de Quetzal)",
    key: "PrimalItemConsumable_Kibble_QuetzEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Quetzal, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_QuetzEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_QuetzEgg.PrimalItemConsumable_Kibble_QuetzEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Raptor)",
    key: "PrimalItemConsumable_Kibble_RaptorEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Raptor, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_RaptorEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_RaptorEgg.PrimalItemConsumable_Kibble_RaptorEgg'",
    id: 331
  },
  {
    nameFr: "Croquette (Oeuf de Sarcosuchus)",
    key: "PrimalItemConsumable_Kibble_SarcoEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Sarcosuchus, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_SarcoEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_SarcoEgg.PrimalItemConsumable_Kibble_SarcoEgg'",
    id: 333
  },
  {
    nameFr: "Croquette (Oeuf de Spinosaure)",
    key: "PrimalItemConsumable_Kibble_SpinoEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Spinosaure, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_SpinoEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_SpinoEgg.PrimalItemConsumable_Kibble_SpinoEgg'",
    id: 337
  },
  {
    nameFr: "Croquette (Oeuf de Stégosaure)",
    key: "PrimalItemConsumable_Kibble_StegoEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Stégosaure, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_StegoEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_StegoEgg.PrimalItemConsumable_Kibble_StegoEgg'",
    id: 338
  },
  {
    nameFr: "Croquette (Oeuf de T-Rex)",
    key: "PrimalItemConsumable_Kibble_RexEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de T-Rex, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_RexEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_RexEgg.PrimalItemConsumable_Kibble_RexEgg'",
    id: 332
  },
  {
    nameFr: "Croquette (Oeuf de Tapejara)",
    key: "PrimalItemConsumable_Kibble_TapejaraEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Tapejara, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_TapejaraEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_TapejaraEgg.PrimalItemConsumable_Kibble_TapejaraEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Thérizinosaure)",
    key: "PrimalItemConsumable_Kibble_TherizinoEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Thérizinosaure, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_TherizinoEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_TherizinoEgg.PrimalItemConsumable_Kibble_TherizinoEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Titanboa)",
    key: "PrimalItemConsumable_Kibble_BoaEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Titanboa, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_BoaEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_BoaEgg.PrimalItemConsumable_Kibble_BoaEgg'",
    id: 325
  },
  {
    nameFr: "Croquette (Oeuf de Tricératops)",
    key: "PrimalItemConsumable_Kibble_TrikeEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Tricératops, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_TrikeEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_TrikeEgg.PrimalItemConsumable_Kibble_TrikeEgg'",
    id: 339
  },
  {
    nameFr: "Croquette (Oeuf de Troodon)",
    key: "PrimalItemConsumable_Kibble_TroodonEgg_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Troodon, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_TroodonEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_TroodonEgg.PrimalItemConsumable_Kibble_TroodonEgg'",
    id: null
  },
  {
    nameFr: "Croquette (Oeuf de Vautour)",
    key: "PrimalItemConsumable_Kibble_Vulture_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette fabriquée à partir d'un œuf de Vautour, idéale pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Vulture_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/Vulture/PrimalItemConsumable_Kibble_Vulture.PrimalItemConsumable_Kibble_Vulture'",
    id: null
  },
  {
    nameFr: "Croquette Basique",
    key: "PrimalItemConsumable_Kibble_Base_XSmall",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette basique utilisée pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Base_XSmall.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Base_XSmall.PrimalItemConsumable_Kibble_Base_XSmall'",
    id: null
  },
  {
    nameFr: "Croquette Exceptionnelle",
    key: "PrimalItemConsumable_Kibble_Base_XLarge",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette exceptionnelle utilisée pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Base_XLarge.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Base_XLarge.PrimalItemConsumable_Kibble_Base_XLarge'",
    id: null
  },
  {
    nameFr: "Croquette Extraordinaire",
    key: "PrimalItemConsumable_Kibble_Base_Special",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette extraordinaire utilisée pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Base_Special.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Base_Special.PrimalItemConsumable_Kibble_Base_Special'",
    id: null
  },
  {
    nameFr: "Croquette Régulière",
    key: "PrimalItemConsumable_Kibble_Base_Medium",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette régulière utilisée pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Base_Medium.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Base_Medium.PrimalItemConsumable_Kibble_Base_Medium'",
    id: null
  },
  {
    nameFr: "Croquette Simple",
    key: "PrimalItemConsumable_Kibble_Base_Small",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette simple utilisée pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Base_Small.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Base_Small.PrimalItemConsumable_Kibble_Base_Small'",
    id: null
  },
  {
    nameFr: "Croquette Supérieure",
    key: "PrimalItemConsumable_Kibble_Base_Large",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette supérieure utilisée pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Base_Large.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Base_Large.PrimalItemConsumable_Kibble_Base_Large'",
    id: null
  },
  {
    nameFr: "Croquette augmentée basique",
    key: "PrimalItemConsumable_Kibble_Base_XSmall_EX_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette augmentée basique utilisée pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Base_XSmall_EX_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Base_XSmall_EX.PrimalItemConsumable_Kibble_Base_XSmall_EX'",
    id: null
  },
  {
    nameFr: "Croquette augmentée exceptionnelle",
    key: "PrimalItemConsumable_Kibble_Base_XLarge_EX_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette augmentée exceptionnelle utilisée pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Base_XLarge_EX_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Base_XLarge_EX.PrimalItemConsumable_Kibble_Base_XLarge_EX'",
    id: null
  },
  {
    nameFr: "Croquette augmentée extraordinaire",
    key: "PrimalItemConsumable_Kibble_Base_Special_EX_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette augmentée extraordinaire utilisée pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Base_Special_EX_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Base_Special_EX.PrimalItemConsumable_Kibble_Base_Special_EX'",
    id: null
  },
  {
    nameFr: "Croquette augmentée régulière",
    key: "PrimalItemConsumable_Kibble_Base_Medium_EX_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette augmentée régulière utilisée pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Base_Medium_EX_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Base_Medium_EX.PrimalItemConsumable_Kibble_Base_Medium_EX'",
    id: null
  },
  {
    nameFr: "Croquette augmentée simple",
    key: "PrimalItemConsumable_Kibble_Base_Small_EX_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette augmentée simple utilisée pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Base_Small_EX_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Base_Small_EX.PrimalItemConsumable_Kibble_Base_Small_EX'",
    id: null
  },
  {
    nameFr: "Croquette augmentée supérieure",
    key: "PrimalItemConsumable_Kibble_Base_Large_EX_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Croquette augmentée supérieure utilisée pour apprivoiser certaines créatures.",
    image: "assets/images/consommables/PrimalItemConsumable_Kibble_Base_Large_EX_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Base_Large_EX.PrimalItemConsumable_Kibble_Base_Large_EX'",
    id: null
  },
  {
    nameFr: "Cristal de Gacha",
    key: "PrimalItemConsumable_GachaPod_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Cristal mystérieux créé par les Gachas, contient des ressources aléatoires.",
    image: "assets/images/consommables/PrimalItemConsumable_GachaPod_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/Dinos/Gacha/PrimalItemConsumable_GachaPod.PrimalItemConsumable_GachaPod'",
    id: null
  },
  {
    nameFr: "Curry réchauffant",
    key: "PrimalItemConsumable_Soup_FriaCurry_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Un plat chaud et épicé qui aide à résister au froid.",
    image: "assets/images/consommables/PrimalItemConsumable_Soup_FriaCurry_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Soup_FriaCurry.PrimalItemConsumable_Soup_FriaCurry'",
    id: 226
  },
  {
    nameFr: "Côtelette d'agneau cuite",
    key: "PrimalItemConsumable_CookedLambChop_C",
    defaultValue: 30,
    category: "CONSUMABLE",
    description: "Une tranche de viande d'agneau cuite, restauratrice et savoureuse.",
    image: "assets/images/consommables/PrimalItemConsumable_CookedLambChop_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedLambChop.PrimalItemConsumable_CookedLambChop'",
    id: null
  },
  {
    nameFr: "Délicieux gâteau aux légumes",
    key: "PrimalItemConsumable_SweetVeggieCake_C",
    defaultValue: 10,
    category: "CONSUMABLE",
    description: "Un gâteau nutritif fait de légumes, idéal pour soigner les herbivores.",
    image: "assets/images/consommables/PrimalItemConsumable_SweetVeggieCake_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_SweetVeggieCake.PrimalItemConsumable_SweetVeggieCake'",
    id: null
  },
  {
    nameFr: "Emote « Démoniaque »",
    key: "PrimalItemConsumable_UnlockEmote_Evil_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Un consommable qui déverrouille l'emote démoniaque.",
    image: "assets/images/consommables/PrimalItemConsumable_UnlockEmote_Evil_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/BaseBPs/PrimalItemConsumable_UnlockEmote_Evil.PrimalItemConsumable_UnlockEmote_Evil'",
    id: null
  },
  {
    nameFr: "Extrait de cactus",
    key: "PrimalItemConsumable_CactusSap_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Un extrait riche en nutriments obtenu à partir de cactus.",
    image: "assets/images/consommables/PrimalItemConsumable_CactusSap_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/CoreBlueprints/Consumables/PrimalItemConsumable_CactusSap.PrimalItemConsumable_CactusSap'",
    id: null
  },
  {
    nameFr: "Exécuteur désassemblé",
    key: "PrimalItem_Spawner_Enforcer_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Une unité d'exécution désassemblée, peut être réassemblée pour obtenir un Exécuteur.",
    image: "assets/images/consommables/PrimalItem_Spawner_Enforcer_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/PrimalItem_Spawner_Enforcer.PrimalItem_Spawner_Enforcer'",
    id: null
  },
  {
    nameFr: "Glande de phéromone de Faucheur",
    key: "PrimalItemResource_XenomorphPheromoneGland_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Une glande contenant des phéromones de Faucheur, utile pour certaines interactions.",
    image: "assets/images/consommables/PrimalItemResource_XenomorphPheromoneGland_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_XenomorphPheromoneGland.PrimalItemResource_XenomorphPheromoneGland'",
    id: null
  },
  {
    nameFr: "Gourde en peau (Pleine)",
    key: "PrimalItemConsumable_WaterskinRefill_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Une gourde en peau remplie d'eau, utile pour rester hydraté.",
    image: "assets/images/consommables/PrimalItemConsumable_WaterskinRefill_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_WaterskinRefill.PrimalItemConsumable_WaterskinRefill'",
    id: 48
  },
  {
    nameFr: "Gourde en peau (Vide)",
    key: "PrimalItemConsumable_WaterskinCraftable_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Une gourde en peau vide, peut être remplie d'eau.",
    image: "assets/images/consommables/PrimalItemConsumable_WaterskinCraftable_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_WaterskinCraftable.PrimalItemConsumable_WaterskinCraftable'",
    id: 47
  },
  {
    nameFr: "Gourde en polymère (Pleine)",
    key: "PrimalItemConsumable_CanteenRefill_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Une gourde en polymère remplie d'eau, de meilleure qualité que la gourde en peau.",
    image: "assets/images/consommables/PrimalItemConsumable_CanteenRefill_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CanteenRefill.PrimalItemConsumable_CanteenRefill'",
    id: 375
  },
  {
    nameFr: "Gourde en polymère (Vide)",
    key: "PrimalItemConsumable_CanteenCraftable_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Une gourde en polymère vide, de meilleure qualité que la gourde en peau.",
    image: "assets/images/consommables/PrimalItemConsumable_CanteenCraftable_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CanteenCraftable.PrimalItemConsumable_CanteenCraftable'",
    id: 374
  },
  {
    nameFr: "Gourde glacée (Pleine)",
    key: "PrimalItemConsumable_IcedCanteenRefill_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Une gourde glacée remplie d'eau, procure une hydratation et un effet rafraîchissant.",
    image: "assets/images/consommables/PrimalItemConsumable_IcedCanteenRefill_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_IcedCanteenRefill.PrimalItemConsumable_IcedCanteenRefill'",
    id: null
  },
  {
    nameFr: "Gourde glacée (Vide)",
    key: "PrimalItemConsumable_IcedCanteen_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Une gourde glacée vide, peut être remplie d'eau et rafraîchie.",
    image: "assets/images/consommables/PrimalItemConsumable_IcedCanteen_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_IcedCanteen.PrimalItemConsumable_IcedCanteen'",
    id: null
  },
  {
    nameFr: "Jarre à eau glacé (Pleine)",
    key: "PrimalItemConsumable_IcedWaterJarRefill_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Une jarre à eau glacée remplie, procure une hydratation et un effet rafraîchissant.",
    image: "assets/images/consommables/PrimalItemConsumable_IcedWaterJarRefill_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_IcedWaterJarRefill.PrimalItemConsumable_IcedWaterJarRefill'",
    id: null
  },
  {
    nameFr: "Jarre à eau glacé (Vide)",
    key: "PrimalItemConsumable_IcedWaterJar_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Une jarre à eau glacée vide, peut être remplie d'eau et rafraîchie.",
    image: "assets/images/consommables/PrimalItemConsumable_IcedWaterJar_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_IcedWaterJar.PrimalItemConsumable_IcedWaterJar'",
    id: null
  },
  {
    nameFr: "Lait de Wyverne",
    key: "PrimalItemConsumable_WyvernMilk_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Lait obtenu à partir de Wyvernes, utilisé pour nourrir les jeunes Wyvernes.",
    image: "assets/images/consommables/PrimalItemConsumable_WyvernMilk_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/BaseBPs/PrimalItemConsumable_WyvernMilk.PrimalItemConsumable_WyvernMilk'",
    id: null
  },
  {
    nameFr: "Maïs",
    key: "PrimalItemConsumable_Veggie_Longrass_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Légume de base cultivé dans les champs, utilisé dans diverses recettes.",
    image: "assets/images/consommables/PrimalItemConsumable_Veggie_Longrass_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Veggie_Longrass.PrimalItemConsumable_Veggie_Longrass'",
    id: 229
  },
  {
    nameFr: "Mejoberry",
    key: "PrimalItemConsumable_Berry_Mejoberry_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Baie sucrée souvent utilisée pour apprivoiser les herbivores.",
    image: "assets/images/consommables/PrimalItemConsumable_Berry_Mejoberry_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Mejoberry.PrimalItemConsumable_Berry_Mejoberry'",
    id: 119
  },
  {
    nameFr: "Mek désassemblé",
    key: "PrimalItem_Spawner_Mek_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Unité Mek désassemblée, peut être réassemblée pour obtenir un Mek.",
    image: "assets/images/consommables/PrimalItem_Spawner_Mek_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/PrimalItem_Spawner_Mek.PrimalItem_Spawner_Mek'",
    id: null
  },
  {
    nameFr: "Miel d'abeille géante",
    key: "PrimalItemConsumable_Honey_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Miel riche en nutriments obtenu à partir de ruches d'abeilles géantes.",
    image: "assets/images/consommables/PrimalItemConsumable_Honey_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Honey.PrimalItemConsumable_Honey'",
    id: null
  },
  {
    nameFr: "Narcoberry",
    key: "PrimalItemConsumable_Berry_Narcoberry_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Baie toxique utilisée pour endormir les créatures ou fabriquer des narcotiques.",
    image: "assets/images/consommables/PrimalItemConsumable_Berry_Narcoberry_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Narcoberry.PrimalItemConsumable_Berry_Narcoberry'",
    id: 120
  },
  {
    nameFr: "Nasse pleine",
    key: "PrimalItem_FishBasketFilled_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Nasse remplie de poissons capturés.",
    image: "assets/images/consommables/PrimalItem_FishBasketFilled_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItem_FishBasketFilled.PrimalItem_FishBasketFilled'",
    id: null
  },
  {
    nameFr: "Pinte de Bière (alt)",
    key: "",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Une pinte de bière, alternative.",
    image: "assets/images/consommables/PrimalItemConsumable_BeerJarAlt.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_BeerJarAlt.PrimalItemConsumable_BeerJarAlt'",
    id: null
  },
  {
    nameFr: "Pinte de Bière",
    key: "PrimalItemConsumable_BeerJar_C",
    defaultValue: 20,
    category: "CONSUMABLE",
    description: "Une pinte de bière, rafraîchissante et enivrante.",
    image: "assets/images/consommables/PrimalItemConsumable_BeerJar_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_BeerJar.PrimalItemConsumable_BeerJar'",
    id: null
  },
  {
    nameFr: "Pomme de Terre",
    key: "PrimalItemConsumable_Veggie_Savoroot_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Légume de base cultivé dans les champs, utilisé dans diverses recettes.",
    image: "assets/images/consommables/PrimalItemConsumable_Veggie_Savoroot_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Veggie_Savoroot.PrimalItemConsumable_Veggie_Savoroot'",
    id: 228
  },
  {
    nameFr: "Ragoût d'énergie",
    key: "PrimalItemConsumable_Soup_EnduroStew_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Un ragoût nutritif qui augmente l'endurance et la régénération de santé.",
    image: "assets/images/consommables/PrimalItemConsumable_Soup_EnduroStew_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Soup_EnduroStew.PrimalItemConsumable_Soup_EnduroStew'",
    id: 223
  },
  {
    nameFr: "Répulsif à insectes",
    key: "PrimalItemConsumable_BugRepellant_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Répulsif utilisé pour éloigner les insectes hostiles.",
    image: "assets/images/consommables/PrimalItemConsumable_BugRepellant_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_BugRepellant.PrimalItemConsumable_BugRepellant'",
    id: null
  },
  {
    nameFr: "Savon",
    key: "PrimalItemConsumableSoap_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Savon utilisé pour effacer les peintures sur les structures ou les objets.",
    image: "assets/images/consommables/PrimalItemConsumableSoap_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/BaseBPs/PrimalItemConsumableSoap.PrimalItemConsumableSoap'",
    id: null
  },
  {
    nameFr: "Soupe au champignon",
    key: "PrimalItemConsumable_Soup_MushroomSoup_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Soupe riche en champignons, offre des bonus de santé.",
    image: "assets/images/consommables/PrimalItemConsumable_Soup_MushroomSoup_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Soup_MushroomSoup.PrimalItemConsumable_Soup_MushroomSoup'",
    id: null
  },
  {
    nameFr: "Soupe piquante",
    key: "PrimalItemConsumable_Soup_CalienSoup_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Une soupe épicée qui augmente la résistance à la chaleur.",
    image: "assets/images/consommables/PrimalItemConsumable_Soup_CalienSoup_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Soup_CalienSoup.PrimalItemConsumable_Soup_CalienSoup'",
    id: 225
  },
  {
    nameFr: "Steak de vision nocturne",
    key: "PrimalItemConsumable_Soup_ShadowSteak_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Un steak spécial qui améliore la vision nocturne et la précision.",
    image: "assets/images/consommables/PrimalItemConsumable_Soup_ShadowSteak_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Soup_ShadowSteak.PrimalItemConsumable_Soup_ShadowSteak'",
    id: 251
  },
  {
    nameFr: "Stimberry",
    key: "PrimalItemConsumable_Berry_Stimberry_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Baie stimulante utilisée pour régénérer l'endurance ou contrer la torpeur.",
    image: "assets/images/consommables/PrimalItemConsumable_Berry_Stimberry_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Stimberry.PrimalItemConsumable_Berry_Stimberry'",
    id: 121
  },
  {
    nameFr: "Tartare de Combat",
    key: "PrimalItemConsumable_Soup_BattleTartare_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Un plat riche en protéines qui augmente la force et la résistance.",
    image: "assets/images/consommables/PrimalItemConsumable_Soup_BattleTartare_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Soup_BattleTartare.PrimalItemConsumable_Soup_BattleTartare'",
    id: 250
  },
  {
    nameFr: "Tintoberry",
    key: "PrimalItemConsumable_Berry_Tintoberry_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Baie douce et juteuse, utilisée pour la nourriture et la teinture.",
    image: "assets/images/consommables/PrimalItemConsumable_Berry_Tintoberry_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Tintoberry.PrimalItemConsumable_Berry_Tintoberry'",
    id: 118
  },
  {
    nameFr: "Tonic d'amnésie totale",
    key: "PrimalItemConsumableRespecSoup_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Un breuvage spécial qui réinitialise toutes vos statistiques.",
    image: "assets/images/consommables/PrimalItemConsumableRespecSoup_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/BaseBPs/PrimalItemConsumableRespecSoup.PrimalItemConsumableRespecSoup'",
    id: 409
  },
  {
    nameFr: "Venin de Nameless",
    key: "PrimalItemConsumable_NamelessVenom_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Venin extrêmement toxique sécrété par les créatures Nameless.",
    image: "assets/images/consommables/PrimalItemConsumable_NamelessVenom_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Resources/PrimalItemConsumable_NamelessVenom.PrimalItemConsumable_NamelessVenom'",
    id: null
  },
  {
    nameFr: "Viande avariée",
    key: "PrimalItemConsumable_SpoiledMeat_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Viande gâtée, utilisée principalement pour fabriquer des narcotiques.",
    image: "assets/images/consommables/PrimalItemConsumable_SpoiledMeat_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_SpoiledMeat.PrimalItemConsumable_SpoiledMeat'",
    id: 13
  },
  {
    nameFr: "Viande crue",
    key: "PrimalItemConsumable_RawMeat_C",
    defaultValue: 40,
    category: "CONSUMABLE",
    description: "Viande crue, essentielle pour nourrir les carnivores et cuisiner.",
    image: "assets/images/consommables/PrimalItemConsumable_RawMeat_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_RawMeat.PrimalItemConsumable_RawMeat'",
    id: 12
  },
  {
    nameFr: "Viande cuite supérieure",
    key: "PrimalItemConsumable_CookedPrimeMeat_C",
    defaultValue: 30,
    category: "CONSUMABLE",
    description: "Viande cuite de qualité supérieure, nourrit mieux que la viande standard.",
    image: "assets/images/consommables/PrimalItemConsumable_CookedPrimeMeat_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedPrimeMeat.PrimalItemConsumable_CookedPrimeMeat'",
    id: 249
  },
  {
    nameFr: "Viande cuite séchée",
    key: "PrimalItemConsumable_CookedMeat_Jerky_C",
    defaultValue: 50,
    category: "CONSUMABLE",
    description: "Viande cuite conservée par séchage, se conserve plus longtemps.",
    image: "assets/images/consommables/PrimalItemConsumable_CookedMeat_Jerky_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedMeat_Jerky.PrimalItemConsumable_CookedMeat_Jerky'",
    id: 293
  },
  {
    nameFr: "Viande cuite",
    key: "PrimalItemConsumable_CookedMeat_C",
    defaultValue: 50,
    category: "CONSUMABLE",
    description: "Viande cuite standard, essentielle pour nourrir les carnivores.",
    image: "assets/images/consommables/PrimalItemConsumable_CookedMeat_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedMeat.PrimalItemConsumable_CookedMeat'",
    id: 14
  },
  {
    nameFr: "Viande de mouton",
    key: "PrimalItemConsumable_RawMutton_C",
    defaultValue: 100,
    category: "CONSUMABLE",
    description: "Viande crue de mouton, particulièrement nutritive pour les carnivores.",
    image: "assets/images/consommables/PrimalItemConsumable_RawMutton_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_RawMutton.PrimalItemConsumable_RawMutton'",
    id: null
  },
  {
    nameFr: "Viande supérieure crue",
    key: "PrimalItemConsumable_RawPrimeMeat_C",
    defaultValue: 1,
    category: "CONSUMABLE",
    description: "Viande crue de qualité supérieure, idéale pour nourrir les carnivores d'élite.",
    image: "assets/images/consommables/PrimalItemConsumable_RawPrimeMeat_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_RawPrimeMeat.PrimalItemConsumable_RawPrimeMeat'",
    id: 248
  },
  {
    nameFr: "Viande supérieure séchée",
    key: "PrimalItemConsumable_CookedPrimeMeat_Jerky_C",
    defaultValue: 30,
    category: "CONSUMABLE",
    description: "Viande cuite de qualité supérieure conservée par séchage.",
    image: "assets/images/consommables/PrimalItemConsumable_CookedPrimeMeat_Jerky_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedPrimeMeat_Jerky.PrimalItemConsumable_CookedPrimeMeat_Jerky'",
    id: 294
  }
];
