export const EGGS = [
  {
    nameFr: "Oeuf d'Allosaure",
    key: "PrimalItemConsumable_Egg_Allo_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Allosaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Allo_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Allo.PrimalItemConsumable_Egg_Allo'",
    id: null
  },
  {
    nameFr: "Oeuf d'Ankylosaure",
    key: "PrimalItemConsumable_Egg_Ankylo_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Ankylosaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Ankylo_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Ankylo.PrimalItemConsumable_Egg_Ankylo'",
    id: 341
  },
  {
    nameFr: "Oeuf d'Aranéo",
    key: "PrimalItemConsumable_Egg_Spider_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Aranéo.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Spider_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Spider.PrimalItemConsumable_Egg_Spider'",
    id: 349
  },
  {
    nameFr: "Oeuf d'Archaeopteryx",
    key: "PrimalItemConsumable_Egg_Archa_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Archaeopteryx.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Archa_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Archa.PrimalItemConsumable_Egg_Archa'",
    id: null
  },
  {
    nameFr: "Oeuf d'Argentavis",
    key: "PrimalItemConsumable_Egg_Argent_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Argentavis.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Argent_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Argent.PrimalItemConsumable_Egg_Argent'",
    id: 342
  },
  {
    nameFr: "Oeuf de Baryonyx",
    key: "PrimalItemConsumable_Egg_Baryonyx_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Baryonyx.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Baryonyx_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Baryonyx.PrimalItemConsumable_Egg_Baryonyx'",
    id: null
  },
  {
    nameFr: "Oeuf de Basilic",
    key: "PrimalItemConsumable_Egg_Basilisk_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Basilic.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Basilisk_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Egg_Basilisk.PrimalItemConsumable_Egg_Basilisk'",
    id: null
  },
  {
    nameFr: "Oeuf de Wyverne de Sang",
    key: "PrimalItemConsumable_Egg_CrystalWyvern_Fertilized_Bloodfall_C",
    defaultValue: 1,
    category: "Oeufs",
    description: "Oeuf fertilisé de Wyverne de Sang.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_CrystalWyvern_Fertilized_Bloodfall_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Dinos/CrystalWyvern/Eggs/PrimalItemConsumable_Egg_CrystalWyvern_Fertilized_Bloodfall.PrimalItemConsumable_Egg_CrystalWyvern_Fertilized_Bloodfall'",
    id: null
  },
  {
    nameFr: "Oeuf de Bloodstalker",
    key: "PrimalItemConsumable_Egg_BogSpider_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Bloodstalker.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_BogSpider_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Genesis/Dinos/BogSpider/PrimalItemConsumable_Egg_BogSpider.PrimalItemConsumable_Egg_BogSpider'",
    id: null
  },
  {
    nameFr: "Oeuf de Brontosaure",
    key: "PrimalItemConsumable_Egg_Bronto_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Brontosaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Bronto_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Bronto.PrimalItemConsumable_Egg_Bronto'",
    id: 284
  },
  {
    nameFr: "Oeuf de Morellatops",
    key: "PrimalItemConsumable_Egg_Camelsaurus_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Morellatops.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Camelsaurus_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/Camelsaurus/PrimalItemConsumable_Egg_Camelsaurus.PrimalItemConsumable_Egg_Camelsaurus'",
    id: null
  },
  {
    nameFr: "Oeuf de Carnotaure",
    key: "PrimalItemConsumable_Egg_Carno_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Carnotaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Carno_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Carno.PrimalItemConsumable_Egg_Carno'",
    id: 344
  },
  {
    nameFr: "Oeuf de Compy",
    key: "PrimalItemConsumable_Egg_Compy_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Compy.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Compy_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Compy.PrimalItemConsumable_Egg_Compy'",
    id: null
  },
  {
    nameFr: "Oeuf de Wyverne de Cristal",
    key: "PrimalItemConsumable_Egg_CrystalWyvern_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par une Wyverne de Cristal.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_CrystalWyvern_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Dinos/CrystalWyvern/Eggs/PrimalItemConsumable_Egg_CrystalWyvern.PrimalItemConsumable_Egg_CrystalWyvern'",
    id: null
  },
  {
    nameFr: "Oeuf de Deinonychus",
    key: "PrimalItemConsumable_Egg_Deinonychus_Fertilized_C",
    defaultValue: 1,
    category: "Oeufs",
    description: "Oeuf fertilisé de Deinonychus.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Deinonychus_Fertilized_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Valguero/Dinos/Deinonychus/PrimalItemConsumable_Egg_Deinonychus_Fertilized.PrimalItemConsumable_Egg_Deinonychus_Fertilized'",
    id: null
  },
  {
    nameFr: "Oeuf de Dilophosaure",
    key: "PrimalItemConsumable_Egg_Dilo_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Dilophosaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Dilo_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Dilo.PrimalItemConsumable_Egg_Dilo'",
    id: 345
  },
  {
    nameFr: "Oeuf de Dimétrodon",
    key: "PrimalItemConsumable_Egg_Dimetrodon_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Dimétrodon.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Dimetrodon_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Dimetrodon.PrimalItemConsumable_Egg_Dimetrodon'",
    id: null
  },
  {
    nameFr: "Oeuf de Dimorphodon",
    key: "PrimalItemConsumable_Egg_Dimorph_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Dimorphodon.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Dimorph_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Dimorph.PrimalItemConsumable_Egg_Dimorph'",
    id: 420
  },
  {
    nameFr: "Oeuf de Diplodocus",
    key: "PrimalItemConsumable_Egg_Diplo_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Diplodocus.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Diplo_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Diplo.PrimalItemConsumable_Egg_Diplo'",
    id: null
  },
  {
    nameFr: "Oeuf de Dodo",
    key: "PrimalItemConsumable_Egg_Dodo_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Dodo.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Dodo_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Dodo.PrimalItemConsumable_Egg_Dodo'",
    id: 290
  },
  {
    nameFr: "Oeuf de Wyverne de Braise",
    key: "PrimalItemConsumable_Egg_CrystalWyvern_Fertilized_Ember_C",
    defaultValue: 1,
    category: "Oeufs",
    description: "Oeuf fertilisé de Wyverne de Braise.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_CrystalWyvern_Fertilized_Ember_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Dinos/CrystalWyvern/Eggs/PrimalItemConsumable_Egg_CrystalWyvern_Fertilized_Ember.PrimalItemConsumable_Egg_CrystalWyvern_Fertilized_Ember'",
    id: null
  },
  {
    nameFr: "Oeuf de Plumineux",
    key: "PrimalItemConsumable_Egg_LanternBird_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Plumineux.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_LanternBird_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Egg_LanternBird.PrimalItemConsumable_Egg_LanternBird'",
    id: null
  },
  {
    nameFr: "Oeuf de poisson",
    key: "PrimalItemConsumable_UnderwaterEgg_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un poisson.",
    image: "assets/images/oeufs/PrimalItemConsumable_UnderwaterEgg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_UnderwaterEgg.PrimalItemConsumable_UnderwaterEgg'",
    id: null
  },
  {
    nameFr: "Oeuf de Gallimimus",
    key: "PrimalItemConsumable_Egg_Galli_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Gallimimus.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Galli_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Galli.PrimalItemConsumable_Egg_Galli'",
    id: null
  },
  {
    nameFr: "Oeuf de Giganotosaure",
    key: "PrimalItemConsumable_Egg_Gigant_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Giganotosaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Gigant_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Gigant.PrimalItemConsumable_Egg_Gigant'",
    id: null
  },
  {
    nameFr: "Oeuf de Gecko luisant",
    key: "PrimalItemConsumable_Egg_LanternLizard_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Gecko luisant.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_LanternLizard_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Egg_LanternLizard.PrimalItemConsumable_Egg_LanternLizard'",
    id: null
  },
  {
    nameFr: "Oeuf d'Hesperornis en or",
    key: "PrimalItemConsumable_Egg_Hesperonis_Golden_C",
    defaultValue: 1,
    category: "Oeufs",
    description: "Oeuf en or pondu par un Hesperornis.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Hesperonis_Golden_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Hesperonis_Golden.PrimalItemConsumable_Egg_Hesperonis_Golden'",
    id: null
  },
  {
    nameFr: "Oeuf d'Hesperornis",
    key: "PrimalItemConsumable_Egg_Hesperonis_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Hesperornis.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Hesperonis_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Hesperonis.PrimalItemConsumable_Egg_Hesperonis'",
    id: null
  },
  {
    nameFr: "Oeuf d'Ichthyornis",
    key: "PrimalItemConsumable_Egg_Ichthyornis_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Ichthyornis.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Ichthyornis_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Ichthyornis.PrimalItemConsumable_Egg_Ichthyornis'",
    id: null
  },
  {
    nameFr: "Oeuf d'Iguanodon",
    key: "PrimalItemConsumable_Egg_Iguanodon_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Iguanodon.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Iguanodon_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Iguanodon.PrimalItemConsumable_Egg_Iguanodon'",
    id: null
  },
  {
    nameFr: "Oeuf de Kairuku",
    key: "PrimalItemConsumable_Egg_Kairuku_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Kairuku.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Kairuku_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Kairuku.PrimalItemConsumable_Egg_Kairuku'",
    id: null
  },
  {
    nameFr: "Oeuf de Kaprosuchus",
    key: "PrimalItemConsumable_Egg_Kaprosuchus_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Kaprosuchus.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Kaprosuchus_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Kaprosuchus.PrimalItemConsumable_Egg_Kaprosuchus'",
    id: null
  },
  {
    nameFr: "Oeuf de Kentrosaure",
    key: "PrimalItemConsumable_Egg_Kentro_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Kentrosaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Kentro_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Kentro.PrimalItemConsumable_Egg_Kentro'",
    id: null
  },
  {
    nameFr: "Oeuf de Lystrosaure",
    key: "PrimalItemConsumable_Egg_Lystro_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Lystrosaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Lystro_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Lystro.PrimalItemConsumable_Egg_Lystro'",
    id: null
  },
  {
    nameFr: "Oeuf de Magmasaure",
    key: "PrimalItemConsumable_Egg_Cherufe_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Magmasaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Cherufe_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Genesis/Dinos/Cherufe/PrimalItemConsumable_Egg_Cherufe.PrimalItemConsumable_Egg_Cherufe'",
    id: null
  },
  {
    nameFr: "Oeuf de Mantis",
    key: "PrimalItemConsumable_Egg_Mantis_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par une Mantis.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Mantis_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/Mantis/PrimalItemConsumable_Egg_Mantis.PrimalItemConsumable_Egg_Mantis'",
    id: null
  },
  {
    nameFr: "Oeuf de Mégachelon",
    key: "PrimalItemConsumable_Egg_GiantTurtle_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Mégachelon.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_GiantTurtle_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Genesis/Dinos/GiantTurtle/PrimalItemConsumable_Egg_GiantTurtle.PrimalItemConsumable_Egg_GiantTurtle'",
    id: null
  },
  {
    nameFr: "Oeuf de Megalania",
    key: "PrimalItemConsumable_Egg_Megalania_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Megalania.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Megalania_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Megalania.PrimalItemConsumable_Egg_Megalania'",
    id: null
  },
  {
    nameFr: "Oeuf de Mégalosaure",
    key: "PrimalItemConsumable_Egg_Megalosaurus_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Mégalosaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Megalosaurus_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Megalosaurus.PrimalItemConsumable_Egg_Megalosaurus'",
    id: null
  },
  {
    nameFr: "Oeuf de Microraptor",
    key: "PrimalItemConsumable_Egg_MicroRaptor_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Microraptor.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_MicroRaptor_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_MicroRaptor.PrimalItemConsumable_Egg_MicroRaptor'",
    id: null
  },
  {
    nameFr: "Oeuf de Moschops",
    key: "PrimalItemConsumable_Egg_Moschops_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Moschops.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Moschops_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Moschops.PrimalItemConsumable_Egg_Moschops'",
    id: null
  },
  {
    nameFr: "Oeuf de Papillon géant",
    key: "PrimalItemConsumable_Egg_Moth_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Papillon géant.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Moth_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/Moth/PrimalItemConsumable_Egg_Moth.PrimalItemConsumable_Egg_Moth'",
    id: null
  },
  {
    nameFr: "Oeuf d'Oviraptor",
    key: "PrimalItemConsumable_Egg_Oviraptor_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Oviraptor.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Oviraptor_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Oviraptor.PrimalItemConsumable_Egg_Oviraptor'",
    id: null
  },
  {
    nameFr: "Oeuf de Pachycéphalosaure",
    key: "PrimalItemConsumable_Egg_Pachy_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Pachycéphalosaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Pachy_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Pachy.PrimalItemConsumable_Egg_Pachy'",
    id: 413
  },
  {
    nameFr: "Oeuf de Pachyrhinosaure",
    key: "PrimalItemConsumable_Egg_Pachyrhino_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Pachyrhinosaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Pachyrhino_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Pachyrhino.PrimalItemConsumable_Egg_Pachyrhino'",
    id: null
  },
  {
    nameFr: "Oeuf de Parasaure",
    key: "PrimalItemConsumable_Egg_Para_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Parasaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Para_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Para.PrimalItemConsumable_Egg_Para'",
    id: 285
  },
  {
    nameFr: "Oeuf de Pegomastax",
    key: "PrimalItemConsumable_Egg_Pegomastax_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Pegomastax.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Pegomastax_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Pegomastax.PrimalItemConsumable_Egg_Pegomastax'",
    id: null
  },
  {
    nameFr: "Oeuf de Pelagornis",
    key: "PrimalItemConsumable_Egg_Pela_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Pelagornis.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Pela_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Pela.PrimalItemConsumable_Egg_Pela'",
    id: null
  },
  {
    nameFr: "Oeuf de Ptéranodon",
    key: "PrimalItemConsumable_Egg_Ptero_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Ptéranodon.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Ptero_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Ptero.PrimalItemConsumable_Egg_Ptero'",
    id: 346
  },
  {
    nameFr: "Oeuf de Pulmonoscorpius",
    key: "PrimalItemConsumable_Egg_Scorpion_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Pulmonoscorpius.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Scorpion_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Scorpion.PrimalItemConsumable_Egg_Scorpion'",
    id: 348
  },
  {
    nameFr: "Oeuf de Quetzal",
    key: "PrimalItemConsumable_Egg_Quetz_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Quetzal.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Quetz_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Quetz.PrimalItemConsumable_Egg_Quetz'",
    id: null
  },
  {
    nameFr: "Oeuf de Raptor",
    key: "PrimalItemConsumable_Egg_Raptor_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Raptor.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Raptor_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Raptor.PrimalItemConsumable_Egg_Raptor'",
    id: 286
  },
  {
    nameFr: "Oeuf de T-Rex",
    key: "PrimalItemConsumable_Egg_Rex_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un T-Rex.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Rex_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Rex.PrimalItemConsumable_Egg_Rex'",
    id: 287
  },
  {
    nameFr: "Oeuf de Dragon Rocheux",
    key: "PrimalItemConsumable_Egg_RockDrake_Fertilized_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf fertilisé de Dragon Rocheux.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_RockDrake_Fertilized_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/Dinos/RockDrake/PrimalItemConsumable_Egg_RockDrake_Fertilized.PrimalItemConsumable_Egg_RockDrake_Fertilized'",
    id: null
  },
  {
    nameFr: "Oeuf de Sarcosuchus",
    key: "PrimalItemConsumable_Egg_Sarco_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Sarcosuchus.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Sarco_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Sarco.PrimalItemConsumable_Egg_Sarco'",
    id: 347
  },
  {
    nameFr: "Oeuf de Harfang des neiges",
    key: "PrimalItemConsumable_Egg_Owl_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Harfang des neiges.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Owl_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/Dinos/Owl/PrimalItemConsumable_Egg_Owl.PrimalItemConsumable_Egg_Owl'",
    id: null
  },
  {
    nameFr: "Oeuf de Spinosaure",
    key: "PrimalItemConsumable_Egg_Spino_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Spinosaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Spino_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Spino.PrimalItemConsumable_Egg_Spino'",
    id: 350
  },
  {
    nameFr: "Oeuf de Stégosaure",
    key: "PrimalItemConsumable_Egg_Stego_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Stégosaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Stego_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Stego.PrimalItemConsumable_Egg_Stego'",
    id: 56
  },
  {
    nameFr: "Oeuf de Tapejara",
    key: "PrimalItemConsumable_Egg_Tapejara_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Tapejara.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Tapejara_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Tapejara.PrimalItemConsumable_Egg_Tapejara'",
    id: null
  },
  {
    nameFr: "Oeuf de Parasaure Tek",
    key: "PrimalItemConsumable_Egg_Para_Bionic_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Parasaure Tek.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Para_Bionic_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Para_Bionic.PrimalItemConsumable_Egg_Para_Bionic'",
    id: null
  },
  {
    nameFr: "Oeuf de Quetzal Tek",
    key: "PrimalItemConsumable_Egg_Quetz_Bionic_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Quetzal Tek.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Quetz_Bionic_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Quetz_Bionic.PrimalItemConsumable_Egg_Quetz_Bionic'",
    id: null
  },
  {
    nameFr: "Oeuf de Raptor Tek",
    key: "PrimalItemConsumable_Egg_Raptor_Bionic_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Raptor Tek.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Raptor_Bionic_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Raptor_Bionic.PrimalItemConsumable_Egg_Raptor_Bionic'",
    id: null
  },
  {
    nameFr: "Oeuf de T-Rex Tek",
    key: "PrimalItemConsumable_Egg_Rex_Bionic_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un T-Rex Tek.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Rex_Bionic_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Rex_Bionic.PrimalItemConsumable_Egg_Rex_Bionic'",
    id: null
  },
  {
    nameFr: "Oeuf de Stégosaure Tek",
    key: "PrimalItemConsumable_Egg_Stego_Bionic_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Stégosaure Tek.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Stego_Bionic_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Stego_Bionic.PrimalItemConsumable_Egg_Stego_Bionic'",
    id: null
  },
  {
    nameFr: "Oeuf de Tricératops Tek",
    key: "PrimalItemConsumable_Egg_Trike_Bionic_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Tricératops Tek.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Trike_Bionic_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Trike_Bionic.PrimalItemConsumable_Egg_Trike_Bionic'",
    id: null
  },
  {
    nameFr: "Oeuf d'Oiseau-Terreur",
    key: "PrimalItemConsumable_Egg_Terrorbird_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Oiseau-Terreur.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Terrorbird_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_TerrorBird.PrimalItemConsumable_Egg_Terrorbird'",
    id: null
  },
  {
    nameFr: "Oeuf de Thérizinosaure",
    key: "PrimalItemConsumable_Egg_Therizino_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Thérizinosaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Therizino_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Therizino.PrimalItemConsumable_Egg_Therizino'",
    id: null
  },
  {
    nameFr: "Oeuf de Lézard épineux",
    key: "PrimalItemConsumable_Egg_SpineyLizard_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Lézard épineux.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_SpineyLizard_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/SpineyLizard/PrimalItemConsumable_Egg_SpineyLizard.PrimalItemConsumable_Egg_SpineyLizard'",
    id: null
  },
  {
    nameFr: "Oeuf de Titanoboa",
    key: "PrimalItemConsumable_Egg_Boa_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Titanoboa.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Boa_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Boa.PrimalItemConsumable_Egg_Boa'",
    id: 343
  },
  {
    nameFr: "Oeuf de Tricératops",
    key: "PrimalItemConsumable_Egg_Trike_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Tricératops.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Trike_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Trike.PrimalItemConsumable_Egg_Trike'",
    id: 288
  },
  {
    nameFr: "Oeuf de Troodon",
    key: "PrimalItemConsumable_Egg_Troodon_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Troodon.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Troodon_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Troodon.PrimalItemConsumable_Egg_Troodon'",
    id: null
  },
  {
    nameFr: "Oeuf de Wyverne Tropicale",
    key: "PrimalItemConsumable_Egg_CrystalWyvern_Fertilized_WS_C",
    defaultValue: 1,
    category: "Oeufs",
    description: "Oeuf fertilisé de Wyverne Tropicale.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_CrystalWyvern_Fertilized_WS_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Dinos/CrystalWyvern/Eggs/PrimalItemConsumable_Egg_CrystalWyvern_Fertilized_WS.PrimalItemConsumable_Egg_CrystalWyvern_Fertilized_WS'",
    id: null
  },
  {
    nameFr: "Oeuf de Tropeognathus",
    key: "PrimalItemConsumable_Egg_Tropeognathus_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Tropeognathus.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Tropeognathus_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Tropeognathus.PrimalItemConsumable_Egg_Tropeognathus'",
    id: null
  },
  {
    nameFr: "Oeuf de Carbonemys",
    key: "PrimalItemConsumable_Egg_Turtle_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Carbonemys.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Turtle_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Turtle.PrimalItemConsumable_Egg_Turtle'",
    id: 351
  },
  {
    nameFr: "Oeuf de Vélonasaure",
    key: "PrimalItemConsumable_Egg_Spindles_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Vélonasaure.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Spindles_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/Dinos/Spindles/PrimalItemConsumable_Egg_Spindles.PrimalItemConsumable_Egg_Spindles'",
    id: null
  },
  {
    nameFr: "Oeuf de Vautour",
    key: "PrimalItemConsumable_Egg_Vulture_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Vautour.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Vulture_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/Vulture/PrimalItemConsumable_Egg_Vulture.PrimalItemConsumable_Egg_Vulture'",
    id: null
  },
  {
    nameFr: "Oeuf de Wyverne (Feu)",
    key: "PrimalItemConsumable_Egg_Wyvern_Fertilized_Fire_C",
    defaultValue: 1,
    category: "Oeufs",
    description: "Oeuf fertilisé de Wyverne de Feu.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Wyvern_Fertilized_Fire_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Wyvern_Fertilized_Fire.PrimalItemConsumable_Egg_Wyvern_Fertilized_Fire'",
    id: null
  },
  {
    nameFr: "Oeuf de Wyverne (Foudre)",
    key: "PrimalItemConsumable_Egg_Wyvern_Fertilized_Lightning_C",
    defaultValue: 1,
    category: "Oeufs",
    description: "Oeuf fertilisé de Wyverne de Foudre.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Wyvern_Fertilized_Lightning_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Wyvern_Fertilized_Lightning.PrimalItemConsumable_Egg_Wyvern_Fertilized_Lightning'",
    id: null
  },
  {
    nameFr: "Oeuf de Wyverne (Poison)",
    key: "PrimalItemConsumable_Egg_Wyvern_Fertilized_Poison_C",
    defaultValue: 1,
    category: "Oeufs",
    description: "Oeuf fertilisé de Wyverne de Poison.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Wyvern_Fertilized_Poison_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Wyvern_Fertilized_Poison.PrimalItemConsumable_Egg_Wyvern_Fertilized_Poison'",
    id: null
  },
  {
    nameFr: "Oeuf de Yutyrannus",
    key: "PrimalItemConsumable_Egg_Yuty_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Oeuf pondu par un Yutyrannus.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Yuty_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Egg_Yuty.PrimalItemConsumable_Egg_Yuty'",
    id: null
  },
  {
    nameFr: "Oeuf",
    key: "PrimalItemConsumable_Egg_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Un oeuf générique.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Egg.PrimalItemConsumable_Egg'",
    id: null
  },
  {
    nameFr: "Oeuf Gros",
    key: "PrimalItemConsumable_Egg_Large_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Un gros oeuf.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Large_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Egg_Large.PrimalItemConsumable_Egg_Large'",
    id: null
  },
  {
    nameFr: "Oeuf Moyen",
    key: "PrimalItemConsumable_Egg_Medium_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Un oeuf de taille moyenne.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Medium_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Egg_Medium.PrimalItemConsumable_Egg_Medium'",
    id: null
  },
  {
    nameFr: "Oeuf Petit",
    key: "PrimalItemConsumable_Egg_Small_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Un petit oeuf.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Small_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Egg_Small.PrimalItemConsumable_Egg_Small'",
    id: null
  },
  {
    nameFr: "Oeuf Spécial",
    key: "PrimalItemConsumable_Egg_Special_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Un oeuf spécial.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_Special_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Egg_Special.PrimalItemConsumable_Egg_Special'",
    id: null
  },
  {
    nameFr: "Oeuf Extra Gros",
    key: "PrimalItemConsumable_Egg_XtraLarge_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Un oeuf extra gros.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_XtraLarge_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Egg_XtraLarge.PrimalItemConsumable_Egg_XtraLarge'",
    id: null
  },
  {
    nameFr: "Oeuf Extra Petit",
    key: "PrimalItemConsumable_Egg_XSmall_C",
    defaultValue: 100,
    category: "Oeufs",
    description: "Un oeuf extra petit.",
    image: "assets/images/oeufs/PrimalItemConsumable_Egg_XSmall_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Egg_XSmall.PrimalItemConsumable_Egg_XSmall'",
    id: null
  }
];
