export const HARVEST_RESOURCE = [
  {
    nameFr: "Bois",
    key: "PrimalItemResource_Wood_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisé pour construire divers objets et structures. Ex : murs, meubles.",
    image: "assets/images/resources/PrimalItemResource_Wood_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Wood.PrimalItemResource_Wood'",
    id: 7
  },
  {
    nameFr: "Pierre",
    key: "PrimalItemResource_Stone_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisée pour créer des outils et des structures. Ex : murs, fondations.",
    image: "assets/images/resources/PrimalItemResource_Stone_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Stone.PrimalItemResource_Stone'",
    id: 8
  },
  {
    nameFr: "Métal",
    key: "PrimalItemResource_Metal_C",
    defaultValue: 200,
    category: "RESOURCE",
    description: "Métal utilisé pour fabriquer des outils et des structures avancées.",
    image: "assets/images/resources/PrimalItemResource_Metal_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Metal.PrimalItemResource_Metal'",
    id: 9
  },
  {
    nameFr: "Peau",
    key: "PrimalItemResource_Hide_C",
    defaultValue: 200,
    category: "RESOURCE",
    description: "Utilisé pour fabriquer des vêtements et des équipements.",
    image: "assets/images/resources/PrimalItemResource_Hide_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Hide.PrimalItemResource_Hide'",
    id: 10
  },
  {
    nameFr: "Chitine",
    key: "PrimalItemResource_Chitin_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Matériau dur utilisé pour des armures et des objets spécifiques.",
    image: "assets/images/resources/PrimalItemResource_Chitin_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Chitin.PrimalItemResource_Chitin'",
    id: 11
  },
  {
    nameFr: "Poche de sang",
    key: "PrimalItemConsumable_BloodPack_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisée comme source de régénération pour la santé.",
    image: "assets/images/resources/PrimalItemConsumable_BloodPack_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_BloodPack.PrimalItemConsumable_BloodPack'",
    id: 45
  },
  {
    nameFr: "Engrais",
    key: "PrimalItemConsumable_Fertilizer_Compost_C",
    defaultValue: 1,
    category: "RESOURCE",
    description: "Utilisé pour fertiliser les cultures et améliorer la croissance des plantes.",
    image: "assets/images/resources/PrimalItemConsumable_Fertilizer_Compost_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Fertilizer_Compost.PrimalItemConsumable_Fertilizer_Compost'",
    id: 50
  },
  {
    nameFr: "Silex",
    key: "PrimalItemResource_Flint_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisé principalement pour la fabrication d'outils et d'armes en pierre.",
    image: "assets/images/resources/PrimalItemResource_Flint_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Flint.PrimalItemResource_Flint'",
    id: 72
  },
  {
    nameFr: "Lingot de métal",
    key: "PrimalItemResource_MetalIngot_C",
    defaultValue: 200,
    category: "RESOURCE",
    description: "Métal raffiné utilisé pour créer des outils, des armes et des structures.",
    image: "assets/images/resources/PrimalItemResource_MetalIngot_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_MetalIngot.PrimalItemResource_MetalIngot'",
    id: 73
  },
  {
    nameFr: "Branchages",
    key: "PrimalItemResource_Thatch_C",
    defaultValue: 200,
    category: "RESOURCE",
    description: "Utilisés principalement pour la construction de structures légères.",
    image: "assets/images/resources/PrimalItemResource_Thatch_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Thatch.PrimalItemResource_Thatch'",
    id: 74
  },
  {
    nameFr: "Fibres",
    key: "PrimalItemResource_Fibers_C",
    defaultValue: 300,
    category: "RESOURCE",
    description: "Utilisées pour fabriquer divers objets et équipements.",
    image: "assets/images/resources/PrimalItemResource_Fibers_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Fibers.PrimalItemResource_Fibers'",
    id: 75
  },
  {
    nameFr: "Charbon",
    key: "PrimalItemResource_Charcoal_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisé comme combustible et pour fabriquer des poudres.",
    image: "assets/images/resources/PrimalItemResource_Charcoal_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Charcoal.PrimalItemResource_Charcoal'",
    id: 76
  },
  {
    nameFr: "Cristal",
    key: "PrimalItemResource_Crystal_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Ressource précieuse utilisée pour fabriquer des objets spéciaux et des équipements.",
    image: "assets/images/resources/PrimalItemResource_Crystal_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Crystal.PrimalItemResource_Crystal'",
    id: 77
  },
  {
    nameFr: "Poudre-étincelle",
    key: "PrimalItemResource_Sparkpowder_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisée comme composant pour les explosifs et les torches.",
    image: "assets/images/resources/PrimalItemResource_Sparkpowder_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Sparkpowder.PrimalItemResource_Sparkpowder'",
    id: 107
  },
  {
    nameFr: "Poudre à Canon",
    key: "PrimalItemResource_Gunpowder_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisée pour fabriquer des munitions et des explosifs.",
    image: "assets/images/resources/PrimalItemResource_Gunpowder_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Gunpowder.PrimalItemResource_Gunpowder'",
    id: 108
  },
  {
    nameFr: "Narcotique",
    key: "PrimalItemConsumable_Narcotic_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisé pour endormir les créatures.",
    image: "assets/images/resources/PrimalItemConsumable_Narcotic_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Narcotic.PrimalItemConsumable_Narcotic'",
    id: 122
  },
  {
    nameFr: "Stimulant",
    key: "PrimalItemConsumable_Stimulant_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisé pour augmenter temporairement l'énergie.",
    image: "assets/images/resources/PrimalItemConsumable_Stimulant_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Stimulant.PrimalItemConsumable_Stimulant'",
    id: 123
  },
  {
    nameFr: "Obsidienne",
    key: "PrimalItemResource_Obsidian_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Ressource rare utilisée pour fabriquer des outils tranchants.",
    image: "assets/images/resources/PrimalItemResource_Obsidian_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Obsidian.PrimalItemResource_Obsidian'",
    id: 141
  },
  {
    nameFr: "Ciment",
    key: "PrimalItemResource_ChitinPaste_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisé pour fabriquer des matériaux de construction.",
    image: "assets/images/resources/PrimalItemResource_ChitinPaste_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ChitinPaste.PrimalItemResource_ChitinPaste'",
    id: 144
  },
  {
    nameFr: "Pétrole",
    key: "PrimalItemResource_Oil_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisé comme combustible pour diverses machines et équipements.",
    image: "assets/images/resources/PrimalItemResource_Oil_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Oil.PrimalItemResource_Oil'",
    id: 159
  },
  {
    nameFr: "Perles de Silice",
    key: "PrimalItemResource_Silicon_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisées pour fabriquer des composants électroniques.",
    image: "assets/images/resources/PrimalItemResource_Silicon_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Silicon.PrimalItemResource_Silicon'",
    id: 160
  },
  {
    nameFr: "Essence",
    key: "PrimalItemResource_Gasoline_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisée comme carburant pour divers véhicules et machines.",
    image: "assets/images/resources/PrimalItemResource_Gasoline_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Gasoline.PrimalItemResource_Gasoline'",
    id: 161
  },
  {
    nameFr: "Électroniques",
    key: "PrimalItemResource_Electronics_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisées pour fabriquer des appareils électroniques et des gadgets.",
    image: "assets/images/resources/PrimalItemResource_Electronics_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Electronics.PrimalItemResource_Electronics'",
    id: 162
  },
  {
    nameFr: "Polymère",
    key: "PrimalItemResource_Polymer_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisé pour fabriquer divers objets avancés et armures.",
    image: "assets/images/resources/PrimalItemResource_Polymer_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Polymer.PrimalItemResource_Polymer'",
    id: 163
  },
  {
    nameFr: "Chitine ou Kératine",
    key: "PrimalItemResource_ChitinOrKeratin_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Ressource utilisée pour fabriquer des armures et des objets spécifiques.",
    image: "assets/images/resources/PrimalItemResource_ChitinOrKeratin_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ChitinOrKeratin.PrimalItemResource_ChitinOrKeratin'",
    id: 212
  },
  {
    nameFr: "Kératine",
    key: "PrimalItemResource_Keratin_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisé pour fabriquer des armures et des objets spécifiques.",
    image: "assets/images/resources/PrimalItemResource_Keratin_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Keratin.PrimalItemResource_Keratin'",
    id: 213
  },
  {
    nameFr: "Fleur rare",
    key: "PrimalItemResource_RareFlower_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisée pour créer des potions et divers objets rares.",
    image: "assets/images/resources/PrimalItemResource_RareFlower_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_RareFlower.PrimalItemResource_RareFlower'",
    id: 246
  },
  {
    nameFr: "Champignon Rare",
    key: "PrimalItemResource_RareMushroom_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisé pour la fabrication de potions et de divers objets rares.",
    image: "assets/images/resources/PrimalItemResource_RareMushroom_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_RareMushroom.PrimalItemResource_RareMushroom'",
    id: 247
  },
  {
    nameFr: "Super fertilisant",
    key: "PrimalItemConsumableMiracleGro_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisé pour booster la croissance des cultures de manière significative.",
    image: "assets/images/resources/PrimalItemConsumableMiracleGro_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/BaseBPs/PrimalItemConsumableMiracleGro.PrimalItemConsumableMiracleGro'",
    id: 382
  },
  {
    nameFr: "Fourrure",
    key: "PrimalItemResource_Pelt_C",
    defaultValue: 200,
    category: "RESOURCE",
    description: "Utilisée pour fabriquer des vêtements et des équipements en fourrure.",
    image: "assets/images/resources/PrimalItemResource_Pelt_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Pelt.PrimalItemResource_Pelt'",
    id: 419
  },
  {
    nameFr: "Ambre gris",
    key: "PrimalItemResource_Ambergris_C",
    defaultValue: 1,
    category: "RESOURCE",
    description: "Ressource rare provenant des baleines spatiales. Utilisée dans divers crafts avancés.",
    image: "assets/images/resources/PrimalItemResource_Ambergris_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/Dinos/SpaceWhale/PrimalItemResource_Ambergris.PrimalItemResource_Ambergris'",
    id: null
  },
  {
    nameFr: "Argile",
    key: "PrimalItemResource_Clay_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Ressource utilisée principalement pour fabriquer de la poterie et divers objets de construction.",
    image: "assets/images/resources/PrimalItemResource_Clay_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_Clay.PrimalItemResource_Clay'",
    id: null
  },
  {
    nameFr: "Batterie",
    key: "PrimalItem_ChargeBattery_C",
    defaultValue: 1,
    category: "RESOURCE",
    description: "Utilisée pour stocker de l'énergie et alimenter divers équipements électriques.",
    image: "assets/images/resources/PrimalItem_ChargeBattery_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/WeaponGlowStickCharge/PrimalItem_ChargeBattery.PrimalItem_ChargeBattery'",
    id: null
  },
  {
    nameFr: "Bave d'Achatina",
    key: "PrimalItemResource_SnailPaste_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisée pour créer des potions et des crafts spécifiques, obtenue à partir des Achatinas.",
    image: "assets/images/resources/PrimalItemResource_SnailPaste_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Dinos/Achatina/PrimalItemResource_SnailPaste.PrimalItemResource_SnailPaste'",
    id: null
  },
  {
    nameFr: "Bile d'Ammonite",
    key: "PrimalItemResource_AmmoniteBlood_C",
    defaultValue: 50,
    category: "RESOURCE",
    description: "Ressource obtenue à partir des Ammonites, utilisée dans divers crafts et potions.",
    image: "assets/images/resources/PrimalItemResource_AmmoniteBlood_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_AmmoniteBlood.PrimalItemResource_AmmoniteBlood'",
    id: null
  },
  {
    nameFr: "Bois corrompu",
    key: "PrimalItemResource_CorruptedWood_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Bois infecté, utilisé pour la fabrication de divers objets corrompus.",
    image: "assets/images/resources/PrimalItemResource_CorruptedWood_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_CorruptedWood.PrimalItemResource_CorruptedWood'",
    id: null
  },
  {
    nameFr: "Bois fongique",
    key: "PrimalItemResource_FungalWood_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Bois provenant des environnements fongiques, utilisé pour divers crafts sur Aberration.",
    image: "assets/images/resources/PrimalItemResource_FungalWood_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_FungalWood.PrimalItemResource_FungalWood'",
    id: null
  },
  {
    nameFr: "Carburant",
    key: "PrimalItemResource_Propellant_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisé comme carburant pour diverses machines et objets.",
    image: "assets/images/resources/PrimalItemResource_Propellant_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_Propellant.PrimalItemResource_Propellant'",
    id: null
  },
  {
    nameFr: "Cheveux humains",
    key: "PrimalItemResource_Hair_C",
    defaultValue: 200,
    category: "RESOURCE",
    description: "Utilisés pour créer des vêtements et des équipements en cheveux humains.",
    image: "assets/images/resources/PrimalItemResource_Hair_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Hair.PrimalItemResource_Hair'",
    id: null
  },
  {
    nameFr: "Corne de Rhinocéros laineux",
    key: "PrimalItemResource_Horn_C",
    defaultValue: 20,
    category: "RESOURCE",
    description: "Utilisée pour fabriquer des objets et des équipements spécifiques.",
    image: "assets/images/resources/PrimalItemResource_Horn_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Horn.PrimalItemResource_Horn'",
    id: null
  },
  {
    nameFr: "Corne de Ver des sables",
    key: "PrimalItemResource_KeratinSpike_C",
    defaultValue: 20,
    category: "RESOURCE",
    description: "Utilisée pour fabriquer des objets spécifiques à partir des vers des sables.",
    image: "assets/images/resources/PrimalItemResource_KeratinSpike_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/Deathworm/PrimalItemResource_KeratinSpike.PrimalItemResource_KeratinSpike'",
    id: null
  },
  {
    nameFr: "Corne de Ver des sables ou Corne de Rhinocéros laineux",
    key: "PrimalItemResource_ChitinOrKeratin_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Ressource interchangeable pour les crafts nécessitant des cornes ou de la chitine.",
    image: "assets/images/resources/PrimalItemResource_ChitinOrKeratin_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ChitinOrKeratin.PrimalItemResource_ChitinOrKeratin'",
    id: null
  },
  {
    nameFr: "Derme",
    key: "PrimalItem_TaxidermyDermis_C",
    defaultValue: 1,
    category: "RESOURCE",
    description: "Utilisé pour la taxidermie, ce matériau est obtenu en conservant la peau d'animaux.",
    image: "assets/images/resources/PrimalItem_TaxidermyDermis_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/PrimalItem_TaxidermyDermis.PrimalItem_TaxidermyDermis'",
    id: null
  },
  {
    nameFr: "Ferraille",
    key: "PrimalItemResource_ScrapMetal_C",
    defaultValue: 200,
    category: "RESOURCE",
    description: "Métal récupéré à partir de ferraille, utilisé pour créer divers objets et équipements.",
    image: "assets/images/resources/PrimalItemResource_ScrapMetal_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_ScrapMetal.PrimalItemResource_ScrapMetal'",
    id: null
  },
  {
    nameFr: "Fourrure, Cheveux humains ou Laine",
    key: "PrimalItemResource_PeltOrHair_C",
    defaultValue: 200,
    category: "RESOURCE",
    description: "Matériaux variés utilisés pour fabriquer des vêtements et équipements en fourrure ou laine.",
    image: "assets/images/resources/PrimalItemResource_PeltOrHair_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_PeltOrHair.PrimalItemResource_PeltOrHair'",
    id: null
  },
  {
    nameFr: "Fragment d'Élément instable",
    key: "PrimalItemResource_ShardRefined_C",
    defaultValue: 1,
    category: "RESOURCE",
    description: "Fragment précieux d'élément instable, utilisé dans divers crafts avancés.",
    image: "assets/images/resources/PrimalItemResource_ShardRefined_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_ShardRefined.PrimalItemResource_ShardRefined'",
    id: null
  },
  {
    nameFr: "Fragment de carapace",
    key: "PrimalItemResource_TurtleShell_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Fragments de carapace de tortue, utilisés pour créer divers objets et équipements.",
    image: "assets/images/resources/PrimalItemResource_TurtleShell_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Genesis/CoreBlueprints/Resources/PrimalItemResource_TurtleShell.PrimalItemResource_TurtleShell'",
    id: null
  },
  {
    nameFr: "Fragment d’élément",
    key: "PrimalItemResource_ElementShard_C",
    defaultValue: 1000,
    category: "RESOURCE",
    description: "Fragment d'élément, essentiel pour les crafts et les constructions avancées.",
    image: "assets/images/resources/PrimalItemResource_ElementShard_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ElementShard.PrimalItemResource_ElementShard'",
    id: null
  },
  {
    nameFr: "Gaz condensé",
    key: "PrimalItemResource_CondensedGas_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Gaz condensé utilisé pour divers crafts et équipements.",
    image: "assets/images/resources/PrimalItemResource_CondensedGas_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_CondensedGas.PrimalItemResource_CondensedGas'",
    id: null
  },
  {
    nameFr: "Gelée de Baudroie abyssale",
    key: "PrimalItemResource_AnglerGel_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Gelée provenant des baudroies abyssales, utilisée dans divers crafts et potions.",
    image: "assets/images/resources/PrimalItemResource_AnglerGel_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_AnglerGel.PrimalItemResource_AnglerGel'",
    id: null
  },
  {
    nameFr: "Gemme Bleue",
    key: "PrimalItemResource_Gem_BioLum_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Gemme précieuse de couleur bleue, utilisée dans divers crafts sur Aberration.",
    image: "assets/images/resources/PrimalItemResource_Gem_BioLum_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_Gem_BioLum.PrimalItemResource_Gem_BioLum'",
    id: null
  },
  {
    nameFr: "Gemme Rouge",
    key: "PrimalItemResource_Gem_Element_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Gemme rouge utilisée dans divers crafts et équipements sur Aberration.",
    image: "assets/images/resources/PrimalItemResource_Gem_Element_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_Gem_Element.PrimalItemResource_Gem_Element'",
    id: null
  },
  {
    nameFr: "Gemme Verte",
    key: "PrimalItemResource_Gem_Fertile_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Gemme verte utilisée dans divers crafts et équipements sur Aberration.",
    image: "assets/images/resources/PrimalItemResource_Gem_Fertile_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_Gem_Fertile.PrimalItemResource_Gem_Fertile'",
    id: null
  },
  {
    nameFr: "Gemme verte fragmentée",
    key: "PrimalItemResource_FracturedGem_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Fragment de gemme verte, utilisé pour divers crafts avancés.",
    image: "assets/images/resources/PrimalItemResource_FracturedGem_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_FracturedGem.PrimalItemResource_FracturedGem'",
    id: null
  },
  {
    nameFr: "Laine",
    key: "PrimalItemResource_Wool_C",
    defaultValue: 200,
    category: "RESOURCE",
    description: "Laine utilisée pour fabriquer des vêtements et des équipements en laine.",
    image: "assets/images/resources/PrimalItemResource_Wool_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Wool.PrimalItemResource_Wool'",
    id: null
  },
  {
    nameFr: "Lingot de ferraille",
    key: "PrimalItemResource_ScrapMetalIngot_C",
    defaultValue: 200,
    category: "RESOURCE",
    description: "Lingot de ferraille, utilisé pour divers crafts et équipements.",
    image: "assets/images/resources/PrimalItemResource_ScrapMetalIngot_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_ScrapMetalIngot.PrimalItemResource_ScrapMetalIngot'",
    id: null
  },
  {
    nameFr: "Minerai d'Élément",
    key: "PrimalItemResource_ElementOre_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Minerai d'élément utilisé pour créer divers objets et équipements avancés.",
    image: "assets/images/resources/PrimalItemResource_ElementOre_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_ElementOre.PrimalItemResource_ElementOre'",
    id: null
  },
  {
    nameFr: "Mutagel",
    key: "PrimalItemConsumable_Mutagel_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Substance utilisée pour divers crafts et améliorations sur Genesis 2.",
    image: "assets/images/resources/PrimalItemConsumable_Mutagel_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Genesis2/CoreBlueprints/Environment/Mutagen/PrimalItemConsumable_Mutagel.PrimalItemConsumable_Mutagel'",
    id: null
  },
  {
    nameFr: "Mutagène",
    key: "PrimalItemConsumable_Mutagen_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Substance utilisée pour divers crafts et améliorations sur Genesis 2.",
    image: "assets/images/resources/PrimalItemConsumable_Mutagen_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Genesis2/CoreBlueprints/Environment/Mutagen/PrimalItemConsumable_Mutagen.PrimalItemConsumable_Mutagen'",
    id: null
  },
  {
    nameFr: "Nodule corrompu",
    key: "PrimalItemResource_CorruptedPolymer_C",
    defaultValue: 10,
    category: "RESOURCE",
    description: "Nodule corrompu utilisé pour divers crafts et améliorations.",
    image: "assets/images/resources/PrimalItemResource_CorruptedPolymer_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_CorruptedPolymer.PrimalItemResource_CorruptedPolymer'",
    id: null
  },
  {
    nameFr: "Os de dinosaure",
    key: "PrimalItemResource_ARKBone_C",
    defaultValue: 200,
    category: "RESOURCE",
    description: "Os de dinosaure utilisés pour fabriquer divers objets et équipements.",
    image: "assets/images/resources/PrimalItemResource_ARKBone_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_ARKBone.PrimalItemResource_ARKBone'",
    id: null
  },
  {
    nameFr: "Perle noire",
    key: "PrimalItemResource_BlackPearl_C",
    defaultValue: 200,
    category: "RESOURCE",
    description: "Perle rare utilisée pour divers crafts avancés.",
    image: "assets/images/resources/PrimalItemResource_BlackPearl_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_BlackPearl.PrimalItemResource_BlackPearl'",
    id: null
  },
  {
    nameFr: "Pollen de haute qualité",
    key: "PrimalItemResource_HighQualityPollen_C",
    defaultValue: 1,
    category: "RESOURCE",
    description: "Pollen de haute qualité utilisé pour divers crafts et améliorations.",
    image: "assets/images/resources/PrimalItemResource_HighQualityPollen_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/Missions/Retrieve/RetrieveItems/HighQualityPollen/PrimalItemResource_HighQualityPollen.PrimalItemResource_HighQualityPollen'",
    id: null
  },
  {
    nameFr: "Polymère organique",
    key: "PrimalItemResource_Polymer_Organic_C",
    defaultValue: 20,
    category: "RESOURCE",
    description: "Polymère organique utilisé pour divers crafts et équipements.",
    image: "assets/images/resources/PrimalItemResource_Polymer_Organic_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Polymer_Organic.PrimalItemResource_Polymer_Organic'",
    id: null
  },
  {
    nameFr: "Poudre d'Élément fabriquée",
    key: "PrimalItemResource_ElementDustFromShards_C",
    defaultValue: 1000,
    category: "RESOURCE",
    description: "Poudre d'élément fabriquée à partir de fragments, utilisée pour divers crafts avancés.",
    image: "assets/images/resources/PrimalItemResource_ElementDustFromShards_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_ElementDustFromShards.PrimalItemResource_ElementDustFromShards'",
    id: null
  },
  {
    nameFr: "Poussière d'élément",
    key: "PrimalItemResource_ElementDust_C",
    defaultValue: 1000,
    category: "RESOURCE",
    description: "Poussière d'élément, utilisée dans divers crafts avancés.",
    image: "assets/images/resources/PrimalItemResource_ElementDust_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_ElementDust.PrimalItemResource_ElementDust'",
    id: null
  },
  {
    nameFr: "Cristal primordial",
    key: "PrimalItemResource_Crystal_IslesPrimal_C",
    defaultValue: 1,
    category: "RESOURCE",
    description: "Cristal primordial utilisé dans divers crafts et améliorations sur Crystal Isles.",
    image: "assets/images/resources/PrimalItemResource_Crystal_IslesPrimal_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Dinos/CrystalWyvern/CrystalResources/Primal/PrimalItemResource_Crystal_IslesPrimal.PrimalItemResource_Crystal_IslesPrimal'",
    id: null
  },
  {
    nameFr: "Pépite d'Or",
    key: "PrimalItemResource_GoldenNugget_C",
    defaultValue: 1,
    category: "RESOURCE",
    description: "Pépite d'or rare utilisée dans divers crafts et améliorations.",
    image: "assets/images/resources/PrimalItemResource_GoldenNugget_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/Missions/Retrieve/RetrieveItems/GoldenNugget/PrimalItemResource_GoldenNugget.PrimalItemResource_GoldenNugget'",
    id: null
  },
  {
    nameFr: "Sable",
    key: "PrimalItemResource_Sand_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Sable utilisé pour divers crafts et constructions.",
    image: "assets/images/resources/PrimalItemResource_Sand_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_Sand.PrimalItemResource_Sand'",
    id: null
  },
  {
    nameFr: "Sang de Sangsue",
    key: "PrimalItemResource_LeechBlood_C",
    defaultValue: 50,
    category: "RESOURCE",
    description: "Sang de sangsue utilisé pour divers crafts et potions.",
    image: "assets/images/resources/PrimalItemResource_LeechBlood_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_LeechBlood.PrimalItemResource_LeechBlood'",
    id: null
  },
  {
    nameFr: "Sang de Sangsue ou Cornes",
    key: "PrimalItemResourceGeneric_Curing_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Utilisé pour les crafts de guérison, et dans certains cas, les cornes de créature peuvent être utilisées à la place.",
    image: "assets/images/resources/PrimalItemResourceGeneric_Curing_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResourceGeneric_Curing.PrimalItemResourceGeneric_Curing'",
    id: null
  },
  {
    nameFr: "Sel brut",
    key: "PrimalItemResource_RawSalt_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Sel brut utilisé pour divers crafts et conservations.",
    image: "assets/images/resources/PrimalItemResource_RawSalt_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_RawSalt.PrimalItemResource_RawSalt'",
    id: null
  },
  {
    nameFr: "Sel de conservation",
    key: "PrimalItemResource_PreservingSalt_C",
    defaultValue: 6,
    category: "RESOURCE",
    description: "Sel utilisé pour la conservation des aliments.",
    image: "assets/images/resources/PrimalItemResource_PreservingSalt_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_PreservingSalt.PrimalItemResource_PreservingSalt'",
    id: null
  },
  {
    nameFr: "Silice",
    key: "PrimalItemResource_Silicate_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Silice utilisée dans divers crafts et constructions.",
    image: "assets/images/resources/PrimalItemResource_Silicate_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_Silicate.PrimalItemResource_Silicate'",
    id: null
  },
  {
    nameFr: "Soie",
    key: "PrimalItemResource_Silk_C",
    defaultValue: 200,
    category: "RESOURCE",
    description: "Soie utilisée pour divers crafts et vêtements.",
    image: "assets/images/resources/PrimalItemResource_Silk_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_Silk.PrimalItemResource_Silk'",
    id: null
  },
  {
    nameFr: "Soufre",
    key: "PrimalItemResource_Sulfur_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Soufre utilisé pour divers crafts et créations.",
    image: "assets/images/resources/PrimalItemResource_Sulfur_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/CoreBlueprints/Resources/PrimalItemResource_Sulfur.PrimalItemResource_Sulfur'",
    id: null
  },
  {
    nameFr: "Sphère de Gaz congelé",
    key: "PrimalItemResource_Gas_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Sphère de gaz congelé utilisée pour divers crafts et équipements.",
    image: "assets/images/resources/PrimalItemResource_Gas_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Resources/PrimalItemResource_Gas.PrimalItemResource_Gas'",
    id: null
  },
  {
    nameFr: "Substrat absorbant",
    key: "PrimalItemResource_SubstrateAbsorbent_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Substrat absorbant utilisé dans divers crafts et améliorations.",
    image: "assets/images/resources/PrimalItemResource_SubstrateAbsorbent_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_SubstrateAbsorbent.PrimalItemResource_SubstrateAbsorbent'",
    id: null
  },
  {
    nameFr: "Sève cristallisée bleue",
    key: "PrimalItemResource_BlueSap_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Sève cristallisée bleue utilisée dans divers crafts et améliorations.",
    image: "assets/images/resources/PrimalItemResource_BlueSap_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_BlueSap.PrimalItemResource_BlueSap'",
    id: null
  },
  {
    nameFr: "Sève cristallisée rouge",
    key: "PrimalItemResource_RedSap_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Sève cristallisée rouge utilisée dans divers crafts et améliorations.",
    image: "assets/images/resources/PrimalItemResource_RedSap_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_RedSap.PrimalItemResource_RedSap'",
    id: null
  },
  {
    nameFr: "Sève",
    key: "PrimalItemResource_Sap_C",
    defaultValue: 30,
    category: "RESOURCE",
    description: "Sève utilisée pour divers crafts et améliorations.",
    image: "assets/images/resources/PrimalItemResource_Sap_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Sap.PrimalItemResource_Sap'",
    id: null
  },
  {
    nameFr: "Élément instable",
    key: "PrimalItemResource_ElementRefined_C",
    defaultValue: 1,
    category: "RESOURCE",
    description: "Élément instable, utilisé dans divers crafts avancés.",
    image: "assets/images/resources/PrimalItemResource_ElementRefined_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Resources/PrimalItemResource_ElementRefined.PrimalItemResource_ElementRefined'",
    id: null
  },
  {
    nameFr: "Élément",
    key: "PrimalItemResource_Element_C",
    defaultValue: 100,
    category: "RESOURCE",
    description: "Élément utilisé dans divers crafts avancés.",
    image: "assets/images/resources/PrimalItemResource_Element_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_Element.PrimalItemResource_Element'",
    id: null
  }
];
