export const MUNITIONS = [
  {
    nameFr: "Ancrage pour tyrolienne",
    key: "PrimalItemAmmo_Zipline_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Ancrage pour créer des tyroliennes.",
    image: "assets/images/ammo/PrimalItemAmmo_Zipline_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Weapons/PrimalItemAmmo_Zipline.PrimalItemAmmo_Zipline'",
    id: null
  },
  {
    nameFr: "Balle de fusil d'assaut",
    key: "PrimalItemAmmo_AdvancedRifleBullet_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Munitions pour fusil d'assaut.",
    image: "assets/images/ammo/PrimalItemAmmo_AdvancedRifleBullet_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_AdvancedRifleBullet.PrimalItemAmmo_AdvancedRifleBullet'",
    id: 242
  },
  {
    nameFr: "Balle de fusil de précision",
    key: "PrimalItemAmmo_AdvancedSniperBullet_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Munitions pour fusil de précision.",
    image: "assets/images/ammo/PrimalItemAmmo_AdvancedSniperBullet_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_AdvancedSniperBullet.PrimalItemAmmo_AdvancedSniperBullet'",
    id: null
  },
  {
    nameFr: "Balle de fusil à canon long",
    key: "PrimalItemAmmo_SimpleRifleBullet_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Munitions pour fusil à canon long.",
    image: "assets/images/ammo/PrimalItemAmmo_SimpleRifleBullet_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_SimpleRifleBullet.PrimalItemAmmo_SimpleRifleBullet'",
    id: 143
  },
  {
    nameFr: "Balle de pistolet semi-auto",
    key: "PrimalItemAmmo_AdvancedBullet_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Munitions pour pistolet semi-automatique.",
    image: "assets/images/ammo/PrimalItemAmmo_AdvancedBullet_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_AdvancedBullet.PrimalItemAmmo_AdvancedBullet'",
    id: 241
  },
  {
    nameFr: "Balle de revolver",
    key: "PrimalItemAmmo_SimpleBullet_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Munitions pour revolver.",
    image: "assets/images/ammo/PrimalItemAmmo_SimpleBullet_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_SimpleBullet.PrimalItemAmmo_SimpleBullet'",
    id: 4
  },
  {
    nameFr: "Boulet de canon",
    key: "PrimalItemAmmo_CannonBall_C",
    defaultValue: 1,
    category: "Munitions",
    description: "Projectile pour canon.",
    image: "assets/images/ammo/PrimalItemAmmo_CannonBall_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_CannonBall.PrimalItemAmmo_CannonBall'",
    id: null
  },
  {
    nameFr: "Boulet renforcé",
    key: "PrimalItemAmmo_Boulder_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Projectile pour les catapultes.",
    image: "assets/images/ammo/PrimalItemAmmo_Boulder_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_Boulder.PrimalItemAmmo_Boulder'",
    id: null
  },
  {
    nameFr: "Cartouche de fusil à pompe",
    key: "PrimalItemAmmo_SimpleShotgunBullet_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Munitions pour fusil à pompe.",
    image: "assets/images/ammo/PrimalItemAmmo_SimpleShotgunBullet_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_SimpleShotgunBullet.PrimalItemAmmo_SimpleShotgunBullet'",
    id: 264
  },
  {
    nameFr: "Charge de C4",
    key: "PrimalItemC4Ammo_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Explosif contrôlé à distance.",
    image: "assets/images/ammo/PrimalItemC4Ammo_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemC4Ammo.PrimalItemC4Ammo'",
    id: 43
  },
  {
    nameFr: "Essaim de roquette",
    key: "PrimalItemAmmo_RocketPod_C",
    defaultValue: 1,
    category: "Munitions",
    description: "Munitions pour des attaques multiples.",
    image: "assets/images/ammo/PrimalItemAmmo_RocketPod_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Weapons/PrimalItemAmmo_RocketPod.PrimalItemAmmo_RocketPod'",
    id: null
  },
  {
    nameFr: "Flèche en fonte",
    key: "PrimalItemAmmo_BallistaArrow_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Flèche pour baliste.",
    image: "assets/images/ammo/PrimalItemAmmo_BallistaArrow_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_BallistaArrow.PrimalItemAmmo_BallistaArrow'",
    id: null
  },
  {
    nameFr: "Flèche en métal",
    key: "PrimalItemAmmo_CompoundBowArrow_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Flèche pour arc à poulie.",
    image: "assets/images/ammo/PrimalItemAmmo_CompoundBowArrow_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_CompoundBowArrow.PrimalItemAmmo_CompoundBowArrow'",
    id: 373
  },
  {
    nameFr: "Flèche en pierre",
    key: "PrimalItemAmmo_ArrowStone_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Flèche standard en pierre.",
    image: "assets/images/ammo/PrimalItemAmmo_ArrowStone_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_ArrowStone.PrimalItemAmmo_ArrowStone'",
    id: 32
  },
  {
    nameFr: "Flèche enflammée",
    key: "PrimalItemAmmo_ArrowFlame_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Flèche qui brûle les cibles.",
    image: "assets/images/ammo/PrimalItemAmmo_ArrowFlame_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_ArrowFlame.PrimalItemAmmo_ArrowFlame'",
    id: null
  },
  {
    nameFr: "Flèche tranquillisante en fonte",
    key: "PrimalItemAmmo_TranqSpearBolt_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Flèche tranquillisante en métal pour baliste.",
    image: "assets/images/ammo/PrimalItemAmmo_TranqSpearBolt_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_TranqSpearBolt.PrimalItemAmmo_TranqSpearBolt'",
    id: null
  },
  {
    nameFr: "Flèche tranquillisante",
    key: "PrimalItemAmmo_ArrowTranq_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Flèche tranquillisante pour assommer les créatures.",
    image: "assets/images/ammo/PrimalItemAmmo_ArrowTranq_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_ArrowTranq.PrimalItemAmmo_ArrowTranq'",
    id: 70
  },
  {
    nameFr: "Fléchette de phéromone",
    key: "PrimalItemAmmo_AggroTranqDart_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Fléchette qui attire les créatures.",
    image: "assets/images/ammo/PrimalItemAmmo_AggroTranqDart_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_AggroTranqDart.PrimalItemAmmo_AggroTranqDart'",
    id: null
  },
  {
    nameFr: "Fléchette tranquillisante améliorée",
    key: "PrimalItemAmmo_RefinedTranqDart_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Fléchette tranquillisante plus efficace.",
    image: "assets/images/ammo/PrimalItemAmmo_RefinedTranqDart_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_RefinedTranqDart.PrimalItemAmmo_RefinedTranqDart'",
    id: null
  },
  {
    nameFr: "Fléchette tranquillisante",
    key: "PrimalItemAmmo_TranqDart_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Fléchette tranquillisante standard.",
    image: "assets/images/ammo/PrimalItemAmmo_TranqDart_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_TranqDart.PrimalItemAmmo_TranqDart'",
    id: null
  },
  {
    nameFr: "Grappin",
    key: "PrimalItemAmmo_GrapplingHook_C",
    defaultValue: 10,
    category: "Munitions",
    description: "Grappin pour grimper ou capturer.",
    image: "assets/images/ammo/PrimalItemAmmo_GrapplingHook_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_GrapplingHook.PrimalItemAmmo_GrapplingHook'",
    id: null
  },
  {
    nameFr: "Missile téléguidé",
    key: "PrimalItemAmmo_RocketHomingMissile_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Missile qui suit les cibles.",
    image: "assets/images/ammo/PrimalItemAmmo_RocketHomingMissile_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/WeaponHomingMissile/PrimalItemAmmo_RocketHomingMissile.PrimalItemAmmo_RocketHomingMissile'",
    id: null
  },
  {
    nameFr: "Munitions pour Lance-flamme",
    key: "PrimalItemAmmo_Flamethrower_C",
    defaultValue: 30,
    category: "Munitions",
    description: "Carburant pour lance-flamme.",
    image: "assets/images/ammo/PrimalItemAmmo_Flamethrower_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/WeaponFlamethrower/PrimalItemAmmo_Flamethrower.PrimalItemAmmo_Flamethrower'",
    id: null
  },
  {
    nameFr: "Obus de Canon",
    key: "PrimalItemAmmo_CannonShell_C",
    defaultValue: 1,
    category: "Munitions",
    description: "Obus pour canon avancé.",
    image: "assets/images/ammo/PrimalItemAmmo_CannonShell_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Weapons/PrimalItemAmmo_CannonShell.PrimalItemAmmo_CannonShell'",
    id: null
  },
  {
    nameFr: "Roquette",
    key: "PrimalItemAmmo_Rocket_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Roquette pour lance-roquettes.",
    image: "assets/images/ammo/PrimalItemAmmo_Rocket_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_Rocket.PrimalItemAmmo_Rocket'",
    id: 243
  },
  {
    nameFr: "Transpondeur",
    key: "PrimalItemTransGPSAmmo_C",
    defaultValue: 100,
    category: "Munitions",
    description: "Dispositif pour suivre les créatures ou objets.",
    image: "assets/images/ammo/PrimalItemTransGPSAmmo_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItemTransGPSAmmo.PrimalItemTransGPSAmmo'",
    id: 369
  }
];
