export const SADDLES = [
  {
    nameFr: "Plateforme pour Mosasaure",
    key: "PrimalItemArmor_MosaSaddle_Platform_C",
    defaultValue: 1,
    category: "Selles",
    description: "Plateforme pour Mosasaure.",
    image: "assets/images/saddles/PrimalItemArmor_MosaSaddle_Platform_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MosaSaddle_Platform.PrimalItemArmor_MosaSaddle_Platform'",
    id: null
  },
  {
    nameFr: "Plateforme pour Mégachelon",
    key: "PrimalItemArmor_GiantTurtleSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Plateforme pour Mégachelon.",
    image: "assets/images/saddles/PrimalItemArmor_GiantTurtleSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/Dinos/GiantTurtle/PrimalItemArmor_GiantTurtleSaddle.PrimalItemArmor_GiantTurtleSaddle'",
    id: null
  },
  {
    nameFr: "Plateforme pour Plésiosaure",
    key: "PrimalItemArmor_PlesiSaddle_Platform_C",
    defaultValue: 1,
    category: "Selles",
    description: "Plateforme pour Plésiosaure.",
    image: "assets/images/saddles/PrimalItemArmor_PlesiSaddle_Platform_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PlesiSaddle_Platform.PrimalItemArmor_PlesiSaddle_Platform'",
    id: null
  },
  {
    nameFr: "Plateforme pour Quetzal",
    key: "PrimalItemArmor_QuetzSaddle_Platform_C",
    defaultValue: 1,
    category: "Selles",
    description: "Plateforme pour Quetzal.",
    image: "assets/images/saddles/PrimalItemArmor_QuetzSaddle_Platform_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_QuetzSaddle_Platform.PrimalItemArmor_QuetzSaddle_Platform'",
    id: null
  },
  {
    nameFr: "Plateforme pour Titanosaure",
    key: "PrimalItemArmor_TitanSaddle_Platform_C",
    defaultValue: 1,
    category: "Selles",
    description: "Plateforme pour Titanosaure.",
    image: "assets/images/saddles/PrimalItemArmor_TitanSaddle_Platform_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TitanSaddle_Platform.PrimalItemArmor_TitanSaddle_Platform'",
    id: null
  },
  {
    nameFr: "Sacoche de viande",
    key: "PrimalItemArmor_HyaenodonSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Sacoche de viande pour Hyaenodon.",
    image: "assets/images/saddles/PrimalItemArmor_HyaenodonSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_HyaenodonSaddle.PrimalItemArmor_HyaenodonSaddle'",
    id: null
  },
  {
    nameFr: "Selle Tek de Dragon Rocheux",
    key: "PrimalItemArmor_RockDrakeSaddle_Tek_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle Tek pour Dragon Rocheux.",
    image: "assets/images/saddles/PrimalItemArmor_RockDrakeSaddle_Tek_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/Dinos/RockDrake/PrimalItemArmor_RockDrakeSaddle_Tek.PrimalItemArmor_RockDrakeSaddle_Tek'",
    id: null
  },
  {
    nameFr: "Selle Tek de Mosasaure",
    key: "PrimalItemArmor_MosaSaddle_Tek_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle Tek pour Mosasaure.",
    image: "assets/images/saddles/PrimalItemArmor_MosaSaddle_Tek_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MosaSaddle_Tek.PrimalItemArmor_MosaSaddle_Tek'",
    id: null
  },
  {
    nameFr: "Selle Tek de Mégalodon",
    key: "PrimalItemArmor_MegalodonSaddle_Tek_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle Tek pour Mégalodon.",
    image: "assets/images/saddles/PrimalItemArmor_MegalodonSaddle_Tek_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MegalodonSaddle_Tek.PrimalItemArmor_MegalodonSaddle_Tek'",
    id: null
  },
  {
    nameFr: "Selle Tek de T-Rex",
    key: "PrimalItemArmor_RexSaddle_Tek_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle Tek pour T-Rex.",
    image: "assets/images/saddles/PrimalItemArmor_RexSaddle_Tek_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_RexSaddle_Tek.PrimalItemArmor_RexSaddle_Tek'",
    id: null
  },
  {
    nameFr: "Selle Tek de Tapejara",
    key: "PrimalItemArmor_Tapejara_Tek_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle Tek pour Tapejara.",
    image: "assets/images/saddles/PrimalItemArmor_Tapejara_Tek_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_Tapejara_Tek.PrimalItemArmor_Tapejara_Tek'",
    id: null
  },
  {
    nameFr: "Selle d'Allosaure",
    key: "PrimalItemArmor_AlloSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Allosaure.",
    image: "assets/images/saddles/PrimalItemArmor_AlloSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_AlloSaddle.PrimalItemArmor_AlloSaddle'",
    id: null
  },
  {
    nameFr: "Selle d'Aranéo",
    key: "PrimalItemArmor_SpiderSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Aranéo.",
    image: "assets/images/saddles/PrimalItemArmor_SpiderSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SpiderSaddle.PrimalItemArmor_SpiderSaddle'",
    id: null
  },
  {
    nameFr: "Selle d'Arthropleura",
    key: "PrimalItemArmor_ArthroSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Arthropleura.",
    image: "assets/images/saddles/PrimalItemArmor_ArthroSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ArthroSaddle.PrimalItemArmor_ArthroSaddle'",
    id: null
  },
  {
    nameFr: "Selle d'Equus",
    key: "PrimalItemArmor_EquusSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Equus.",
    image: "assets/images/saddles/PrimalItemArmor_EquusSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_EquusSaddle.PrimalItemArmor_EquusSaddle'",
    id: null
  },
  {
    nameFr: "Selle d'Iguanodon",
    key: "PrimalItemArmor_IguanodonSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Iguanodon.",
    image: "assets/images/saddles/PrimalItemArmor_IguanodonSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_IguanodonSaddle.PrimalItemArmor_IguanodonSaddle'",
    id: null
  },
  {
    nameFr: "Selle d'Ours Sinistre",
    key: "PrimalItemArmor_DireBearSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Ours Sinistre.",
    image: "assets/images/saddles/PrimalItemArmor_DireBearSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_DireBearSaddle.PrimalItemArmor_DireBearSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Baryonyx",
    key: "PrimalItemArmor_BaryonyxSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Baryonyx.",
    image: "assets/images/saddles/PrimalItemArmor_BaryonyxSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_BaryonyxSaddle.PrimalItemArmor_BaryonyxSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Basilic",
    key: "PrimalItemArmor_BasiliskSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Basilic.",
    image: "assets/images/saddles/PrimalItemArmor_BasiliskSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/Dinos/Basilisk/PrimalItemArmor_BasiliskSaddle.PrimalItemArmor_BasiliskSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Basilosaure",
    key: "PrimalItemArmor_BasiloSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Basilosaure.",
    image: "assets/images/saddles/PrimalItemArmor_BasiloSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_BasiloSaddle.PrimalItemArmor_BasiloSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Castoroides",
    key: "PrimalItemArmor_BeaverSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Castoroides.",
    image: "assets/images/saddles/PrimalItemArmor_BeaverSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_BeaverSaddle.PrimalItemArmor_BeaverSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Chalicotherium",
    key: "PrimalItemArmor_ChalicoSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Chalicotherium.",
    image: "assets/images/saddles/PrimalItemArmor_ChalicoSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ChalicoSaddle.PrimalItemArmor_ChalicoSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Daeodon",
    key: "PrimalItemArmor_DaeodonSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Daeodon.",
    image: "assets/images/saddles/PrimalItemArmor_DaeodonSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_DaeodonSaddle.PrimalItemArmor_DaeodonSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Deinonychus",
    key: "PrimalItemArmor_DeinonychusSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Deinonychus.",
    image: "assets/images/saddles/PrimalItemArmor_DeinonychusSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Valguero/Dinos/Deinonychus/PrimalItemArmor_DeinonychusSaddle.PrimalItemArmor_DeinonychusSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Diplodocus",
    key: "PrimalItemArmor_DiplodocusSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Diplodocus.",
    image: "assets/images/saddles/PrimalItemArmor_DiplodocusSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_DiplodocusSaddle.PrimalItemArmor_DiplodocusSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Dragon Rocheux",
    key: "PrimalItemArmor_RockDrakeSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Dragon Rocheux.",
    image: "assets/images/saddles/PrimalItemArmor_RockDrakeSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/Dinos/RockDrake/PrimalItemArmor_RockDrakeSaddle.PrimalItemArmor_RockDrakeSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Dunkleosteus",
    key: "PrimalItemArmor_DunkleosteusSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Dunkleosteus.",
    image: "assets/images/saddles/PrimalItemArmor_DunkleosteusSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_DunkleosteusSaddle.PrimalItemArmor_DunkleosteusSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Gacha",
    key: "PrimalItemArmor_GachaSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Gacha.",
    image: "assets/images/saddles/PrimalItemArmor_GachaSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/Saddle/PrimalItemArmor_GachaSaddle.PrimalItemArmor_GachaSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Gallimimus",
    key: "PrimalItemArmor_Gallimimus_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Gallimimus.",
    image: "assets/images/saddles/PrimalItemArmor_Gallimimus_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_Gallimimus.PrimalItemArmor_Gallimimus'",
    id: null
  },
  {
    nameFr: "Selle de Giganotosaure",
    key: "PrimalItemArmor_GigantSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Giganotosaure.",
    image: "assets/images/saddles/PrimalItemArmor_GigantSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_GigantSaddle.PrimalItemArmor_GigantSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Golem de pierre",
    key: "PrimalItemArmor_RockGolemSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Golem de pierre.",
    image: "assets/images/saddles/PrimalItemArmor_RockGolemSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/RockGolem/PrimalItemArmor_RockGolemSaddle.PrimalItemArmor_RockGolemSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Harfang des neiges",
    key: "PrimalItemArmor_OwlSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Harfang des neiges.",
    image: "assets/images/saddles/PrimalItemArmor_OwlSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/Saddle/PrimalItemArmor_OwlSaddle.PrimalItemArmor_OwlSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Kaprosuchus",
    key: "PrimalItemArmor_KaprosuchusSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Kaprosuchus.",
    image: "assets/images/saddles/PrimalItemArmor_KaprosuchusSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_KaprosuchusSaddle.PrimalItemArmor_KaprosuchusSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Karkinos",
    key: "PrimalItemArmor_CrabSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Karkinos.",
    image: "assets/images/saddles/PrimalItemArmor_CrabSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/Dinos/Crab/PrimalItemArmor_CrabSaddle.PrimalItemArmor_CrabSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Lymantria",
    key: "PrimalItemArmor_MothSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Lymantria.",
    image: "assets/images/saddles/PrimalItemArmor_MothSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/Moth/PrimalItemArmor_MothSaddle.PrimalItemArmor_MothSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Lézard épineux",
    key: "PrimalItemArmor_SpineyLizardSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Lézard épineux.",
    image: "assets/images/saddles/PrimalItemArmor_SpineyLizardSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/SpineyLizard/PrimalItemArmor_SpineyLizardSaddle.PrimalItemArmor_SpineyLizardSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Magmasaure",
    key: "PrimalItemArmor_CherufeSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Magmasaure.",
    image: "assets/images/saddles/PrimalItemArmor_CherufeSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/Dinos/Cherufe/PrimalItemArmor_CherufeSaddle.PrimalItemArmor_CherufeSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Managarm",
    key: "PrimalItemArmor_IceJumperSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Managarm.",
    image: "assets/images/saddles/PrimalItemArmor_IceJumperSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/Saddle/PrimalItemArmor_IceJumperSaddle.PrimalItemArmor_IceJumperSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Manta",
    key: "PrimalItemArmor_MantaSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Manta.",
    image: "assets/images/saddles/PrimalItemArmor_MantaSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MantaSaddle.PrimalItemArmor_MantaSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Mantis",
    key: "PrimalItemArmor_MantisSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Mantis.",
    image: "assets/images/saddles/PrimalItemArmor_MantisSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/Mantis/PrimalItemArmor_MantisSaddle.PrimalItemArmor_MantisSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Megalania",
    key: "PrimalItemArmor_MegalaniaSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Megalania.",
    image: "assets/images/saddles/PrimalItemArmor_MegalaniaSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MegalaniaSaddle.PrimalItemArmor_MegalaniaSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Morellatops",
    key: "PrimalItemArmor_CamelsaurusSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Morellatops.",
    image: "assets/images/saddles/PrimalItemArmor_CamelsaurusSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/Dinos/Camelsaurus/PrimalItemArmor_CamelsaurusSaddle.PrimalItemArmor_CamelsaurusSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Mosasaure",
    key: "PrimalItemArmor_MosaSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Mosasaure.",
    image: "assets/images/saddles/PrimalItemArmor_MosaSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MosaSaddle.PrimalItemArmor_MosaSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Mégalosaure",
    key: "PrimalItemArmor_MegalosaurusSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Mégalosaure.",
    image: "assets/images/saddles/PrimalItemArmor_MegalosaurusSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MegalosaurusSaddle.PrimalItemArmor_MegalosaurusSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Mégathérium",
    key: "PrimalItemArmor_MegatheriumSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Mégathérium.",
    image: "assets/images/saddles/PrimalItemArmor_MegatheriumSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MegatheriumSaddle.PrimalItemArmor_MegatheriumSaddle'",
    id: null
  },
  {
    nameFr: "Selle d'Oiseau-Terreur",
    key: "PrimalItemArmor_TerrorBirdSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Oiseau-Terreur.",
    image: "assets/images/saddles/PrimalItemArmor_TerrorBirdSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TerrorBirdSaddle.PrimalItemArmor_TerrorBirdSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Pachyrhinosaure",
    key: "PrimalItemArmor_PachyrhinoSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Pachyrhinosaure.",
    image: "assets/images/saddles/PrimalItemArmor_PachyrhinoSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PachyrhinoSaddle.PrimalItemArmor_PachyrhinoSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Pelagornis",
    key: "PrimalItemArmor_PelaSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Pelagornis.",
    image: "assets/images/saddles/PrimalItemArmor_PelaSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PelaSaddle.PrimalItemArmor_PelaSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Procoptodon",
    key: "PrimalItemArmor_ProcoptodonSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Procoptodon.",
    image: "assets/images/saddles/PrimalItemArmor_ProcoptodonSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ProcoptodonSaddle.PrimalItemArmor_ProcoptodonSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Quetzal",
    key: "PrimalItemArmor_QuetzSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Quetzal.",
    image: "assets/images/saddles/PrimalItemArmor_QuetzSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_QuetzSaddle.PrimalItemArmor_QuetzSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Rat des profondeurs",
    key: "PrimalItemArmor_MoleRatSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Rat des profondeurs.",
    image: "assets/images/saddles/PrimalItemArmor_MoleRatSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/Dinos/MoleRat/PrimalItemArmor_MoleRatSaddle.PrimalItemArmor_MoleRatSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Ravageur",
    key: "PrimalItemArmor_CavewolfSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Ravageur.",
    image: "assets/images/saddles/PrimalItemArmor_CavewolfSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/Dinos/CaveWolf/PrimalItemArmor_CavewolfSaddle.PrimalItemArmor_CavewolfSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Rhinocéros laineux",
    key: "PrimalItemArmor_RhinoSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Rhinocéros laineux.",
    image: "assets/images/saddles/PrimalItemArmor_RhinoSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_RhinoSaddle.PrimalItemArmor_RhinoSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Tapejara",
    key: "PrimalItemArmor_TapejaraSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Tapejara.",
    image: "assets/images/saddles/PrimalItemArmor_TapejaraSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TapejaraSaddle.PrimalItemArmor_TapejaraSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Thylacoleo",
    key: "PrimalItemArmor_ThylacoSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Thylacoleo.",
    image: "assets/images/saddles/PrimalItemArmor_ThylacoSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ThylacoSaddle.PrimalItemArmor_ThylacoSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Thérizinosaure",
    key: "PrimalItemArmor_TherizinosaurusSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Thérizinosaure.",
    image: "assets/images/saddles/PrimalItemArmor_TherizinosaurusSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TherizinosaurusSaddle.PrimalItemArmor_TherizinosaurusSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Tropéognathus",
    key: "PrimalItemArmor_TropeSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Tropéognathus.",
    image: "assets/images/saddles/PrimalItemArmor_TropeSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Dinos/Tropeognathus/PrimalItemArmor_TropeSaddle.PrimalItemArmor_TropeSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Tusoteuthis",
    key: "PrimalItemArmor_TusoSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Tusoteuthis.",
    image: "assets/images/saddles/PrimalItemArmor_TusoSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TusoSaddle.PrimalItemArmor_TusoSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Vélonasaure",
    key: "PrimalItemArmor_SpindlesSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Vélonasaure.",
    image: "assets/images/saddles/PrimalItemArmor_SpindlesSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/Saddle/PrimalItemArmor_SpindlesSaddle.PrimalItemArmor_SpindlesSaddle'",
    id: null
  },
  {
    nameFr: "Selle de Yutyrannus",
    key: "PrimalItemArmor_YutySaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Yutyrannus.",
    image: "assets/images/saddles/PrimalItemArmor_YutySaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_YutySaddle.PrimalItemArmor_YutySaddle'",
    id: null
  },
  {
    nameFr: "Selle du Sacagaz",
    key: "PrimalItemArmor_GasBagsSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Sacagaz.",
    image: "assets/images/saddles/PrimalItemArmor_GasBagsSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Items/Saddle/PrimalItemArmor_GasBagsSaddle.PrimalItemArmor_GasBagsSaddle'",
    id: null
  },
  {
    nameFr: "Selle de T-Rex",
    key: "PrimalItemArmor_RexSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour T-Rex.",
    image: "assets/images/saddles/PrimalItemArmor_RexSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_RexSaddle.PrimalItemArmor_RexSaddle'",
    id: 69
  },
  {
    nameFr: "Selle de Parasaure",
    key: "PrimalItemArmor_ParaSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Parasaure.",
    image: "assets/images/saddles/PrimalItemArmor_ParaSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ParaSaddle.PrimalItemArmor_ParaSaddle'",
    id: 99
  },
  {
    nameFr: "Selle de Raptor",
    key: "PrimalItemArmor_RaptorSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Raptor.",
    image: "assets/images/saddles/PrimalItemArmor_RaptorSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_RaptorSaddle.PrimalItemArmor_RaptorSaddle'",
    id: 100
  },
  {
    nameFr: "Selle de Stégosaure",
    key: "PrimalItemArmor_StegoSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Stégosaure.",
    image: "assets/images/saddles/PrimalItemArmor_StegoSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_StegoSaddle.PrimalItemArmor_StegoSaddle'",
    id: 101
  },
  {
    nameFr: "Selle de Tricératops",
    key: "PrimalItemArmor_TrikeSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Tricératops.",
    image: "assets/images/saddles/PrimalItemArmor_TrikeSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TrikeSaddle.PrimalItemArmor_TrikeSaddle'",
    id: 102
  },
  {
    nameFr: "Selle de Pulmonoscorpius",
    key: "PrimalItemArmor_ScorpionSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Pulmonoscorpius.",
    image: "assets/images/saddles/PrimalItemArmor_ScorpionSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ScorpionSaddle.PrimalItemArmor_ScorpionSaddle'",
    id: 103
  },
  {
    nameFr: "Selle de Ptéranodon",
    key: "PrimalItemArmor_PteroSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Ptéranodon.",
    image: "assets/images/saddles/PrimalItemArmor_PteroSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PteroSaddle.PrimalItemArmor_PteroSaddle'",
    id: 130
  },
  {
    nameFr: "Selle de Brontosaure",
    key: "PrimalItemArmor_SauroSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Brontosaure.",
    image: "assets/images/saddles/PrimalItemArmor_SauroSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SauroSaddle.PrimalItemArmor_SauroSaddle'",
    id: 134
  },
  {
    nameFr: "Selle de Carbonemys",
    key: "PrimalItemArmor_TurtleSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Carbonemys.",
    image: "assets/images/saddles/PrimalItemArmor_TurtleSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TurtleSaddle.PrimalItemArmor_TurtleSaddle'",
    id: 204
  },
  {
    nameFr: "Selle de Sarcosuchus",
    key: "PrimalItemArmor_SarcoSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Sarcosuchus.",
    image: "assets/images/saddles/PrimalItemArmor_SarcoSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SarcoSaddle.PrimalItemArmor_SarcoSaddle'",
    id: 205
  },
  {
    nameFr: "Selle d'Ankylosaure",
    key: "PrimalItemArmor_AnkyloSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Ankylosaure.",
    image: "assets/images/saddles/PrimalItemArmor_AnkyloSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_AnkyloSaddle.PrimalItemArmor_AnkyloSaddle'",
    id: 206
  },
  {
    nameFr: "Selle de Mammouth",
    key: "PrimalItemArmor_MammothSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Mammouth.",
    image: "assets/images/saddles/PrimalItemArmor_MammothSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MammothSaddle.PrimalItemArmor_MammothSaddle'",
    id: 207
  },
  {
    nameFr: "Selle de Mégalodon",
    key: "PrimalItemArmor_MegalodonSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Mégalodon.",
    image: "assets/images/saddles/PrimalItemArmor_MegalodonSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MegalodonSaddle.PrimalItemArmor_MegalodonSaddle'",
    id: 208
  },
  {
    nameFr: "Selle de Smilodon",
    key: "PrimalItemArmor_SaberSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Smilodon.",
    image: "assets/images/saddles/PrimalItemArmor_SaberSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SaberSaddle.PrimalItemArmor_SaberSaddle'",
    id: 209
  },
  {
    nameFr: "Selle de Carnotaure",
    key: "PrimalItemArmor_CarnoSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Carnotaure.",
    image: "assets/images/saddles/PrimalItemArmor_CarnoSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarnoSaddle.PrimalItemArmor_CarnoSaddle'",
    id: 210
  },
  {
    nameFr: "Selle d'Argentavis",
    key: "PrimalItemArmor_ArgentavisSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Argentavis.",
    image: "assets/images/saddles/PrimalItemArmor_ArgentavisSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ArgentavisSaddle.PrimalItemArmor_ArgentavisSaddle'",
    id: 211
  },
  {
    nameFr: "Selle de Phiomia",
    key: "PrimalItemArmor_PhiomiaSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Phiomia.",
    image: "assets/images/saddles/PrimalItemArmor_PhiomiaSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PhiomiaSaddle.PrimalItemArmor_PhiomiaSaddle'",
    id: 281
  },
  {
    nameFr: "Selle de Spinosaure",
    key: "PrimalItemArmor_SpinoSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Spinosaure.",
    image: "assets/images/saddles/PrimalItemArmor_SpinoSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SpinoSaddle.PrimalItemArmor_SpinoSaddle'",
    id: 299
  },
  {
    nameFr: "Selle de Plésiosaure",
    key: "PrimalItemArmor_PlesiaSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Plésiosaure.",
    image: "assets/images/saddles/PrimalItemArmor_PlesiaSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PlesiaSaddle.PrimalItemArmor_PlesiaSaddle'",
    id: 309
  },
  {
    nameFr: "Selle d'Ichthyosaure",
    key: "PrimalItemArmor_DolphinSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Ichthyosaure.",
    image: "assets/images/saddles/PrimalItemArmor_DolphinSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_DolphinSaddle.PrimalItemArmor_DolphinSaddle'",
    id: 310
  },
  {
    nameFr: "Selle de Doedicurus",
    key: "PrimalItemArmor_DoedSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Doedicurus.",
    image: "assets/images/saddles/PrimalItemArmor_DoedSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_DoedSaddle.PrimalItemArmor_DoedSaddle'",
    id: 389
  },
  {
    nameFr: "Plateforme pour Brontosaure",
    key: "PrimalItemArmor_SauroSaddle_Platform_C",
    defaultValue: 1,
    category: "Selles",
    description: "Plateforme pour Brontosaure.",
    image: "assets/images/saddles/PrimalItemArmor_SauroSaddle_Platform_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SauroSaddle_Platform.PrimalItemArmor_SauroSaddle_Platform'",
    id: 411
  },
  {
    nameFr: "Selle de Pachycéphalosaure",
    key: "PrimalItemArmor_PachySaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Pachycéphalosaure.",
    image: "assets/images/saddles/PrimalItemArmor_PachySaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PachySaddle.PrimalItemArmor_PachySaddle'",
    id: 412
  },
  {
    nameFr: "Selle de Paraceratherium",
    key: "PrimalItemArmor_Paracer_Saddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Paraceratherium.",
    image: "assets/images/saddles/PrimalItemArmor_Paracer_Saddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_Paracer_Saddle.PrimalItemArmor_Paracer_Saddle'",
    id: 417
  },
  {
    nameFr: "Plateforme pour Paraceratherium",
    key: "PrimalItemArmor_ParacerSaddle_Platform_C",
    defaultValue: 1,
    category: "Selles",
    description: "Plateforme pour Paraceratherium.",
    image: "assets/images/saddles/PrimalItemArmor_ParacerSaddle_Platform_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ParacerSaddle_Platform.PrimalItemArmor_ParacerSaddle_Platform'",
    id: 418
  },
  {
    nameFr: "Selle de Beelzebufo",
    key: "PrimalItemArmor_ToadSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Beelzebufo.",
    image: "assets/images/saddles/PrimalItemArmor_ToadSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ToadSaddle.PrimalItemArmor_ToadSaddle'",
    id: 422
  },
  {
    nameFr: "Selle de Mégalocéros",
    key: "PrimalItemArmor_StagSaddle_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle pour Mégalocéros.",
    image: "assets/images/saddles/PrimalItemArmor_StagSaddle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_StagSaddle.PrimalItemArmor_StagSaddle'",
    id: 423
  },
  {
    nameFr: "Selle Tek d'Astrocetus",
    key: "PrimalItemArmor_SpaceWhaleSaddle_Tek_C",
    defaultValue: 1,
    category: "Selles",
    description: "Selle Tek pour Astrocetus.",
    image: "assets/images/saddles/PrimalItemArmor_SpaceWhaleSaddle_Tek_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/Dinos/SpaceWhale/PrimalItemArmor_SpaceWhaleSaddle_Tek.PrimalItemArmor_SpaceWhaleSaddle_Tek'",
    id: null
  }
];
