export const TOOLS = [
  {
    nameFr: "Caisse de butin - Niv 1",
    key: "PrimalItemConsumable_Lootcrate_lvl1_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Caisse de butin de niveau 1 contenant des objets aléatoires.",
    image: "assets/images/resources/PrimalItemConsumable_Lootcrate_lvl1_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/CoreBlueprints/Items/PrimalItemConsumable_Lootcrate_lvl1.PrimalItemConsumable_Lootcrate_lvl1'",
    id: null
  },
  {
    nameFr: "Caisse de butin - Niv 2",
    key: "PrimalItemConsumable_Lootcrate_lvl2_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Caisse de butin de niveau 2 contenant des objets aléatoires.",
    image: "assets/images/resources/PrimalItemConsumable_Lootcrate_lvl2_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/CoreBlueprints/Items/PrimalItemConsumable_Lootcrate_lvl2.PrimalItemConsumable_Lootcrate_lvl2'",
    id: null
  },
  {
    nameFr: "Caisse de butin - Niv 3",
    key: "PrimalItemConsumable_Lootcrate_lvl3_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Caisse de butin de niveau 3 contenant des objets aléatoires.",
    image: "assets/images/resources/PrimalItemConsumable_Lootcrate_lvl3_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/CoreBlueprints/Items/PrimalItemConsumable_Lootcrate_lvl3.PrimalItemConsumable_Lootcrate_lvl3'",
    id: null
  },
  {
    nameFr: "Caméra",
    key: "PrimalItem_Camera_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Caméra pour capturer des images ou vidéos dans le jeu.",
    image: "assets/images/resources/PrimalItem_Camera_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItem_Camera.PrimalItem_Camera'",
    id: null
  },
  {
    nameFr: "Canne à pêche",
    key: "PrimalItem_WeaponFishingRod_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Canne à pêche utilisée pour attraper des poissons.",
    image: "assets/images/resources/PrimalItem_WeaponFishingRod_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponFishingRod.PrimalItem_WeaponFishingRod'",
    id: null
  },
  {
    nameFr: "Ciseaux",
    key: "PrimalItem_WeaponScissors_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Ciseaux utilisés pour couper divers matériaux.",
    image: "assets/images/resources/PrimalItem_WeaponScissors_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponScissors.PrimalItem_WeaponScissors'",
    id: null
  },
  {
    nameFr: "Cryopod",
    key: "PrimalItem_WeaponEmptyCryopod_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Cryopod vide utilisé pour stocker des créatures.",
    image: "assets/images/resources/PrimalItem_WeaponEmptyCryopod_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Weapons/PrimalItem_WeaponEmptyCryopod.PrimalItem_WeaponEmptyCryopod'",
    id: null
  },
  {
    nameFr: "Filet de pêche",
    key: "PrimalItem_WeaponFishingNet_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Filet de pêche utilisé pour attraper plusieurs poissons à la fois.",
    image: "assets/images/resources/PrimalItem_WeaponFishingNet_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/Weapons/FishingNet/PrimalItem_WeaponFishingNet.PrimalItem_WeaponFishingNet'",
    id: null
  },
  {
    nameFr: "Foreuse",
    key: "PrimalItem_WeaponMiningDrill_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Foreuse utilisée pour miner des ressources.",
    image: "assets/images/resources/PrimalItem_WeaponMiningDrill_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/Weapons/MiningDrill/PrimalItem_WeaponMiningDrill.PrimalItem_WeaponMiningDrill'",
    id: null
  },
  {
    nameFr: "Fouet",
    key: "PrimalItem_WeaponWhip_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Fouet utilisé pour attaquer ou contrôler des créatures.",
    image: "assets/images/resources/PrimalItem_WeaponWhip_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/WeaponWhip/PrimalItem_WeaponWhip.PrimalItem_WeaponWhip'",
    id: null
  },
  {
    nameFr: "Jumelles électroniques",
    key: "PrimalItem_WeaponElectronicBinoculars_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Jumelles électroniques pour observer à distance.",
    image: "assets/images/resources/PrimalItem_WeaponElectronicBinoculars_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/WeaponElectronicBinoculars/PrimalItem_WeaponElectronicBinoculars.PrimalItem_WeaponElectronicBinoculars'",
    id: null
  },
  {
    nameFr: "Loupe",
    key: "PrimalItem_WeaponMagnifyingGlass_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Loupe utilisée pour examiner des objets de près.",
    image: "assets/images/resources/PrimalItem_WeaponMagnifyingGlass_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItem_WeaponMagnifyingGlass.PrimalItem_WeaponMagnifyingGlass'",
    id: null
  },
  {
    nameFr: "Outil de taxidermie",
    key: "PrimalItem_WeaponTaxidermyTool_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Outil de taxidermie utilisé pour créer des trophées.",
    image: "assets/images/resources/PrimalItem_WeaponTaxidermyTool_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Weapons/PrimalItem_WeaponTaxidermyTool.PrimalItem_WeaponTaxidermyTool'",
    id: null
  },
  {
    nameFr: "Pinces",
    key: "PrimalItem_Pliers_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Pinces utilisées pour manipuler des objets et des matériaux.",
    image: "assets/images/resources/PrimalItem_Pliers_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItem_Pliers.PrimalItem_Pliers'",
    id: null
  },
  {
    nameFr: "Tronçonneuse",
    key: "PrimalItem_ChainSaw_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Tronçonneuse utilisée pour abattre des arbres et couper des matériaux.",
    image: "assets/images/resources/PrimalItem_ChainSaw_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/WeaponChainsaw/PrimalItem_ChainSaw.PrimalItem_ChainSaw'",
    id: null
  },
  {
    nameFr: "Pioche en pierre",
    key: "PrimalItem_WeaponStonePick_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Pioche en pierre pour miner des ressources de base.",
    image: "assets/images/resources/PrimalItem_WeaponStonePick_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponStonePick.PrimalItem_WeaponStonePick'",
    id: 33
  },
  {
    nameFr: "Hache en pierre",
    key: "PrimalItem_WeaponStoneHatchet_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Hache en pierre pour couper du bois et miner.",
    image: "assets/images/resources/PrimalItem_WeaponStoneHatchet_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponStoneHatchet.PrimalItem_WeaponStoneHatchet'",
    id: 34
  },
  {
    nameFr: "Pioche en métal",
    key: "PrimalItem_WeaponMetalPick_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Pioche en métal pour extraire des ressources plus efficacement.",
    image: "assets/images/resources/PrimalItem_WeaponMetalPick_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponMetalPick.PrimalItem_WeaponMetalPick'",
    id: 35
  },
  {
    nameFr: "Hache en métal",
    key: "PrimalItem_WeaponMetalHatchet_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Hache en métal pour couper des arbres et récolter des ressources.",
    image: "assets/images/resources/PrimalItem_WeaponMetalHatchet_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponMetalHatchet.PrimalItem_WeaponMetalHatchet'",
    id: 36
  },
  {
    nameFr: "Torche",
    key: "PrimalItem_WeaponTorch_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Torche pour s'éclairer dans les environnements sombres.",
    image: "assets/images/resources/PrimalItem_WeaponTorch_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponTorch.PrimalItem_WeaponTorch'",
    id: 37
  },
  {
    nameFr: "Pinceau",
    key: "PrimalItem_WeaponPaintbrush_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Pinceau utilisé pour peindre et personnaliser les objets.",
    image: "assets/images/resources/PrimalItem_WeaponPaintbrush_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponPaintbrush.PrimalItem_WeaponPaintbrush'",
    id: 38
  },
  {
    nameFr: "Kit de Prélèvement sanguin",
    key: "PrimalItem_BloodExtractor_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Kit pour prélever du sang des créatures.",
    image: "assets/images/resources/PrimalItem_BloodExtractor_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItem_BloodExtractor.PrimalItem_BloodExtractor'",
    id: 44
  },
  {
    nameFr: "GPS",
    key: "PrimalItem_WeaponGPS_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "GPS pour localiser des points spécifiques sur la carte.",
    image: "assets/images/resources/PrimalItem_WeaponGPS_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItem_WeaponGPS.PrimalItem_WeaponGPS'",
    id: 71
  },
  {
    nameFr: "Boussole",
    key: "PrimalItem_WeaponCompass_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Boussole pour s'orienter et naviguer.",
    image: "assets/images/resources/PrimalItem_WeaponCompass_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItem_WeaponCompass.PrimalItem_WeaponCompass'",
    id: 136
  },
  {
    nameFr: "Radio",
    key: "PrimalItemRadio_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Radio pour écouter des communications.",
    image: "assets/images/resources/PrimalItemRadio_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemRadio.PrimalItemRadio'",
    id: 140
  },
  {
    nameFr: "Longue-vue",
    key: "PrimalItem_WeaponSpyglass_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Longue-vue pour observer à distance.",
    image: "assets/images/resources/PrimalItem_WeaponSpyglass_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/Test/PrimalItem_WeaponSpyglass.PrimalItem_WeaponSpyglass'",
    id: 279
  },
  {
    nameFr: "Faucille",
    key: "PrimalItem_WeaponSickle_C",
    defaultValue: 1,
    category: "TOOLS",
    description: "Faucille utilisée pour récolter des plantes.",
    image: "assets/images/resources/PrimalItem_WeaponSickle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponSickle.PrimalItem_WeaponSickle'",
    id: 376
  }
];
