export const TROPHIES = [
  {
    nameFr: "Trophée de Rockwell (Alpha)",
    key: "PrimalItemTrophy_Rockwell_Beta_Alpha_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée de Rockwell en mode Alpha.",
    image: "assets/images/trophies/PrimalItemTrophy_Rockwell_Beta_Alpha_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Trophies/PrimalItemTrophy_Rockwell_Beta_Alpha.PrimalItemTrophy_Rockwell_Beta_Alpha'",
    id: null
  },
  {
    nameFr: "Trophée de Rockwell (Beta)",
    key: "PrimalItemTrophy_Rockwell_Beta_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée de Rockwell en mode Beta.",
    image: "assets/images/trophies/PrimalItemTrophy_Rockwell_Beta_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Trophies/PrimalItemTrophy_Rockwell_Beta.PrimalItemTrophy_Rockwell_Beta'",
    id: null
  },
  {
    nameFr: "Trophée de Rockwell (Gamma)",
    key: "PrimalItemTrophy_Rockwell_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée de Rockwell en mode Gamma.",
    image: "assets/images/trophies/PrimalItemTrophy_Rockwell_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Items/Trophies/PrimalItemTrophy_Rockwell.PrimalItemTrophy_Rockwell'",
    id: null
  },
  {
    nameFr: "Trophée de la Broodmother (Alpha)",
    key: "PrimalItemTrophy_Broodmother_Alpha_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée de la Broodmother en mode Alpha.",
    image: "assets/images/trophies/PrimalItemTrophy_Broodmother_Alpha_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_Broodmother_Alpha.PrimalItemTrophy_Broodmother_Alpha'",
    id: null
  },
  {
    nameFr: "Trophée de la Broodmother (Beta)",
    key: "PrimalItemTrophy_Broodmother_Beta_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée de la Broodmother en mode Beta.",
    image: "assets/images/trophies/PrimalItemTrophy_Broodmother_Beta_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_Broodmother_Beta.PrimalItemTrophy_Broodmother_Beta'",
    id: null
  },
  {
    nameFr: "Trophée de la Broodmother (Gamma)",
    key: "PrimalItemTrophy_Broodmother_Gamma_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée de la Broodmother en mode Gamma.",
    image: "assets/images/trophies/PrimalItemTrophy_Broodmother_Gamma_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_Broodmother_Gamma.PrimalItemTrophy_Broodmother_Gamma'",
    id: null
  },
  {
    nameFr: "Trophée de la Manticore (Alpha)",
    key: "PrimalItemTrophy_Manticore_Alpha_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée de la Manticore en mode Alpha.",
    image: "assets/images/trophies/PrimalItemTrophy_Manticore_Alpha_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/Structures/TrophyHeads/Manticore_Trophy/PrimalItemTrophy_Manticore_Alpha.PrimalItemTrophy_Manticore_Alpha'",
    id: null
  },
  {
    nameFr: "Trophée de la Manticore (Beta)",
    key: "PrimalItemTrophy_Manticore_Beta_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée de la Manticore en mode Beta.",
    image: "assets/images/trophies/PrimalItemTrophy_Manticore_Beta_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/Structures/TrophyHeads/Manticore_Trophy/PrimalItemTrophy_Manticore_Beta.PrimalItemTrophy_Manticore_Beta'",
    id: null
  },
  {
    nameFr: "Trophée de la Manticore (Gamma)",
    key: "PrimalItemTrophy_Manticore_Gamma_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée de la Manticore en mode Gamma.",
    image: "assets/images/trophies/PrimalItemTrophy_Manticore_Gamma_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/Structures/TrophyHeads/Manticore_Trophy/PrimalItemTrophy_Manticore_Gamma.PrimalItemTrophy_Manticore_Gamma'",
    id: null
  },
  {
    nameFr: "Trophée de la Reine des Wyvernes de Cristal (Alpha)",
    key: "PrimalItemTrophy_CIBoss_Alpha_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée de la Reine des Wyvernes de Cristal en mode Alpha.",
    image: "assets/images/trophies/PrimalItemTrophy_CIBoss_Alpha_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Mods/CrystalIsles/Assets/Dinos/CIBoss/Trophy/PrimalItemTrophy_CIBoss_Alpha.PrimalItemTrophy_CIBoss_Alpha'",
    id: null
  },
  {
    nameFr: "Trophée de la Reine des Wyvernes de Cristal (Beta)",
    key: "PrimalItemTrophy_CIBoss_Beta_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée de la Reine des Wyvernes de Cristal en mode Beta.",
    image: "assets/images/trophies/PrimalItemTrophy_CIBoss_Beta_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Mods/CrystalIsles/Assets/Dinos/CIBoss/Trophy/PrimalItemTrophy_CIBoss_Beta.PrimalItemTrophy_CIBoss_Beta'",
    id: null
  },
  {
    nameFr: "Trophée de la Reine des Wyvernes de Cristal (Gamma)",
    key: "PrimalItemTrophy_CIBoss_Gamma_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée de la Reine des Wyvernes de Cristal en mode Gamma.",
    image: "assets/images/trophies/PrimalItemTrophy_CIBoss_Gamma_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Mods/CrystalIsles/Assets/Dinos/CIBoss/Trophy/PrimalItemTrophy_CIBoss_Gamma.PrimalItemTrophy_CIBoss_Gamma'",
    id: null
  },
  {
    nameFr: "Trophée de la Wyverne Alpha",
    key: "PrimalItemTrophy_AlphaWyvern_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée de la Wyverne Alpha.",
    image: "assets/images/trophies/PrimalItemTrophy_AlphaWyvern_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_AlphaWyvern.PrimalItemTrophy_AlphaWyvern'",
    id: null
  },
  {
    nameFr: "Trophée du Dragon (Alpha)",
    key: "PrimalItemTrophy_Dragon_Alpha_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du Dragon en mode Alpha.",
    image: "assets/images/trophies/PrimalItemTrophy_Dragon_Alpha_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_Dragon_Alpha.PrimalItemTrophy_Dragon_Alpha'",
    id: null
  },
  {
    nameFr: "Trophée du Dragon (Beta)",
    key: "PrimalItemTrophy_Dragon_Beta_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du Dragon en mode Beta.",
    image: "assets/images/trophies/PrimalItemTrophy_Dragon_Beta_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_Dragon_Beta.PrimalItemTrophy_Dragon_Beta'",
    id: null
  },
  {
    nameFr: "Trophée du Dragon (Gamma)",
    key: "PrimalItemTrophy_Dragon_Gamma_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du Dragon en mode Gamma.",
    image: "assets/images/trophies/PrimalItemTrophy_Dragon_Gamma_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_Dragon_Gamma.PrimalItemTrophy_Dragon_Gamma'",
    id: null
  },
  {
    nameFr: "Trophée du Maître contrôleur",
    key: "PrimalItemTrophy_MasterController_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du Maître contrôleur.",
    image: "assets/images/trophies/PrimalItemTrophy_MasterController_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/CoreBlueprints/Items/Trophies/PrimalItemTrophy_MasterController.PrimalItemTrophy_MasterController'",
    id: null
  },
  {
    nameFr: "Trophée du Megapithecus (Alpha)",
    key: "PrimalItemTrophy_Gorilla_Alpha_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du Megapithecus en mode Alpha.",
    image: "assets/images/trophies/PrimalItemTrophy_Gorilla_Alpha_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_Gorilla_Alpha.PrimalItemTrophy_Gorilla_Alpha'",
    id: null
  },
  {
    nameFr: "Trophée du Megapithecus (Beta)",
    key: "PrimalItemTrophy_Gorilla_Beta_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du Megapithecus en mode Beta.",
    image: "assets/images/trophies/PrimalItemTrophy_Gorilla_Beta_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_Gorilla_Beta.PrimalItemTrophy_Gorilla_Beta'",
    id: null
  },
  {
    nameFr: "Trophée du Megapithecus (Gamma)",
    key: "PrimalItemTrophy_Gorilla_Gamma_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du Megapithecus en mode Gamma.",
    image: "assets/images/trophies/PrimalItemTrophy_Gorilla_Gamma_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_Gorilla_Gamma.PrimalItemTrophy_Gorilla_Gamma'",
    id: null
  },
  {
    nameFr: "Trophée du T-Rex (Alpha)",
    key: "PrimalItemTrophy_AlphaRex_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du T-Rex en mode Alpha.",
    image: "assets/images/trophies/PrimalItemTrophy_AlphaRex_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_AlphaRex.PrimalItemTrophy_AlphaRex'",
    id: null
  },
  {
    nameFr: "Trophée du Roi des Titans (Alpha)",
    key: "PrimalItemTrophy_Kaiju_King_Alpha_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du Roi des Titans en mode Alpha.",
    image: "assets/images/trophies/PrimalItemTrophy_Kaiju_King_Alpha_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Trophies/PrimalItemTrophy_Kaiju_King_Alpha.PrimalItemTrophy_Kaiju_King_Alpha'",
    id: null
  },
  {
    nameFr: "Trophée du Roi des Titans (Beta)",
    key: "PrimalItemTrophy_Kaiju_King_Beta_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du Roi des Titans en mode Beta.",
    image: "assets/images/trophies/PrimalItemTrophy_Kaiju_King_Beta_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Trophies/PrimalItemTrophy_Kaiju_King_Beta.PrimalItemTrophy_Kaiju_King_Beta'",
    id: null
  },
  {
    nameFr: "Trophée du Roi des Titans (Gamma)",
    key: "PrimalItemTrophy_Kaiju_King_Gamma_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du Roi des Titans en mode Gamma.",
    image: "assets/images/trophies/PrimalItemTrophy_Kaiju_King_Gamma_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Trophies/PrimalItemTrophy_Kaiju_King_Gamma.PrimalItemTrophy_Kaiju_King_Gamma'",
    id: null
  },
  {
    nameFr: "Trophée du Titan de Glace",
    key: "PrimalItemTrophy_Kaiju_Ice_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du Titan de Glace.",
    image: "assets/images/trophies/PrimalItemTrophy_Kaiju_Ice_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Trophies/PrimalItemTrophy_Kaiju_Ice.PrimalItemTrophy_Kaiju_Ice'",
    id: null
  },
  {
    nameFr: "Trophée du Titan des Forêts",
    key: "PrimalItemTrophy_Kaiju_Forest_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du Titan des Forêts.",
    image: "assets/images/trophies/PrimalItemTrophy_Kaiju_Forest_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Trophies/PrimalItemTrophy_Kaiju_Forest.PrimalItemTrophy_Kaiju_Forest'",
    id: null
  },
  {
    nameFr: "Trophée du Titan du Désert",
    key: "PrimalItemTrophy_Kaiju_Desert_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du Titan du Désert.",
    image: "assets/images/trophies/PrimalItemTrophy_Kaiju_Desert_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Trophies/PrimalItemTrophy_Kaiju_Desert.PrimalItemTrophy_Kaiju_Desert'",
    id: null
  },
  {
    nameFr: "Trophée du Ver des sables (Alpha)",
    key: "PrimalItemTrophy_AlphaWorm_C",
    defaultValue: 1,
    category: "Trophées",
    description: "Trophée du Ver des sables en mode Alpha.",
    image: "assets/images/trophies/PrimalItemTrophy_AlphaWorm_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Trophies/PrimalItemTrophy_AlphaWorm.PrimalItemTrophy_AlphaWorm'",
    id: null
  }
];
