export const WEAPONS = [
  {
    nameFr: "Arbalète",
    key: "PrimalItem_WeaponCrossbow_C",
    defaultValue: 1,
    category: "Armes",
    description: "Arbalète puissante pour chasser ou combattre.",
    image: "assets/images/weapons/PrimalItem_WeaponCrossbow_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponCrossbow.PrimalItem_WeaponCrossbow'",
    id: 358
  },
  {
    nameFr: "Arc à poulie",
    key: "PrimalItem_WeaponCompoundBow_C",
    defaultValue: 1,
    category: "Armes",
    description: "Arc à poulie avancé pour une précision accrue.",
    image: "assets/images/weapons/PrimalItem_WeaponCompoundBow_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponCompoundBow.PrimalItem_WeaponCompoundBow'",
    id: 372
  },
  {
    nameFr: "Arc",
    key: "PrimalItem_WeaponBow_C",
    defaultValue: 1,
    category: "Armes",
    description: "Arc de base pour tirer des flèches.",
    image: "assets/images/weapons/PrimalItem_WeaponBow_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponBow.PrimalItem_WeaponBow'",
    id: 5
  },
  {
    nameFr: "Bocal de pétrole",
    key: "PrimalItem_WeaponOilJar_C",
    defaultValue: 10,
    category: "Armes",
    description: "Bocal rempli de pétrole inflammable.",
    image: "assets/images/weapons/PrimalItem_WeaponOilJar_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/WeaponOilJar/PrimalItem_WeaponOilJar.PrimalItem_WeaponOilJar'",
    id: null
  },
  {
    nameFr: "Bolas à chaîne métallique",
    key: "PrimalItemAmmo_ChainBola_C",
    defaultValue: 20,
    category: "Armes",
    description: "Bolas renforcées pour capturer des cibles plus grandes.",
    image: "assets/images/weapons/PrimalItemAmmo_ChainBola_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_ChainBola.PrimalItemAmmo_ChainBola'",
    id: null
  },
  {
    nameFr: "Bolas",
    key: "PrimalItem_WeaponBola_C",
    defaultValue: 10,
    category: "Armes",
    description: "Bolas pour immobiliser de petites cibles.",
    image: "assets/images/weapons/PrimalItem_WeaponBola_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponBola.PrimalItem_WeaponBola'",
    id: null
  },
  {
    nameFr: "Boomerang",
    key: "PrimalItem_WeaponBoomerang_C",
    defaultValue: 10,
    category: "Armes",
    description: "Boomerang pour assommer les cibles.",
    image: "assets/images/weapons/PrimalItem_WeaponBoomerang_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/WeaponBoomerang/PrimalItem_WeaponBoomerang.PrimalItem_WeaponBoomerang'",
    id: null
  },
  {
    nameFr: "Bâton lumineux",
    key: "PrimalItem_GlowStick_C",
    defaultValue: 20,
    category: "Armes",
    description: "Bâton lumineux pour éclairer les zones sombres.",
    image: "assets/images/weapons/PrimalItem_GlowStick_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/WeaponGlowStickThrow/PrimalItem_GlowStick.PrimalItem_GlowStick'",
    id: null
  },
  {
    nameFr: "Détonateur à distance pour C4",
    key: "PrimalItem_WeaponC4_C",
    defaultValue: 1,
    category: "Armes",
    description: "Détonateur pour faire exploser les charges C4.",
    image: "assets/images/weapons/PrimalItem_WeaponC4_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponC4.PrimalItem_WeaponC4'",
    id: 42
  },
  {
    nameFr: "Épée",
    key: "PrimalItem_WeaponSword_C",
    defaultValue: 1,
    category: "Armes",
    description: "Épée pour les combats rapprochés.",
    image: "assets/images/weapons/PrimalItem_WeaponSword_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponSword.PrimalItem_WeaponSword'",
    id: null
  },
  {
    nameFr: "Fruit de Plante Spécimen Z",
    key: "PrimalItem_PlantSpeciesZ_Grenade_C",
    defaultValue: 100,
    category: "Armes",
    description: "Grenade à base de fruit de Plante Spécimen Z.",
    image: "assets/images/weapons/PrimalItem_PlantSpeciesZ_Grenade_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Aberration/WeaponPlantSpeciesZ/PrimalItem_PlantSpeciesZ_Grenade.PrimalItem_PlantSpeciesZ_Grenade'",
    id: null
  },
  {
    nameFr: "Fusil Admin",
    key: "PrimalItem_WeaponAdminBlinkRifle_C",
    defaultValue: 1,
    category: "Armes",
    description: "Fusil Admin pour les tests en mode administrateur.",
    image: "assets/images/weapons/PrimalItem_WeaponAdminBlinkRifle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/Weapon_AdminBlinkRifle/PrimalItem_WeaponAdminBlinkRifle.PrimalItem_WeaponAdminBlinkRifle'",
    id: null
  },
  {
    nameFr: "Fusil Tek",
    key: "PrimalItem_TekRifle_C",
    defaultValue: 1,
    category: "Armes",
    description: "Fusil avancé utilisant la technologie Tek.",
    image: "assets/images/weapons/PrimalItem_TekRifle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_TekRifle.PrimalItem_TekRifle'",
    id: null
  },
  {
    nameFr: "Fusil d'assaut",
    key: "PrimalItem_WeaponRifle_C",
    defaultValue: 1,
    category: "Armes",
    description: "Fusil d'assaut pour les combats à distance.",
    image: "assets/images/weapons/PrimalItem_WeaponRifle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponRifle.PrimalItem_WeaponRifle'",
    id: 2
  },
  {
    nameFr: "Fusil de précision",
    key: "PrimalItem_WeaponMachinedSniper_C",
    defaultValue: 1,
    category: "Armes",
    description: "Fusil de précision pour les tirs à longue distance.",
    image: "assets/images/weapons/PrimalItem_WeaponMachinedSniper_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponMachinedSniper.PrimalItem_WeaponMachinedSniper'",
    id: 431
  },
  {
    nameFr: "Fusil à canon long",
    key: "PrimalItem_WeaponOneShotRifle_C",
    defaultValue: 1,
    category: "Armes",
    description: "Fusil à un coup puissant pour des tirs précis.",
    image: "assets/images/weapons/PrimalItem_WeaponOneShotRifle_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponOneShotRifle.PrimalItem_WeaponOneShotRifle'",
    id: 131
  },
  {
    nameFr: "Fusil à canon scié",
    key: "PrimalItem_WeaponShotgun_C",
    defaultValue: 1,
    category: "Armes",
    description: "Fusil à canon scié pour les combats rapprochés.",
    image: "assets/images/weapons/PrimalItem_WeaponShotgun_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponShotgun.PrimalItem_WeaponShotgun'",
    id: 263
  },
  {
    nameFr: "Fusil à pompe",
    key: "PrimalItem_WeaponMachinedShotgun_C",
    defaultValue: 1,
    category: "Armes",
    description: "Fusil à pompe pour les combats rapprochés.",
    image: "assets/images/weapons/PrimalItem_WeaponMachinedShotgun_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponMachinedShotgun.PrimalItem_WeaponMachinedShotgun'",
    id: 357
  },
  {
    nameFr: "Grand Piège à Ours",
    key: "PrimalItemStructure_BearTrap_Large_C",
    defaultValue: 10,
    category: "Armes",
    description: "Grand piège pour capturer de grandes créatures.",
    image: "assets/images/weapons/PrimalItemStructure_BearTrap_Large_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_BearTrap_Large.PrimalItemStructure_BearTrap_Large'",
    id: 380
  },
  {
    nameFr: "Grenade Tek",
    key: "PrimalItem_TekGrenade_C",
    defaultValue: 10,
    category: "Armes",
    description: "Grenade utilisant la technologie Tek pour des explosions puissantes.",
    image: "assets/images/weapons/PrimalItem_TekGrenade_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_TekGrenade.PrimalItem_TekGrenade'",
    id: null
  },
  {
    nameFr: "Grenade de Gravité Tek",
    key: "PrimalItem_WeaponTekGravityGrenade_C",
    defaultValue: 10,
    category: "Armes",
    description: "Grenade Tek générant un champ de gravité.",
    image: "assets/images/weapons/PrimalItem_WeaponTekGravityGrenade_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/Extinction/CoreBlueprints/Weapons/PrimalItem_WeaponTekGravityGrenade.PrimalItem_WeaponTekGravityGrenade'",
    id: null
  },
  {
    nameFr: "Grenade empoisonnée",
    key: "PrimalItem_PoisonGrenade_C",
    defaultValue: 10,
    category: "Armes",
    description: "Grenade relâchant un gaz toxique pour endommager les ennemis.",
    image: "assets/images/weapons/PrimalItem_PoisonGrenade_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_PoisonGrenade.PrimalItem_PoisonGrenade'",
    id: 430
  },
  {
    nameFr: "Grenade fumigène",
    key: "PrimalItem_GasGrenade_C",
    defaultValue: 10,
    category: "Armes",
    description: "Grenade qui crée un nuage de fumée pour désorienter les ennemis.",
    image: "assets/images/weapons/PrimalItem_GasGrenade_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_GasGrenade.PrimalItem_GasGrenade'",
    id: null
  },
  {
    nameFr: "Grenade à fragmentation",
    key: "PrimalItem_WeaponClusterGrenade_C",
    defaultValue: 100,
    category: "Armes",
    description: "Grenade qui se divise en plusieurs explosions secondaires.",
    image: "assets/images/weapons/PrimalItem_WeaponClusterGrenade_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/WeaponClusterGrenade/PrimalItem_WeaponClusterGrenade.PrimalItem_WeaponClusterGrenade'",
    id: null
  },
  {
    nameFr: "Grenade",
    key: "PrimalItem_WeaponGrenade_C",
    defaultValue: 10,
    category: "Armes",
    description: "Grenade explosive standard pour endommager les ennemis.",
    image: "assets/images/weapons/PrimalItem_WeaponGrenade_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponGrenade.PrimalItem_WeaponGrenade'",
    id: 6
  },
  {
    nameFr: "Harpon",
    key: "PrimalItem_WeaponHarpoon_C",
    defaultValue: 1,
    category: "Armes",
    description: "Arme pour chasser sous l'eau.",
    image: "assets/images/weapons/PrimalItem_WeaponHarpoon_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponHarpoon.PrimalItem_WeaponHarpoon'",
    id: null
  },
  {
    nameFr: "Lampe tactique (Accessoire)",
    key: "PrimalItemWeaponAttachment_Flashlight_C",
    defaultValue: 1,
    category: "Accessoires",
    description: "Accessoire pour ajouter une lampe à vos armes.",
    image: "assets/images/weapons/PrimalItemWeaponAttachment_Flashlight_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/WeaponAttachments/PrimalItemWeaponAttachment_Flashlight.PrimalItemWeaponAttachment_Flashlight'",
    id: 202
  },
  {
    nameFr: "Lance Ardente",
    key: "PrimalItem_WeaponSpear_Flame_Gauntlet_C",
    defaultValue: 1,
    category: "Armes",
    description: "Lance enflammée pour des attaques incendiaires.",
    image: "assets/images/weapons/PrimalItem_WeaponSpear_Flame_Gauntlet_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/CoreBlueprints/Weapons/Mission/PrimalItem_WeaponSpear_Flame_Gauntlet.PrimalItem_WeaponSpear_Flame_Gauntlet'",
    id: null
  },
  {
    nameFr: "Lance de joute",
    key: "PrimalItem_WeaponLance_C",
    defaultValue: 1,
    category: "Armes",
    description: "Lance utilisée pour les combats de joute.",
    image: "assets/images/weapons/PrimalItem_WeaponLance_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponLance.PrimalItem_WeaponLance'",
    id: null
  },
  {
    nameFr: "Lance en bois",
    key: "PrimalItem_WeaponSpear_C",
    defaultValue: 10,
    category: "Armes",
    description: "Lance de base fabriquée en bois.",
    image: "assets/images/weapons/PrimalItem_WeaponSpear_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponSpear.PrimalItem_WeaponSpear'",
    id: 57
  },
  {
    nameFr: "Lance en métal",
    key: "PrimalItem_WeaponPike_C",
    defaultValue: 1,
    category: "Armes",
    description: "Lance renforcée en métal pour plus de durabilité.",
    image: "assets/images/weapons/PrimalItem_WeaponPike_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponPike.PrimalItem_WeaponPike'",
    id: 139
  },
  {
    nameFr: "Lance-Roquettes",
    key: "PrimalItem_WeaponRocketLauncher_C",
    defaultValue: 1,
    category: "Armes",
    description: "Lance-roquettes pour des attaques explosives puissantes.",
    image: "assets/images/weapons/PrimalItem_WeaponRocketLauncher_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponRocketLauncher.PrimalItem_WeaponRocketLauncher'",
    id: 3
  },
  {
    nameFr: "Lance-flamme",
    key: "PrimalItem_WeapFlamethrower_C",
    defaultValue: 1,
    category: "Armes",
    description: "Lance-flamme pour brûler les ennemis et les obstacles.",
    image: "assets/images/weapons/PrimalItem_WeapFlamethrower_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/ScorchedEarth/WeaponFlamethrower/PrimalItem_WeapFlamethrower.PrimalItem_WeapFlamethrower'",
    id: null
  },
  {
    nameFr: "Lance-grenade Tek",
    key: "PrimalItem_WeaponTekGrenadeLauncher_C",
    defaultValue: 1,
    category: "Armes",
    description: "Lanceur de grenades Tek avancé pour des explosions massives.",
    image: "assets/images/weapons/PrimalItem_WeaponTekGrenadeLauncher_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/Weapons/TekGrenadeLauncher/PrimalItem_WeaponTekGrenadeLauncher.PrimalItem_WeaponTekGrenadeLauncher'",
    id: null
  },
  {
    nameFr: "Lance-pierre",
    key: "PrimalItem_WeaponSlingshot_C",
    defaultValue: 1,
    category: "Armes",
    description: "Lance-pierre pour assommer les petites créatures.",
    image: "assets/images/weapons/PrimalItem_WeaponSlingshot_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponSlingshot.PrimalItem_WeaponSlingshot'",
    id: 138
  },
  {
    nameFr: "Lanterne de Charge",
    key: "PrimalItem_WeaponRadioactiveLanternCharge_C",
    defaultValue: 1,
    category: "Armes",
    description: "Lanterne pour repousser les créatures sensibles à la lumière.",
    image: "assets/images/weapons/PrimalItem_WeaponRadioactiveLanternCharge_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/WeaponRadioactiveLanternCharge/PrimalItem_WeaponRadioactiveLanternCharge.PrimalItem_WeaponRadioactiveLanternCharge'",
    id: null
  },
  {
    nameFr: "Lasso",
    key: "PrimalItem_WeaponLasso_C",
    defaultValue: 10,
    category: "Armes",
    description: "Lasso pour capturer et immobiliser les créatures.",
    image: "assets/images/weapons/PrimalItem_WeaponLasso_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponLasso.PrimalItem_WeaponLasso'",
    id: null
  },
  {
    nameFr: "Lunette de visée",
    key: "PrimalItemWeaponAttachment_Scope_C",
    defaultValue: 1,
    category: "Accessoires",
    description: "Accessoire pour améliorer la précision des armes à distance.",
    image: "assets/images/weapons/PrimalItemWeaponAttachment_Scope_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/WeaponAttachments/PrimalItemWeaponAttachment_Scope.PrimalItemWeaponAttachment_Scope'",
    id: 137
  },
  {
    nameFr: "Massue",
    key: "PrimalItem_WeaponStoneClub_C",
    defaultValue: 1,
    category: "Armes",
    description: "Massue pour assommer les ennemis au corps à corps.",
    image: "assets/images/weapons/PrimalItem_WeaponStoneClub_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponStoneClub.PrimalItem_WeaponStoneClub'",
    id: 429
  },
  {
    nameFr: "Matraque électrique",
    key: "PrimalItem_WeaponProd_C",
    defaultValue: 1,
    category: "Armes",
    description: "Matraque électrique pour neutraliser les ennemis.",
    image: "assets/images/weapons/PrimalItem_WeaponProd_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponProd.PrimalItem_WeaponProd'",
    id: 446
  },
  {
    nameFr: "Menottes",
    key: "PrimalItem_WeaponHandcuffs_C",
    defaultValue: 1,
    category: "Armes",
    description: "Menottes pour capturer et restreindre les ennemis.",
    image: "assets/images/weapons/PrimalItem_WeaponHandcuffs_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponHandcuffs.PrimalItem_WeaponHandcuffs'",
    id: 447
  },
  {
    nameFr: "Missile de croisière",
    key: "PrimalItem_WeaponTekCruiseMissile_C",
    defaultValue: 1,
    category: "Armes",
    description: "Missile de croisière Tek pour des attaques précises à longue distance.",
    image: "assets/images/weapons/PrimalItem_WeaponTekCruiseMissile_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/Weapons/CruiseMissile/PrimalItem_WeaponTekCruiseMissile.PrimalItem_WeaponTekCruiseMissile'",
    id: null
  },
  {
    nameFr: "Piolet d'escalade",
    key: "PrimalItem_WeaponClimbPick_C",
    defaultValue: 1,
    category: "Armes",
    description: "Outil pour escalader des surfaces verticales.",
    image: "assets/images/weapons/PrimalItem_WeaponClimbPick_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/CoreBlueprints/Weapons/PrimalItem_WeaponClimbPick.PrimalItem_WeaponClimbPick'",
    id: null
  },
  {
    nameFr: "Pistolet de détresse",
    key: "PrimalItem_WeaponFlareGun_C",
    defaultValue: 10,
    category: "Armes",
    description: "Pistolet pour lancer des fusées de détresse.",
    image: "assets/images/weapons/PrimalItem_WeaponFlareGun_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponFlareGun.PrimalItem_WeaponFlareGun'",
    id: 181
  },
  {
    nameFr: "Pistolet semi-auto",
    key: "PrimalItem_WeaponMachinedPistol_C",
    defaultValue: 1,
    category: "Armes",
    description: "Pistolet semi-automatique pour les combats rapprochés.",
    image: "assets/images/weapons/PrimalItem_WeaponMachinedPistol_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponMachinedPistol.PrimalItem_WeaponMachinedPistol'",
    id: 240
  },
  {
    nameFr: "Pistolet à Peinture",
    key: "PrimalItem_WeaponSprayPaint_C",
    defaultValue: 1,
    category: "Armes",
    description: "Pistolet pour appliquer de la peinture sur des objets.",
    image: "assets/images/weapons/PrimalItem_WeaponSprayPaint_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponSprayPaint.PrimalItem_WeaponSprayPaint'",
    id: 388
  },
  {
    nameFr: "Piège avec alarme sonore",
    key: "PrimalItem_WeaponAlarmTrap_C",
    defaultValue: 10,
    category: "Armes",
    description: "Piège avec alarme pour avertir en cas d'intrusion.",
    image: "assets/images/weapons/PrimalItem_WeaponAlarmTrap_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponAlarmTrap.PrimalItem_WeaponAlarmTrap'",
    id: 322
  },
  {
    nameFr: "Piège de Plante Spécimen Y",
    key: "PrimalItemStructure_PlantSpeciesYTrap_C",
    defaultValue: 10,
    category: "Armes",
    description: "Piège utilisant les graines de Plante Spécimen Y.",
    image: "assets/images/weapons/PrimalItemStructure_PlantSpeciesYTrap_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/ScorchedEarth/WeaponPlantSpeciesY/PrimalItemStructure_PlantSpeciesYTrap.PrimalItemStructure_PlantSpeciesYTrap'",
    id: null
  },
  {
    nameFr: "Piège explosif improvisé",
    key: "PrimalItem_WeaponTripwireC4_C",
    defaultValue: 10,
    category: "Armes",
    description: "Piège explosif utilisant des fils-pièges C4.",
    image: "assets/images/weapons/PrimalItem_WeaponTripwireC4_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponTripwireC4.PrimalItem_WeaponTripwireC4'",
    id: 46
  },
  {
    nameFr: "Piège narcotique",
    key: "PrimalItem_WeaponPoisonTrap_C",
    defaultValue: 10,
    category: "Armes",
    description: "Piège relâchant un gaz empoisonné pour endormir les ennemis.",
    image: "assets/images/weapons/PrimalItem_WeaponPoisonTrap_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponPoisonTrap.PrimalItem_WeaponPoisonTrap'",
    id: 321
  },
  {
    nameFr: "Piège à Ours",
    key: "PrimalItemStructure_BearTrap_C",
    defaultValue: 10,
    category: "Armes",
    description: "Piège pour capturer les créatures de taille moyenne.",
    image: "assets/images/weapons/PrimalItemStructure_BearTrap_C.png",
    stackable: true,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_BearTrap.PrimalItemStructure_BearTrap'",
    id: 379
  },
  {
    nameFr: "Récepteur pour Transpondeur",
    key: "PrimalItem_WeaponTransGPS_C",
    defaultValue: 1,
    category: "Armes",
    description: "Récepteur pour suivre les signaux des transpondeurs.",
    image: "assets/images/weapons/PrimalItem_WeaponTransGPS_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponTransGPS.PrimalItem_WeaponTransGPS'",
    id: 368
  },
  {
    nameFr: "Revolver",
    key: "PrimalItem_WeaponGun_C",
    defaultValue: 1,
    category: "Armes",
    description: "Revolver pour les combats rapprochés.",
    image: "assets/images/weapons/PrimalItem_WeaponGun_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponGun.PrimalItem_WeaponGun'",
    id: 1
  },
  {
    nameFr: "Silencieux",
    key: "PrimalItemWeaponAttachment_Silencer_C",
    defaultValue: 1,
    category: "Accessoires",
    description: "Accessoire pour réduire le bruit des tirs d'armes.",
    image: "assets/images/weapons/PrimalItemWeaponAttachment_Silencer_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/WeaponAttachments/PrimalItemWeaponAttachment_Silencer.PrimalItemWeaponAttachment_Silencer'",
    id: 203
  },
  {
    nameFr: "Sniper Tek",
    key: "PrimalItem_TekSniper_C",
    defaultValue: 1,
    category: "Armes",
    description: "Fusil de précision utilisant la technologie Tek.",
    image: "assets/images/weapons/PrimalItem_TekSniper_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Aberration/WeaponTekSniper/PrimalItem_TekSniper.PrimalItem_TekSniper'",
    id: null
  },
  {
    nameFr: "Télécommande pour Éclaireur",
    key: "PrimalItem_WeaponScoutRemote_C",
    defaultValue: 1,
    category: "Armes",
    description: "Télécommande pour contrôler les éclaireurs.",
    image: "assets/images/weapons/PrimalItem_WeaponScoutRemote_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Extinction/Dinos/Scout/PrimalItem_WeaponScoutRemote.PrimalItem_WeaponScoutRemote'",
    id: null
  },
  {
    nameFr: "Viseur Holographique",
    key: "PrimalItemWeaponAttachment_HoloScope_C",
    defaultValue: 1,
    category: "Accessoires",
    description: "Accessoire pour viser avec précision à longue distance.",
    image: "assets/images/weapons/PrimalItemWeaponAttachment_HoloScope_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/WeaponAttachments/PrimalItemWeaponAttachment_HoloScope.PrimalItemWeaponAttachment_HoloScope'",
    id: 215
  },
  {
    nameFr: "Viseur Laser",
    key: "PrimalItemWeaponAttachment_Laser_C",
    defaultValue: 1,
    category: "Accessoires",
    description: "Accessoire pour améliorer la précision avec un laser.",
    image: "assets/images/weapons/PrimalItemWeaponAttachment_Laser_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/WeaponAttachments/PrimalItemWeaponAttachment_Laser.PrimalItemWeaponAttachment_Laser'",
    id: 216
  },
  {
    nameFr: "Épée Tek",
    key: "PrimalItem_WeaponTekSword_C",
    defaultValue: 1,
    category: "Armes",
    description: "Épée avancée utilisant la technologie Tek.",
    image: "assets/images/weapons/PrimalItem_WeaponTekSword_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponTekSword.PrimalItem_WeaponTekSword'",
    id: null
  },
  {
    nameFr: "Éventreuses Tek",
    key: "PrimalItem_WeaponTekClaws_C",
    defaultValue: 1,
    category: "Armes",
    description: "Armes de mêlée avancées utilisant la technologie Tek.",
    image: "assets/images/weapons/PrimalItem_WeaponTekClaws_C.png",
    stackable: false,
    blueprint: "Blueprint'/Game/Genesis/Weapons/TekHandBlades/PrimalItem_WeaponTekClaws.PrimalItem_WeaponTekClaws'",
    id: null
  }
];
